ksumini/Algorithm-Study2.0

- .github/ISSUE_TEMPLATE/daily-coding-problem.yml
요샌 issue template를 yml 파일로 한다네요
> [FEAT]: add issue template(yml)

- Programmers/도넛과 막대 그래프/jisu.py
[Insight]
- 새로 생성된 정점은 그래프와 무관한 정점이며 다른 그래프로 뻗어나가는 간선밖에 존재하지 않음
- 그래프는 두 개 이상 존재하므로, 2개 이상 뻗어나가는 간선을 갖되, 들어오는 간선이 없는 점
- 다른 그래프의 임의의 정점으로 뻗어나감
- 그래프 순회를 통해 규칙을 찾아야 함
- 도넛 그래프 : 각 정점의 in : 1 / out : 1
- 막대 그래프 : 특정 정점이 in : 1 / out : 0 or in : 0 / out : 1
- 8자 그래프 : 특정 정점의 in or out이 2
[풀이]
1. 새로 생성된 정점을 찾는다.
2. 새로 생성된 정점에 연결된 각 그래프의 정점 집합을 찾는다.
3. 집합 내 정점의 in, out 간선 수를 바탕으로 그래프 유형을 파악한다.
- #3
> [2024-03-14] jisu #3

- Programmers/주사위 고르기/jisu.py
start : 2024.03.19 10:40
end : 2024.03.19 12:30([ref](https://school.programmers.co.kr/questions/66170))
승리할 확률이 가장 높은 조합이 유일한 완탐(+ 이분탐색)
1. 주사위 n개중 n//2를 뽑는 모든 조합 찾기 : make_combinations()
- A주사위, B주사위 조합 나누기
2. n//2개의 주사위를 굴리는 모든 경우의 수 찾기 : product()
3. (모든 주사위 조합 + 굴리는 모든 경우의 수)에 따른 결과 구하기 : get_roll_result()
- A주사위 결과, B주사위 결과
4. A, B 주사위 결과에 따른 승리 횟수 구하기 : get_wins_cnt()
- 이 경우 A, B 주사위 결과를 완탐하여 승리 횟수를 구하게 되면 TLE 발생
- ref를 참고하여 이분탐색으로 접근
- B 결과에 대한 A의 모든 요소의 lower bound = A의 요소가 B에서 승리하는 횟수
- n^2 -> nlogn으로 개선
+) 조합을 구할 때 itertools의 permutation과 product를 사용하면 비교적 간단하게 구현 가능 (삼성 SW 역량평가 대비 직접 구현함)
- #8
> [2024-03-19] jisu #8

- Programmers/석유 시추/jisu.py
start : 2024.03.21 15:30
end : 2024.03.21 16:10
- 그래프 탐색(BFS, DFS)을 활용한 완전탐색으로 풀이
- 각 columns마다 시추관을 꽂아서 몇 칸을 탐색할 수 있는지 탐색(BFS) -> TLE
- 하나의 덩어리 BFS 탐색 시, 해당 지점에 몇 칸 있는지를 명시(Memoization) -> TLE
- 반대로 BFS 탐색때마다 거치게 되는 col에 몇 칸이 있는지를 더해주면 됨 -> 해결
[정확성 테스트]
테스트 1 〉 | 통과 (0.05ms, 10.5MB)
-- | --
테스트 2 〉 | 통과 (0.43ms, 10.4MB)
테스트 3 〉 | 통과 (0.06ms, 10.7MB)
테스트 4 〉 | 통과 (0.23ms, 10.5MB)
테스트 5 〉 | 통과 (0.09ms, 10.5MB)
테스트 6 〉 | 통과 (0.81ms, 10.6MB)
테스트 7 〉 | 통과 (1.17ms, 10.6MB)
테스트 8 〉 | 통과 (0.48ms, 10.5MB)
테스트 9 〉 | 통과 (3.44ms, 10.5MB)
[효율성 테스트]
테스트 1 〉 | 통과 (61.01ms, 14.3MB)
-- | --
테스트 2 〉 | 통과 (171.89ms, 14.3MB)
테스트 3 〉 | 통과 (169.71ms, 14.2MB)
테스트 4 〉 | 통과 (57.55ms, 14.3MB)
테스트 5 〉 | 통과 (322.39ms, 14.2MB)
테스트 6 〉 | 통과 (62.69ms, 14.3MB)
- #9
> [2024-03-21] jisu #9

- Programmers/주사위 고르기/heewon.py
- `dice_set`: 주사위 쌍 세트 ex) 주사위 4개 경우 : [ [(0, 1), (2, 3)], [(0, 2), (1, 3)], [(0, 3), (1, 2)] ]
- `case_x`: X의 주사위 합의 경우 딕셔너리로 저장 ex) 기본 주사위: {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
- `win, draw, loss`: 각 경우의 win, draw, loss 수 ex) win : 704, draw: 16, loss: 576
- 주사위를 나누는 경우 구하기
- 나눈 주사위들로 나올 수 있는 경우 구하기
- 승률이 가장 높은 경우를 저장
- 모든 경우를 구하지만 시간 복잡도를 최대한 줄이자!
- `combinations`의 순서가 역순과 쌍을 이루기 때문에 len(dice_case)//2 번만 확인
- 주사위의 경우를 리스트가 아닌 딕셔너리를 이용하자
`defaultdict, combinations`
- 시간: 1 hour
- 힌트: `None`
- 과거 풀은 경험 有 : 2024 KAKAO WINTER INTERNSHIP 당시에는 Time out!
#8
> [2024-03-19] heewon #8

- Programmers/도넛과 막대 그래프/osmin.py
- Programmers/주사위 고르기/osmin.py
[문제 번호] #3 
[Insight]
- 새로 생성된 정점은 진입 차수가 0이고, 자식 노드가 2개 이상임.
- 새로 생성된 정점을 제외한 후,
- 도넛 그래프는 진입 차수가 1이고, 자식 노드가 1개임. 또한 사이클이 형성됨.
- 막대 그래프는 진입 차수가 0인 노드의 개수와 동일함.
- 8 그래프는 진입 차수가 2이고, 자식 노드가 2개인 노드의 개수와 동일함.
[풀이]
1. 엣지 정보로 그래프와 진입 차수를 구한다. ind = make_ind()
2. 전체 노드의 개수를 구한다.  graph, node_cnt = make_graph()
3. 새로 생성된 정점을 찾는다. gen_node = find_gen_node()
4. 사용되지 않은 노드 번호를 찾는다. unused_node = find_unused_node()
5. 새로 생성된 정점을 제거한다. remove_node()
6. 그래프 형태별로 개수를 센다. donut, stick, eight = cal_cnt()
[예외 처리]
- 막대 그래프의 개수를 셀 때, 애초에 사용되지 않은 노드 번호에 대한 예외 처리를 해주어야 한다.
- 도넛 그래프의 개수를 셀 때, 사이클 여부로 판단하면 도넛에 포함된 노드의 개수만큼 전부 도넛 그래프의 개수로 추가된다.
이를 방지하기 위해 사이클 여부를 추적할 때 방문 여부를 확인하여 이미 확인한 노드면 사이클이 아니라고 리턴한다.
> [2024-03-14] osmin #3

- Programmers/n + 1 카드게임/dori.py
- 약 1시간 20분 풀이 후 힌트 참조 -> +20분 풀이
- 짝을 이루는 것을 확인하기위해 이분탐색을 활용할 수 있을듯 함
- 라고 생각했지만 애초에 집합을 활용하는 게 존재 여부 확인 시 O(1)로 더 효율적
- 버리는 것, 가지는 것의 차이가 뭘까?
- 경우의 수를 따져보았는데 과거/현재/미래까지 다 생각해야함. 너무 복잡...
- 힌트 참조
- 매 라운드마다 실제 주어진 과정을 수행할 필요 없음
- 그냥 뽑았던 카드를 기억하고 있다가 짝이 될 때 코인을 빼면 됨
- 계속 패에 들고 있다가 내꺼에서 낼게 없으면 동전써서 대출하는 것과 같은 것
- 즉 매 라운드 코인을 가장 적게 쓸 수 있는 방법을 고민하면 됨
- 코인 0개 씀 -> 기존 카드에서 2개 냄
- 코인 1개 씀 -> 기존 카드에서 1개, 현재 라운드까지 뽑은 카드 중 아직 가져오지 않은 거 1개
- 코인 2개 씀 -> 현재 라운드까지 뽑은 카드 중 아직 가져오지 않은 거 2개
-----
```
테스트 1 〉 | 통과 (0.02ms, 10.2MB)
테스트 3 〉 | 통과 (0.02ms, 10.1MB)
테스트 4 〉 | 통과 (0.02ms, 10.3MB)
테스트 5 〉 | 통과 (0.02ms, 10.2MB)
테스트 6 〉 | 통과 (0.03ms, 10.3MB)
테스트 7 〉 | 통과 (0.02ms, 10.1MB)
테스트 8 〉 | 통과 (0.12ms, 10.2MB)
테스트 9 〉 | 통과 (0.41ms, 10MB)
테스트 10 〉 | 통과 (0.74ms, 10.3MB)
테스트 11 〉 | …
```
> [2024-03-26] dohyun #19

- Programmers/n + 1 카드게임/jisu(TLE).py
- Programmers/n + 1 카드게임/jisu.py
- 접근 1: 백트래킹을 활용한 접근(TLE)
- 라운드, 카드 순서대로 탐색하여 각 라운드 별 아래 4개의 분기로 재귀한다.
- 카드 1, 2를 모두 가져가는 경우
- 카드 1만 가져가는 경우
- 카드 2만 가져가는 경우
- 카드를 모두 안가져가는 경우
- 재귀가 최대 2^1000번 이상 일어나므로 TLE
---
- 접근 2: 로직을 활용한 풀이 ([ref1](https://school.programmers.co.kr/questions/72868), [ref2](https://jaimemin.tistory.com/2350))
- key : 1~n 까지의 수 중 n+1을 만드는데 각 수는 최대 한 번 사용된다. ([1, n], [2, n-2], ...)
- 이는 즉, 각 라운드마다 어떤 카드를 내던지 n+1을 만들기만 하면 된다는 것을 의미한다.
- 각 라운드마다 어떤 카드 쌍으로 n+1을 만들지 생각 안해도 된다는 얘기
- 따라서, 뽑은 카드를 안가져오고도 n+1을 만들 수 있으면 만들되, 만들 수 없으면 지금까지 뽑았던 수를 가져와서 만들면 된다.
- 1. 현재 카드만으로 n+1 만들기 (코인 0 소모)
- 2. 현재 카드 1 + 뽑은 카드 1 로 n+1 만들기 (코인 1 소모)
- 3. 뽑은 카드 2 로 n+1 만들기 (코인 2 소모)
- (핵심) 우선 모두 무료로 가져온 뒤, 보유한 카드를 제출 할 때 후불 감당 가능하면 다음 라운드로 진출하면 된다.
** |  정확성 테스트
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.4MB)
테스트 2 〉 | 통과 (0.01ms, 10.5MB) …
> [2024-03-26] jisu #19

- Programmers/도넛과 막대 그래프/sumin.py
**<풀이 시간>**
2시간 30분
**<제한 사항>**
- 1 ≤ edges의 길이 ≤ 1,000,000
- edges의 원소는 [a,b] 형태이며, a번 정점에서 b번 정점으로 향하는 간선이 있다는 것을 나타낸다.
- 1 ≤ a, b ≤ 1,000,000
- 문제의 조건에 맞는 그래프가 주어진다.
- 도넛 모양 그래프, 막대 모양 그래프, 8자 모양 그래프의 수의 합은 2이상이다.
**<문제 풀이>**
생성된 정점이 없다고 했을 때, 각 그래프의 정점과 간선 특징
1) 생성된 정점
- 나가는 간선: 2개 이상 (그래프의 수의 합이 2개 이상이기 때문)
- 들어오는 간선: 0개
2) 도넛 모양 그래프
(시작 정점과 마지막 정점을 제외한 정점의 특징)
- 나가는 간선: 1개
- 들어오는 간선: 1개
3) 막대 모양 그래프
- 시작 정점: 나가는 간선(1개)
- 마지막 정점: 들어오는 간선(1개)
- 그 외, 각 정점은 들어오는 간선(1개), 나가는 간선(1개)
4) 8자 모양 그래프
- 가운데 하나의 정점만 들어오는 간선이 두 개, 나가는 간 선이 두 개
- 그 외,정점은 들어오는 간선과 나가는 간선이 모두 하나씩 존재
1. 생성된 정점 찾기(들어오는 간선이 없고, 나가는 간선이 있는 정점으로 하나밖에 존재하지 않음)
2. 생성된 정점에서 나가는 간선 모두 제거
3. 막대 모양 그래프의 시작 정점과 마지막 정점을 찾는다.
**<시간 복잡도>**
O(V+E)
- #3
> [2024-03-14] sumin #3

- Programmers/아날로그 시계/heewon.py
- `real_time`: 시침, 분침, 초침들의 실제 값 ex) 12시 30초 -> 0.00833333333333286시, 0.5분, 30초
- `alarm_check`: 지금 순간에 알람 확인
- 조건에서 h, m, s 값이 정수라는 조건이 없으므로 소수도 고려! -> real time이 중요 -> 하지만 모두 정수였다.
- 문제를 잘못 이해함
- Fact: 초침이 분침과 시침이 만날 때만 알람
- 오해: 초침이 분침과 시침이 만날 때 + 분침과 시침의 만날 때 알람
- h1:m1:s1 ~ h2:m2:s2 사이의 알람 수를 직접 구하지 않고 `00:00:00 ~ h2:m2:s2 사이의 알람 수` - `00:00:00 ~ h1:m1:s1 사이의 알람 수`
- Case
- A: 최종 초침이 시침을 지날 때
- B: 최종 초침이 분침을 지날 때
- C: n 바퀴 돌면서 초침이 돌면서 시침, 분침 만날 때 
- 예외 처리 필요
- B와 C가 겹칠 때 -> alarm_cnt -= hour
- A, B, C가 겹칠 때 -> alarm_cnt -= 2
- h1:m1:s1에서 알람이 울릴 때 : `00:00:00 ~ h2:m2:s2 사이의 알람 수` - `00:00:00 ~ h1:m1:s1 사이의 알람 수` 방식이라 h1:m1:s1 알람 카운트 안 됨
-> alarm_check
`없음`
- 시간: 4 hour(문제 잘못 이해 + 틀린 답 이해)
- 힌트: [아이디어 및 틀린 코드 참고](https://school.programmers.co.kr/questions/63464)
<html>
<body>
<pre …
> [2024-03-28] heewon #24

- Programmers/아날로그 시계/dori.py
- 약 3시간 소요
- 우선 시계 한바퀴돌면 초기화가 필요하므로 각 침의 각도를 통해서 로직 구현 가능
- 초침 속도가 가장 빠르므로 초침이 앞에있다가 역전당하는 일은 없음
- 12시침 근처에서 엣지 발생 -> 나머지로 보완
- 예를 들어 초침이 358 도였다가 1도가 되는 순간 시침이 359도인 상황을 주의해야함
- 또한 이는 넘어가는 상황에서만 발생
- continuous한 움직임을 어떻게 discrete하게 쪼갤것?
- 애초에 정확하게 같은 값을 찾을 수 있나?
- 예제에서 전부 소수점 세자리에서 겹치는 것이 의미하는 것이 있나? -> 못찾겠음
- 정확하게 같은 값을 찾는 것은 불가능할 듯함
- -> 초침이 시침/분침의 이전 값에있다가 다음 텀에 그 값을 초과한다면 겹친적이 있는 것
- 초침이 시침/분침 두개랑 겹쳐도 한번만 알람이 울리는 것 주의해야할 듯함
- 각도를 계속해서 누적한다면 부동소수점 오차 때문에 위 경우가 계산이 안됨
- 시작시간 - 종료시간을 초로 계산하여 반복문마다 1초씩 빼면서 각도를 쌓아가는 로직
- 테스트케이스 1개 통과 X (하루종일 디버깅하다가 실패 ㅠㅠㅠ)
- 따라서 루프마다 현재 시간에 따라서 각도를 새로 구해야함
-----
```
테스트 1 〉 | 통과 (24.16ms, 10.4MB)
테스트 2 〉 | 통과 (35.82ms, 10.2MB)
테스트 3 〉 | 통과 (15.38ms, 10.3MB)
테스트 4 〉 | 통과 (32.71ms, 10.3MB)
테스트 5 〉 | 통과 (0.93ms, 10.2MB)
테스트 6 〉 | 통과 (8.29ms, 10.4MB)
테스트 7 〉 …
```
> [2024-03-28] dohyun #24

- Programmers/요격 시스템/heewon.py
- e 좌표를 기준으로 정렬해서 카운트
`없음`
- 시간: 1 hour 미만
- 힌트: `None`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; overflow: auto; display: block; border: none; …
> [2024-04-04] heewon #34

- Programmers/수레 움직이기/heewon.py
- `bfs`: BFS 방식으로 start 지점에서 end 지점으로 가는 모든 경우의 수 출력(최적의 경로들만 X)
- `double_bfs`: 입력된 순서에 따라 2번의 bfs 적용
- 1st method
- 동시에 고려하는 것은 힘들다고 생각
- 말 1개를 미리 이동 시키고 다른 말을 이동 시키자
- 실수: 첫 시작하는 말은 최적의 경로로 가고 나머지 말을 최적의 경로로 가려고 했음 why? 둘 중에 한 말은 꼭 최적의 경로로 갈거라고 생각 but 아니였다
- 첫 말은 DFS와 다른 말은 BFS 방식으로 코드를 작성 -> 모두 BFS로 수정
- BFS 함수의 조건 == 수레의 조건
1. 수레는 벽이나 격자 판 밖으로 움직일 수 없습니다.(0<=next_position[0] <len(maze) and 0<=next_position[1] <len(maze[0])and next_position not in wall)
2. 수레는 자신이 방문했던 칸으로 움직일 수 없습니다.(next_position not in path)
3. 자신의 도착 칸에 위치한 수레는 움직이지 않습니다. 계속 해당 칸에 고정해 놓아야 합니다. (idx = len(path) if len(opposite_path) > len(path) else -1)
4. 동시에 두 수레를 같은 칸으로 움직일 수 없습니다. (opposite_path[idx] != next_position)
5. 수레끼리 자리를 바꾸며 움직일 수 없습니다. (idx < len(opposite_path) and opposite_path[idx] == now)
- 어떤 말이 …
> [2024-04-09] heewon #35

- Programmers/두 원 사이의 정수 쌍/heewon.py
- 1사분면 + x축(x>0) 의 점의 개수를 구하고 X 4를 하자!
- x축의 점의 개수
$$r_2 - r_1 + 1$$
- x값이 0 ~ r1 까지
$$\left\lfloor\sqrt{r_2^2 - x^2}\right\rfloor - \left\lceil\sqrt{r_1^2 - x^2}\right\rceil + 1$$
- x값이 r1 ~ r2 까지
$$\left\lfloor\sqrt{r_2^2 - x^2}\right\rfloor$$
`math`
- 힌트: `None`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, …
> [2024-04-11] heewon #43

- Programmers/에어컨/jisu.py
[접근 방식 - DP (ref)](https://school.programmers.co.kr/questions/52432)
- case 분할
- 1. 에어컨을 끄고, 실내 온도 방향으로 1도 변경하는 경우
- 2. 에어컨을 끄고, 온도를 유지하는 경우 (실내온도 == 현재온도)
- 3. 에어컨을 키고, 온도를 유지하는 경우
- 4. 에어컨을 키고, 온도를 1도 변경하는 경우
- 2차원 DP 테이블
- 행 : 시간
- 열 : 온도 (온도의 범위는 -10~40도 -> 0 ~ 50으로 표현)
- DP[i][j] = i분 상태의 j를 만들어 낼 수 있는 최소 소비 전력
- DP[i-1][j-1], DP[i-1][j], DP[i-1][j+1] 세 가지 상황에서만 DP[i][j]를 만들 수 있다.
- 각 비용을 계산해 최소 비용을 DP[i][j]로 업데이트
<details>
<summary>테스트 기록</summary>
테스트 1 〉 | 통과 (0.10ms, 10.5MB)
-- | --
테스트 2 〉 | 통과 (17.37ms, 13MB)
테스트 3 〉 | 통과 (14.95ms, 13.1MB)
테스트 4 〉 | 통과 (0.05ms, 10.6MB)
테스트 5 〉 | 통과 (0.12ms, 10.6MB)
테스트 6 〉 | 통과 (0.14ms, 10.6MB)
테스트 7 〉 | 통과 (0.13ms, 10.6MB)
테스트 8 〉 | 통과 (0.17ms, 10.6MB)
테스트 9 〉 | 통과 (0.13ms, 10.7MB)
테스트 10 〉 | 통과 (4.57ms, 11MB)
테스트 11 〉 | 통과 …
> [2024-04-16] jisu #46

- Programmers/에어컨/heewon.py
- `airconditioner_off`: 에어컨 끄고 방치했을 때 실내 온도 변화량을 계산합니다.
- 1st method
- DP를 이용하여 풀자!
- 온도, 전력을 동시에 기록 -> i분에 그 X 온도 유지하는 전력의 경우
ex) {20:[20, 22, 15], 21:[19,20]} : i분에 20도를 유지하려면 20, 22, 15 / 21도로 유지하려면 19,29 전력이 필요
- 1st
- 다음에 사람이 있으면 무조건 에어컨 가동
- 없다면 가동하거나 가동 안 하거나
- ith
- i+1에 사람 없으면 에어컨 OFF, 에어컨 ON with 온도 유지 O, 에어컨 ON with 온도 유지 X
- i+1에 사람 있으면 각각의 온도가 적정 범위에 있다면 추가
- i+1에 전력을 추가시에 꼭 i번째의 최소 전력값으로 계산
- 최종
- 마지막에 시간에서 최고 온도의 최저 전력을 구한다.
- 에어컨을 OFF시에 온도의 변화
- 현재 실내 온도 > 실외 온도 -> 1도 감소
- 현재 실내 온도 = 실외 온도 -> 온도 유지
- 현재 실내 온도 < 실외 온도 -> 1도 증가
- 에어컨 ON시에 온도의 변화
- 적정 온도 < 실외 온도 -> 1도 감소(+a전력)
- 적정 온도 > 실외 온도 -> 1도 증가(+a전력)
- 상관 없음 -> 온도 유지(+b전력)
- 2nd method
- 기존의 방식에서 초기 설정만 수정
- DP 방법 같음
- 실외 온도를 항상 적정 온도보다 높게 변경 why? 에어컨은 실내 온도를 낮추거나 온도 유지만 하게 코드 수정
- if temperature< t1, t2 라면 t1, t2 < …
> [2024-04-16] heewon #46

- Programmers/연속된 부분 수열의 합/heewon.py
- `Sliding Window` 방식 적용
- 부분수열의 합 < k : right 1 증가
- 부분수열의 합 == k : 최소 길이 배열이면 저장, 길이가 1이면 바로 return
- 부분수열의 합 > k : left 1 증가
- 힌트: `None`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: …
> [2024-04-18] heewon #47

- Programmers/상담원 인원/heewon.py
- `get_waiting_time`: 특정 수의 컨설턴트가 요청 목록을 처리하는 경우의 총 대기 시간을 계산
- 처음 접근 방법
- 모두가 1명일 때의 대기 시간을 구하고 각각의 1명이 증가할 때마다 줄어드는 시간이 가장 큰 경우 제거 ex) 추가시 1유형: 2시간, 2유형: 3시간, 3유형: 1시간이 줄으면 2유형 상담사 추가
- ~but 추가시 1유형: 2시간, 2유형: 2시간, 3유형: 1시간 인 경우는 1유형, 2유형 모두 고려해야 함~
- ~그리디로 접근하면 X~
- 최종 풀이
- 컨설턴트가 가능한 모든 경우들을 확인하자!
- `x_1 + x_2 + ... + x_k = n` (x_i는 자연수)를 만족하는 모든 쌍 구하기
- 1 <= x_i <= n - k + 1
- 중복 순열로 가능한 (x_1, x_2, ..., x_n)의 경우를 구하고
- x_1 + x_2 + ... + x_k = n를 확인하여 만족하는 경우 찾기
- 상담가 수에 따른 대기 시간 구하기
- 상담이 가능하면 종료 시간을 기록한다.
- 상담이 불가능하면 빨리 끝나는 종료 시간을 구하여 대기 시간 추가하고 종료 시간 추가
- remove로 구현, heap 자료 구조 비슷한 시간이 걸림
- 중복 계산을 줄이기 위하여 DP table(=waiting_times) 사용
- row: 상담 유형
- col: 상담사 수
`defaultdict`, `product`, `List`, `heapq`
- 시간: 1 hour
- 힌트: `None`
<details> …
> [2024-04-23] heewon #53

- Programmers/상담원 인원/jisu.py
start : 2024-04-23 10:00
end : 2024-04-23 12:30
- 초기 멘토 구성 : 1 / 1 / 1
- 다음 요청에 대기가 가장 많이 필요한 유형의 멘토 증가 => 어느 시점에 대기가 많이 필요한지 예측 불가
- 그럼 모든 요청을 처리했을 때 대기 시간이 가장 많이 필요한 유형의 멘토 증가
- 최대 멘토는 20명, reqs의 길이는 300이므로 충분히 가능할 듯
- 모든 테케 예외 처리 불가
- 그리디하게 풀이하려면 증가 시켰을 때, 대기시간이 가장 많이 감소하는 유형을 증가시키는 게 맞음
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, …
> [2024-04-23] jisu #53

- Programmers/과제 진행하기/jisu.py
start : 2024-04-24 18:37
end : 2024-04-24 19:30
- 과제를 시작하기로 한 시각이 되면 시작
- 새로운 과제를 시작할 시각이 되었을 때, 기존 진행 중 과제 멈추고 새로운 과제 시작  -> heap 구현
- 끝냈을 때, 멈춘 과제가 있다면 멈춰둔 과제 이어서 진행                       -> 멈춘 과제는 queue로 관리
- 멈춰둔 과제가 여러 개일 경우, 가장 최근 멈춘 과제부터 시작                   -> 멈추게 되는 경우 appendleft로 앞으로 삽입 (중요)
정확성  테스트
테스트 1 〉 | 통과 (0.05ms, 10.6MB)
-- | --
테스트 2 〉 | 통과 (0.03ms, 10.8MB)
테스트 3 〉 | 통과 (0.06ms, 10.7MB)
테스트 4 〉 | 통과 (0.09ms, 10.8MB)
테스트 5 〉 | 통과 (0.09ms, 10.9MB)
테스트 6 〉 | 통과 (0.12ms, 10.8MB)
테스트 7 〉 | 통과 (0.13ms, 10.9MB)
테스트 8 〉 | 통과 (0.21ms, 10.7MB)
테스트 9 〉 | 통과 (0.37ms, 10.8MB)
테스트 10 〉 | 통과 (0.33ms, 10.9MB)
테스트 11 〉 | 통과 (0.36ms, 10.8MB)
테스트 12 〉 | 통과 (1.31ms, 10.9MB)
테스트 13 〉 | 통과 (1.69ms, 10.9MB)
테스트 14 〉 | 통과 (3.56ms, 11.1MB)
테스트 15 〉 | 통과 (1.90ms, 11.1MB)
테스트 16 〉 | 통과 (0.03ms, …
> [2024-04-25] jisu #54

- Programmers/과제 진행하기/heewon.py
- `parse_time`: string 타입의 시간 문자열을 int 타입의 숫자로 변경
- 문자열을 모두 계산 가능한 숫자들로 변경 (start, playtime)
- `배열은 시간순으로 정렬되어 있지 않을 수 있습니다.` 를 고려하여 정렬 필요!
- 과제를 처리하는 방식
- 과제의 이름과 시간을 같이 저장한다 -> [과제, 남은 시간]
- 최근에 과제를 수행 -> `stack`을 사용
- 새로운 과제를 받을 때마다 연기한 과제들과 비교한다.
- 연기한 과제가 없으면 새로운 과제를 연기한 과제에 넣기
- 연기한 과제가 있으면
- 새로운 과제를 시작할 시간 이전에 연기한 과제를 끝낼수 있다면 끝내기
- 새로운 과제를 시작할 시간 이전에 연기한 과제를 끝낼수 없다면 연기한 과제의 남은 시간을 수정해서 다시 저장
- plans 순서대로 처리한 후에 완료한 과제 목록에 연기한 과제 역순으로 추가
`typing`
- 힌트: `None`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; …
> [2024-04-25] heewon #54

- Programmers/아방가르드 타일링/jisu.py
start : 2024-04-30 09:40
end : 2024-04-30 11:30
ref : 점화식 최적화 부분 이전 풀이 참고
- key point
- f'(n) 구하기
- `f'(4) -> f'(7)` / `f'(5) -> f'(8)` /  `f'(6) -> f'(9)` 에서 규칙을 찾을 수 있음
- 점화식
- #61
> [2024-04-30] jisu #61

- Programmers/광물 캐기/heewon.py
- `get_fatigue`: 광물의 종류에 맞는 모든 곡괭이 피로도 반환
- 5개의 광물을 주기로 [다이아, 철, 돌] 곡괭이를 사용할 때의 피로도 구하기
- 피로도 주기는 총 곡괭이 수와 광물의 주기(math.ceil(n/5))의 최솟값
- 곡괭이가 충분한 경우 -> 모든 광물을 캘 때까지
- 곡괭이가 부족한 경우 -> 곡괭이 못 쓰는 광물은 고려 못 함
- 피로도를 최대한 줄이는 방향으로 정렬 이후에 곡괭이를 (다이아, 철, 돌) 차례대로 사용
`math`
- 힌트: `None`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, …
> [2024-05-02] heewon #62

- Programmers/연속 펄스 부분 수열의 합/heewon.py
- 펄스 2개 경우 미리 적용 후에 부분 수열 합 구하기
- 최대 부분 수열의 합은 DP 사용
`None`
- 힌트: `None`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; …
> [2024-05-07] heewon #68

- Programmers/리코쳇 로봇/heewon.py
- `find_start`: 시작 위치만 알면 되므로 굳이 모든 보드를 확인할 필요가 없다 -> 함수로 작업
- BFS로 작업
- 슬라이딩 작업을 위하여 while문 사용
- visited 확인 작업을 추가하여 복잡도 줄이기
`deque`
- 시간: 2 hour 이하
- 힌트: 코드 참고
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; …
> [2024-05-09] heewon #69

- Programmers/리코쳇 로봇/sumin.py
추후 수정하겠습니다
테스트 1 〉 | 통과 (13.46ms, 10.4MB)
-- | --
테스트 2 〉 | 통과 (9.04ms, 10.3MB)
테스트 3 〉 | 통과 (1.17ms, 10.4MB)
테스트 4 〉 | 통과 (2.18ms, 10.4MB)
테스트 5 〉 | 통과 (2.05ms, 10.2MB)
테스트 6 〉 | 통과 (0.43ms, 10.4MB)
테스트 7 〉 | 통과 (9.10ms, 10.3MB)
테스트 8 〉 | 통과 (0.99ms, 10.3MB)
테스트 9 〉 | 통과 (3.13ms, 10.4MB)
테스트 10 〉 | 통과 (5.79ms, 10.4MB)
테스트 11 〉 | 통과 (0.07ms, 10.3MB)
테스트 12 〉 | 통과 (0.05ms, 10.2MB)
테스트 13 〉 | 통과 (0.09ms, 10.4MB)
테스트 14 〉 | 통과 (0.92ms, 10.4MB)
테스트 15 〉 | 통과 (0.57ms, 10.2MB)
테스트 16 〉 | 통과 (5.01ms, 10.3MB)
테스트 17 〉 | 통과 (0.67ms, 10.3MB)
테스트 18 〉 | 통과 (1.67ms, 10.3MB)
테스트 19 〉 | 통과 (5.95ms, 10.4MB)
테스트 20 〉 | 통과 (0.27ms, 10.3MB)
테스트 21 〉 | 통과 (8.88ms, 10.3MB)
테스트 22 〉 | 통과 (2.04ms, 10.2MB)
테스트 23 〉 | 통과 (0.79ms, 10.3MB)
테스트 24 〉 | 통과 (8.93ms, 10.3MB)
테스트 25 〉 | 통과 (6.13ms, 10.4MB)
테스트 26 〉 | 통과 …
> [2024-05-09] sumin #69

- Programmers/당구 연습/heewon.py
- reflect_point: 동서남북 방향의 대칭 된 점의 리스트 구하기
- 대칭 된 점들을 구한다.
- 대칭 된 점 사이에 당구공이 존재하면 제외
`None`
- 힌트: `None`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; …
> [2024-05-16] heewon #76

- Programmers/혼자서 하는 틱택토/sumin.py
**<풀이 시간>**
40분
**<문제 회고>**
처음에 문제를 봤을 때는 '실수'에 포커스를 두고, 수 제한도 3으로 매우 작으니 '선공, 후공을 순차적으로 진행하며 모든 경우의 수를 계산해야 하나?'라고 생각했다.
하지만, 문제를 읽어보면 나와있듯이 이 문제는 "실수를 했을 가능성이 있는가" 를 묻는 문제가 아니다.
"이 게임판이 규칙을 지켜서 진행한 틱택토에서 나올 수 있는 상황인가"를 확인하는 문제이기 때문에 게임이 종료되는 상황에 대해 고민하며 접근했다.
결과적으로, 게임이 규칙을 준수하면서 진행됐는지만 확인하면 된다.
직관적으로 생각했을 때, O와 X의 개수가 중요한 부분이라는 건 쉽게 떠올릴 수 있고 '개수'를 기반으로 규칙을 지켰는지 지키지 않으면서 진행했는지도 생각해낼 수 있다. 
정확성  |  테스트 
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.4MB)
테스트 2 〉 | 통과 (0.01ms, 10.3MB)
테스트 3 〉 | 통과 (0.02ms, 10.4MB)
테스트 4 〉 | 통과 (0.03ms, 10.2MB)
테스트 5 〉 | 통과 (0.01ms, 10.3MB)
테스트 6 〉 | 통과 (0.02ms, 10.4MB)
테스트 7 〉 | 통과 (0.02ms, 10.4MB)
테스트 8 〉 | 통과 (0.02ms, 10.2MB)
테스트 9 〉 | 통과 (0.01ms, 10.2MB)
테스트 10 〉 | 통과 (0.01ms, 10.2MB)
테스트 11 〉 | 통과 (0.02ms, 10.2MB)
테스트 12 〉 | 통과 (0.02ms, 10.2MB)
테스트 13 〉 | 통과 …
> [2024-06-04] sumin #78

- Programmers/혼자서 하는 틱택토/heewon.py
- `check_line`: 입력되는 라인이 `O`, `X` 빙고인지 확인
- 각각의 `O`와 `X`의 개수 구하기
- 마지막으로 `O`를 둔 경우
- `O` 개수 = `X` 개수 + 1 
- `X`는 빙고 불가
- 마지막으로 `X`를 둔 경우
- `O` 개수 = `X` 개수
- `O`는 빙고 불가
- 위의 경우에서 다른 빙고의 유무가 중요하지 않는 이유: 9칸에 최대 O 5개, X 4개를 사용하는데, O 5개로 만들 수 있는 빙고는 최대 2개이며, 이 빙고들은 무조건 겹칩니다. 따라서 빙고를 최대로 만드는 칸에 둔다고 가정하면, 다른 빙고의 유무를 고려할 필요가 없습니다.
- 나머지 경우는 불가
`None`
- 시간: 1 hour 이상(반례 못 찾음 + 코드 Refactoring)
- 힌트: `반례 case`
<details>
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; …
> [2024-06-04] heewon #78

- Programmers/표현 가능한 이진트리/heewon.py
- `get_node_depth`: 완전 이진 트리를 만족하게 하는 트리의 높이 구하기
- `dfs`: 해당 트리가 표현 가능한지 확인
- number 값을 이진수로 변경하고 '0' 값을 앞에 얼마나 추가할지 구해줘야 함
- 완전 트리의 노드 개수는 2^n - 1을 만족한다는 성질을 이용
- 초기 구현: while 문을 이용하여 '0'을 추가해 줬지만 큰 number에 대해서는 불필요하게 많은 시간을 이용함
- 트리의 높이를 이용 -> number 값을 2로 계속 나누어 주어 높이를 구함 단, 완전 노드 트리의 개수와 같으면 추가 X
- 노드를 확인하는 방법
- 노드의 가운데 값은 항상 트리의 root 노드이다! -> 노드의 중간 값은 부모 노드이다
- 부모 노드가 0인데 자식 노드가 1 -> 표현 불가능
- 노드를 확인하는 과정에서 부모 확인하고 2개의 트리가 생기는 방식 -> DFS로 구현
- 느낀 점
- 노드 확인하는 방법은 바로 생각함
- number 앞에 0을 여러 개 추가할 수 있다는 점을 놓침 -> 반례 참고
`math`
- 시간: 1 hour 이상(반례 못 찾음 + 코드 Refactoring)
- 힌트: `반례 case`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; …
> [2024-06-06] heewon #84

- Programmers/혼자서 하는 틱택토/yerin.py
**<풀이 시간>**
약 1시간 30분
**<문제 회고>**
해당 문제가 '규칙을 지켜서 진행한 틱택토에서 나올 수 있는 상황인가'를 묻는다는 데 주목했다.
틱택토는 선공과 후공이 번갈아 가면서 진행되는 게임으로, 반복횟수가 동일하거나 선공이 한 번 더 하는 경우가 존재한다. 즉, 횟수 차이가 1이하로 보장이 된다. 그런 조건 속에서, 성립하는 경우는 두 가지로 간추릴 수 있다.
(선공 횟수: o_cnt, 후공 횟수: x_cnt)
1) 선공이 후공보다 한 번 더 게임을 진행할 경우 ( o_cnt - x_cnt == 1 ), 후공이 이긴 상황이어서는 안된다.
2) 선공과 후공이 동일한 횟수만큼 게임을 진행한 경우 ( o_cnt - x_cnt == 0 ), 마지막 차례는 후공이었으므로 선공이 이긴 상황이면 안된다.
정리한 내용을 바탕으로 코드를 작성하였으나 코드 작성에 시간을 많이 소모. 결국, 복잡해진 코드를 리팩토링하는데 한계를 느껴 다른 사람들의 코드를 참고하여 코드를 정리하였다. 시간 단축을 위해 구조적으로 코드를 구상하는 능력을 기를 필요가 있어 보인다.
정확성  |  테스트 
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.3MB)
테스트 2 〉 | 통과 (0.02ms, 10.2MB)
테스트 3 〉 | 통과 (0.01ms, 10.3MB)
테스트 4 〉 | 통과 (0.01ms, 10MB)
테스트 5 〉 | 통과 (0.01ms, 10.2MB)
테스트 6 〉 | 통과 (0.02ms, 10.2MB)
테스트 7 〉 | 통과 (0.02ms, 10.2MB)
테스트 8 〉 | 통과 (0.02ms, …
> [2024-06-04] yerin #78

- Programmers/표현 가능한 이진트리/yerin.py
<풀이시간>
약 80분
<문제 회고>
문제 접근 방식을 머리로만 생각하고 코드를 짜지 않고, 주석을 달아 정리하는 시간을 가지니 코드를 작성하는데 걸리는 시간을 단축시킬 수 있었다.
구현 방식은 다음과 같다.
1. 십진수를 이진수로 변환. 생략되었을지도 모르는 더미노드 수만큼 '0'을 앞에 붙여, 여러 개의 가능한 경우를 생성
2. 생성된 경우에 대하여 포화 이진트리 만족 여부를 체크. 
- 부모 노드가 0일 때 1인 자식 노드가 있으면 안됨
- 하위 노드 개수는 항상 홀수
3. 여러 경우에 대한 결과값을 임시 리스트에 저장. 하나의 경우라도 포화 이진트리를 만족할 시 1을 반환
본 문제에서 반례를 찾는 일이 머리가 아팠다. 첫 번째 조건에 집중한 나머지 두 번째 조건을 알아차리지 못했다. 따로 트리에 대해 찾아보지 않고 문제 내용만 보고 이해한대로 풀어내다보니 트리가 가진 특징을 코드에 녹여내지 못한 것 같아 아쉬움이 남는다.
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.3MB)
테스트 2 〉 | 통과 (0.03ms, 10.3MB)
테스트 3 〉 | 통과 (0.07ms, 10.4MB)
테스트 4 〉 | 통과 (0.27ms, 10.2MB)
테스트 5 〉 | 통과 (0.56ms, 10.2MB)
테스트 6 〉 | 통과 (0.98ms, 10.2MB)
테스트 7 〉 | 통과 (1.54ms, 10.4MB)
테스트 8 〉 | 통과 (1.07ms, 10.2MB)
테스트 9 〉 | 통과 (9.86ms, 10.3MB)
테스트 10 〉 | 통과 (92.01ms, 11MB)
테스트 …
> [2024-06-06] yerin #84

- Programmers/미로 탈출/gwangseok.py
- README.md
<풀이시간>
50분
<문제 회고>
문제를 처음 봤을 때 중복을 고려해야 하는 상황이었다.
그러면 경우의 수가 너무 많아져서 고민을 했다.
시작 -> 레버 // 레버 -> 출구로 나눠서 길을 찾으면 중복 방문을 고려하지 않아도 된다.
BFS를 통해 최단 거리를 찾았는데 시간 초과가 나왔다.
실수한 부분을 고치는 데 시간이 많이 소요 됐다.
- 빼내올 때 해당 좌표를 방문 했다고 체크 했다.
- 그러면 q에 같은 수가 들어가게 된다.
- (0, 0) -> (0, 1), (1, 0)
- (0, 1) -> (1, 0), (1, 1) , ...
- (1, 0) -> (1, 1), ..., (1, 1), ... -> (1, 1)이 중복으로 들어감.
들어갈 때 방문 여부를 체크하자.
-- | --
테스트 1 〉 | 통과 (0.10ms, 10MB)
테스트 2 〉 | 통과 (0.14ms, 10.4MB)
테스트 3 〉 | 통과 (0.18ms, 10.3MB)
테스트 4 〉 | 통과 (0.14ms, 10.3MB)
테스트 5 〉 | 통과 (0.20ms, 10.3MB)
테스트 6 〉 | 통과 (0.11ms, 10.4MB)
테스트 7 〉 | 통과 (2.34ms, 10.4MB)
테스트 8 〉 | 통과 (3.96ms, 10.4MB)
테스트 9 〉 | 통과 (0.04ms, 10.3MB)
테스트 10 〉 | 통과 (0.03ms, 10.2MB)
테스트 11 〉 | 통과 (0.83ms, 10.2MB)
테스트 12 〉 | 통과 (5.37ms, 10.2MB)
테스트 13 〉 | 통과 (6.49ms, 10.4MB) …
> [2024-06-11] gwangseok #90

- Programmers/미로 탈출/sumin.py
**<풀이 시간>**
20분
**<문제 회고>**
문제가 최단 거리를 구하는 전형적인 BFS 문제여서 빠르게 풀 수 있었다.
굉장히 친절하게, '출발 지점에서 먼저 레버가 있는 칸으로 이동하여 레버를 당긴 후 미로를 빠져나가는 문이 있는 칸으로 이동하면 됩니다.' 라는 내용이 있어 문제 이해 및 풀이가 어렵지 않은 편이었다.
테스트 | 실행시간, 메모리
-- | --
테스트 1 〉 | 통과 (0.05ms, 10.4MB)
테스트 2 〉 | 통과 (0.15ms, 10.4MB)
테스트 3 〉 | 통과 (0.21ms, 10.3MB)
테스트 4 〉 | 통과 (0.15ms, 10.2MB)
테스트 5 〉 | 통과 (0.21ms, 10.2MB)
테스트 6 〉 | 통과 (0.22ms, 10.3MB)
테스트 7 〉 | 통과 (2.82ms, 10.4MB)
테스트 8 〉 | 통과 (4.54ms, 10.4MB)
테스트 9 〉 | 통과 (0.04ms, 10.4MB)
테스트 10 〉 | 통과 (0.02ms, 10.4MB)
테스트 11 〉 | 통과 (0.97ms, 10.5MB)
테스트 12 〉 | 통과 (6.75ms, 10.7MB)
테스트 13 〉 | 통과 (8.94ms, 10.6MB)
테스트 14 〉 | 통과 (6.05ms, 10.7MB)
테스트 15 〉 | 통과 (0.80ms, 10.2MB)
테스트 16 〉 | 통과 (14.55ms, 11.7MB)
테스트 17 〉 | 통과 (21.23ms, 11.6MB)
테스트 18 〉 | 통과 (0.25ms, 10.4MB)
테스트 19 〉 | 통과 (0.29ms, 10.3MB)
테스트 20 〉 | …
> [2024-06-11] sumin #90

- Programmers/미로 탈출/heewon.py
- 출발 -> 레버 -> 도착 이므로 레버에서 각각 출발, 도착 까지의 거리의 합을 구한다.
- BFS로 구현
`deque`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; overflow: auto; display: block; border: …
> [2024-06-11] heewon #90

- Programmers/미로 탈출/yerin.py
<풀이 시간>
1시간
<문제 회고>
최단 거리를 묻는 문제라 bfs를 떠올림. 문제 조건을 확인해보니, 복잡한 케이스 분류 없이 단순히 출발 지점에서 종료 지점까지의 최단 거리만 구하면 되는 문제라고 판단. 
bfs함수에서 방문처리를 언제 하느냐에 따라 시간 초과가 날 수 있음. 방문처리를 하는 코드를 for문 안에 두고, 중복 방문이 이루어지지 않도록 할 필요가 있음.
테스트 | 실행시간, 메모리
-- | --
테스트 1 〉 | 통과 (0.05ms, 10.2MB)
테스트 2 〉 | 통과 (0.12ms, 10.4MB)
테스트 3 〉 | 통과 (0.17ms, 10.2MB)
테스트 4 〉 | 통과 (0.14ms, 10.2MB)
테스트 5 〉 | 통과 (0.20ms, 10.3MB)
테스트 6 〉 | 통과 (0.10ms, 10.3MB)
테스트 7 〉 | 통과 (3.11ms, 10.2MB)
테스트 8 〉 | 통과 (3.62ms, 10.3MB)
테스트 9 〉 | 통과 (0.07ms, 10.3MB)
테스트 10 〉 | 통과 (0.03ms, 10.1MB)
테스트 11 〉 | 통과 (0.74ms, 10.4MB)
테스트 12 〉 | 통과 (5.53ms, 10.3MB)
테스트 13 〉 | 통과 (6.50ms, 10.2MB)
테스트 14 〉 | 통과 (4.31ms, 10.2MB)
테스트 15 〉 | 통과 (0.91ms, 10.2MB)
테스트 16 〉 | 통과 (10.38ms, 10.5MB)
테스트 17 〉 | 통과 (19.55ms, 10.3MB)
테스트 18 〉 | 통과 (0.40ms, 10.4MB)
테스트 19 〉 | 통과 …
> [2024-06-11] yerin #90

- Programmers/표 병합/yerin.py
- README.md
<풀이 시간>
2시간
<문제 회고>
병합을 구현하는데 처음에 리스트로 구현을 했다가 중복 처리에 어려움을 겪었다. 특히 (r1, c1), (r2, c2)가 병합된 경우를 떠올리지 못한 탓이었다. 이후 set을 활용하여 중복이 일어나는 경우가 없도록 하였고 set에서 union함수를 발견하여 병합된 셀 목록을 갱신하는데 활용하였다.
중복 케이스를 생각해내지 못할 때가 종종 있는데 그냥 set을 활용하는데 익숙해져야겠다..
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (4.20ms, 11MB)
테스트 2 〉 | 통과 (3.06ms, 11MB)
테스트 3 〉 | 통과 (2.27ms, 11MB)
테스트 4 〉 | 통과 (1.77ms, 11.1MB)
테스트 5 〉 | 통과 (2.41ms, 10.9MB)
테스트 6 〉 | 통과 (1.91ms, 11MB)
테스트 7 〉 | 통과 (1.92ms, 11MB)
테스트 8 〉 | 통과 (2.34ms, 11MB)
테스트 9 〉 | 통과 (4.03ms, 11.1MB)
테스트 10 〉 | 통과 (4.06ms, 11MB)
테스트 11 〉 | 통과 (10.98ms, 11.1MB)
테스트 12 〉 | 통과 (8.60ms, 11MB)
테스트 13 〉 | 통과 (13.05ms, 11.3MB)
테스트 14 〉 | 통과 (16.15ms, 11.1MB)
테스트 15 〉 | 통과 (17.37ms, 11.4MB)
테스트 16 〉 | 통과 (12.01ms, 11.3MB)
테스트 17 〉 | 통과 (13.27ms, 11.2MB)
테스트 18 〉 | 통과 (22.94ms, 11.3MB)
테스트 …
> [2024-06-13] yerin #96

- Programmers/표 병합/gwangseok.py
<풀이 시간>
3시간
<문제 회고>
line 36, 41 부분에서 실수가 있었다.
cell_grpnval[key][1] 대신 cell_grpnval[key] 이렇게 했어서 무조건 key1의 값으로 업데이트가 됐었다.
다음날 보니 실수한 부분을 볼 수 있었다.
이런 실수를 많이 하는데 유의해야 겠다.
-- | --
테스트 1 〉 | 통과 (1.89ms, 11.1MB)
테스트 2 〉 | 통과 (1.84ms, 11.1MB)
테스트 3 〉 | 통과 (1.78ms, 11.2MB)
테스트 4 〉 | 통과 (1.80ms, 11.1MB)
테스트 5 〉 | 통과 (2.09ms, 11.1MB)
테스트 6 〉 | 통과 (2.68ms, 11.2MB)
테스트 7 〉 | 통과 (2.95ms, 11.1MB)
테스트 8 〉 | 통과 (2.23ms, 11.1MB)
테스트 9 〉 | 통과 (2.73ms, 11.2MB)
테스트 10 〉 | 통과 (2.33ms, 11.1MB)
테스트 11 〉 | 통과 (10.47ms, 11.1MB)
테스트 12 〉 | 통과 (7.32ms, 11.2MB)
테스트 13 〉 | 통과 (12.77ms, 11.3MB)
테스트 14 〉 | 통과 (12.41ms, 11.2MB)
테스트 15 〉 | 통과 (10.42ms, 11.4MB)
테스트 16 〉 | 통과 (9.92ms, 11.3MB)
테스트 17 〉 | 통과 (8.90ms, 11.4MB)
테스트 18 〉 | 통과 (8.05ms, 11.4MB)
테스트 19 〉 | 통과 (49.59ms, 11.3MB)
테스트 20 〉 | 통과 (4.43ms, …
> [2024-06-13] gwangseok #96

- Programmers/표 병합/sungho.py
<풀이시간>
90분
<문제 풀이 및 회고>
삼성 코딩테스트와 비슷한 문제로 명령어가 들어오고 명령어에 작동하는 프로그램을 짜면 된다.
해당 문제는 엑셀에 표 위치에 해당하는 값 바꾸기, 값 찾아바꾸기, 표 합치기, 표 나누기, 원하는 위치 값 찾기 기능을 구현하는 문제이다.
엑셀이 어떻게 작동하는지 생각하면서 문제를 풀면 쉽다.
단, 각각 두 값을 가진 셀이 합칠 때 전자의 값으로 변경하는 것을 주의하면 된다.
프로그램은 30분 내외로 금방 짰지만 런타임에러가 떠서 해결하느라 오래 걸렸다. unmerge에서 r,c를 제외한 해당 그룹에 모든 셀들의 값은 blank로 바꿔야 하는데 r, c를 제외하는 부분에서 pass를 해야 하는데 continue로 자동적으로 코드를 짰다가 테스트케이스에는 문제가 없어서 문제인 코드 부분을 찾느라 오래 걸렸다.
| 테스트 번호 | 통과 여부 | 실행 시간 | 메모리 사용량 |
| ----------- | --------- | -------- | ------------- |
| 테스트 1    | 통과      | 0.45ms   | 10.4MB        |
| 테스트 2    | 통과      | 0.06ms   | 10.4MB        |
| 테스트 3    | 통과      | 0.03ms   | 10.5MB        |
| 테스트 4    | 통과      | 0.03ms   | 10.4MB        |
| 테스트 5    | 통과      | 0.43ms   | 10.6MB        |
| 테스트 6    | 통과      | 0.06ms   | …
> [2024-06-13] sungho #96

- Programmers/호텔 대실/gwangseok.py
<풀이 시간>
30분
<문제 회고>
Greedy로 풀어서 해결하였다.
-- | --
테스트 1 〉 | 통과 (0.08ms, 10.4MB)
테스트 2 〉 | 통과 (0.57ms, 10.3MB)
테스트 3 〉 | 통과 (3.71ms, 10.5MB)
테스트 4 〉 | 통과 (2.73ms, 10.4MB)
테스트 5 〉 | 통과 (0.03ms, 10.3MB)
테스트 6 〉 | 통과 (3.19ms, 10.5MB)
테스트 7 〉 | 통과 (3.32ms, 10.5MB)
테스트 8 〉 | 통과 (2.19ms, 10.4MB)
테스트 9 〉 | 통과 (1.20ms, 10.4MB)
테스트 10 〉 | 통과 (2.21ms, 10.6MB)
테스트 11 〉 | 통과 (4.75ms, 10.6MB)
테스트 12 〉 | 통과 (3.74ms, 10.4MB)
테스트 13 〉 | 통과 (0.70ms, 10.3MB)
테스트 14 〉 | 통과 (6.06ms, 10.6MB)
테스트 15 〉 | 통과 (7.04ms, 10.6MB)
테스트 16 〉 | 통과 (2.03ms, 10.5MB)
테스트 17 〉 | 통과 (6.97ms, 10.5MB)
테스트 18 〉 | 통과 (2.78ms, 10.6MB)
테스트 19 〉 | 통과 (9.08ms, 10.7MB)
> [2024-06-18] gwangseok #97

- Programmers/호텔 대실/heewon.py
- `timetomin`: 시간 문자열 (hh:mm 형식)을 분 단위 정수형으로 변환하는 함수입니다.
- 호텔 예약 정보를 대소 비교 가능한 분의 형태로 전환한다. 퇴실 시간은 10분 추가
- 호텔 예약 정보를 시작 시간을 기준으로 정렬한다.
- 차례대로 룸에 배정을 한다.
- 룸에 들어오는 정보는 heap을 이용하여 퇴실 시간 기준으로 정렬한다.
- 새로운 손님이 들어올 때
- 대실 중이고 기존 손님의 퇴실 시간 <= 새로운 손님의 시작 시간이면
- 기존 손님은 퇴실
- 새로운 손님은 대실
- 최대 대실 수 확인
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 …
> [2024-06-18] heewon #97

- Programmers/표 병합/sumin.py
**<풀이 시간>**
1시간 20분
**<문제 회고>**
전에 풀었던 문제여서 '서로소-집합 알고리즘'이 금방 생각났고 해당 알고리즘을 사용해서 문제를 풀이했다.
구현해야 하는 부분이 많아서, 각 command에 대한 클래스를 만들어서 풀을까 생각도 했지만 answer를 전역변수로 빼서 실행했다.
하지만, 이 부분은 좀 더 개선할 수 있을 것 같아 고민을 해봐야할 것 같다.
또, 표가 50 x 50이라 알고리즘을 쓰지 않고도 단순 구현으로 잘 구현하면 풀 것 같은데 풀다가 계속 꼬여서 단순구현으로는 풀이하지 못했다.
테스트 | 실행시간, 메모리
-- | --
테스트 1 〉 | 통과 (1.03ms, 10.5MB)
테스트 2 〉 | 통과 (0.60ms, 10.6MB)
테스트 3 〉 | 통과 (0.06ms, 10.5MB)
테스트 4 〉 | 통과 (0.04ms, 10.5MB)
테스트 5 〉 | 통과 (0.39ms, 10.5MB)
테스트 6 〉 | 통과 (0.06ms, 10.6MB)
테스트 7 〉 | 통과 (1.39ms, 10.5MB)
테스트 8 〉 | 통과 (0.96ms, 10.6MB)
테스트 9 〉 | 통과 (1.92ms, 10.5MB)
테스트 10 〉 | 통과 (4.94ms, 10.7MB)
테스트 11 〉 | 통과 (10.86ms, 10.4MB)
테스트 12 〉 | 통과 (14.56ms, 10.7MB)
테스트 13 〉 | 통과 (46.28ms, 10.7MB)
테스트 14 〉 | 통과 (45.12ms, 10.8MB)
테스트 15 〉 | 통과 (28.14ms, 10.8MB)
테스트 16 〉 | 통과 …
> [2024-06-13] sumin #96

- Programmers/호텔 대실/sumin.py
**<풀이 시간>**
20분
**<문제 회고>**
백준의 [회의실 배정](https://www.acmicpc.net/problem/1931), [순회 강연](https://www.acmicpc.net/problem/2109)과 비슷한 유형의 그리디 문제라 쉽게 풀 수 있었다.
테스트 | 실행시간, 메모리
-- | --
테스트 1 〉 | 통과 (0.05ms, 10.2MB)
테스트 2 〉 | 통과 (0.30ms, 10.1MB)
테스트 3 〉 | 통과 (1.43ms, 10.5MB)
테스트 4 〉 | 통과 (0.92ms, 10.5MB)
테스트 5 〉 | 통과 (0.00ms, 10.2MB)
테스트 6 〉 | 통과 (1.26ms, 10.5MB)
테스트 7 〉 | 통과 (2.26ms, 10.2MB)
테스트 8 〉 | 통과 (0.93ms, 10.1MB)
테스트 9 〉 | 통과 (0.39ms, 10.1MB)
테스트 10 〉 | 통과 (1.76ms, 10.5MB)
테스트 11 〉 | 통과 (1.61ms, 10.6MB)
테스트 12 〉 | 통과 (1.43ms, 10.5MB)
테스트 13 〉 | 통과 (0.26ms, 10.2MB)
테스트 14 〉 | 통과 (1.24ms, 10.4MB)
테스트 15 〉 | 통과 (1.43ms, 10.4MB)
테스트 16 〉 | 통과 (0.57ms, 10.3MB)
테스트 17 〉 | 통과 (2.78ms, 10.2MB)
테스트 18 〉 | 통과 (0.94ms, 10.3MB)
테스트 19 〉 | 통과 (1.41ms, 10.5MB)
> [2024-06-18] sumin #97

- Programmers/미로 탈출 명령어/gwangseok.py
<풀이 시간> 
2시간 30분 // dfs: 1시간 30분, 구현: 1시간
<문제 회고>
주어진 우선순위에 맞게 이동이 필요해서 제일 먼저 bfs보단 dfs를 떠올렸다.
처음에 시간 초과가 나는 부분이 있고 런타임 에러가 났었다.
적절하게 pruning을 하니 시간 초과는 해결했는데 런타임 에러는 계속 났다.
그러던 중 방해물이 없고 이동 우선순위가 정해져 있기 때문에 굳이 dfs로 안하고 구현으로 해결이 될 것 같아서 구현으로 해결하였다.
나중에 힌트를 보니 recursion limit을 올려주면 런타임 에러가 해결된다고 하였다.
이를 적용하니 dfs도 시간 내로 풀렸지만, 시간이 더 오래 걸렸다. 
- 구현 
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.3MB)
테스트 2 〉 | 통과 (0.00ms, 10.2MB)
테스트 3 〉 | 통과 (0.00ms, 10.3MB)
테스트 5 〉 | 통과 (0.01ms, 10.3MB)
테스트 6 〉 | 통과 (0.01ms, 10.4MB)
테스트 7 〉 | 통과 (0.01ms, 10.4MB)
테스트 8 〉 | 통과 (0.01ms, 10.2MB)
테스트 9 〉 | 통과 (0.19ms, 10.3MB)
테스트 10 〉 | 통과 (0.15ms, 10.3MB)
테스트 11 〉 | 통과 (0.13ms, 10.4MB)
테스트 12 〉 | 통과 (0.15ms, 10.4MB)
테스트 13 〉 | 통과 (0.14ms, 10.5MB)
테스트 14 〉 | 통과 (0.15ms, 10.3MB) …
> [2024-06-20] gwangseok #110

- Programmers/미로 탈출 명령어/yerin.py
처음에 문제를 풀 때는 bfs를 사용했다. 거리값이 k일 때 도착지점에 있다면 반환하도록 하려했는데 시간 초과가 났다. 시간복잡도 계산이 아직 익숙치 않은데 연습이 많이 필요할 것 같다.
bfs를 포기하고 직접 방향별로 거리를 구하는 방식으로 변경하기로 했다. 그러나 k가 출발과 도착지점간의 거리보다 클 때, 방향별 추가 횟수를 구하는 방법을 정리하지 못했다. 결국 다른 분들이 푼 방식들을 참고해서 코드를 작성하였다.
> [2024-06-20] yerin #110

- Programmers/미로 탈출 명령어/heewon.py
- README.md
- 하, 좌, 우, 상 (d, l, r, u) 순서로 우선 순위를 가진다.
- BFS, DFS는 같은 좌표를 다시 가도 되므로 시간 복잡도가 클 것으로 판단
- 장애물이 없기 때문에 그리디로 접근
- 'impossible' 경우
- 필수 이동 수보다 k가 작은 경우
- 추가 이동이 홀수인 경우
- 다음 순서 대로 움직인다.
1. 필수 하향 이동
2. 가능한 만큼 추가 하향 이동
- x값이 n이 되거나 추가 이동할 수 있을 만큼
- 추가 하향을 한 만큼 마지막(9)에 추가 상향을 해야 함 why? u는 우선 순위 최하
3. 필수 좌향 이동
4. 가능한 만큼 추가 좌향 이동
- y값이 1이 되거나 추가 이동할 수 있을 만큼
- 추가 좌향을 한 만큼 나중(7)에 추가 우향을 해야 함
5. 추가 이동이 남으면 가능한 만큼 우향, 좌향 이동 반복
- 여기서 남은 추가 이동 횟수 소진
6. 필수 우향 이동
7. 추가 우향 이동
- 4에서 이동한 만큼 우향 이동
8. 필수 상향 이동
9. 추가 상향 이동
- 2에서 이동한 만큼 상향 이동
- 변수 실수로 test case 4번을 fail 했다. 반례 문제가 아니라 실수 때문에 시간을 날렸다. 실수를 조심하자!
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; …
> [2024-06-20] heewon #110

- Programmers/미로 탈출 명령어/sumin.py
**<풀이 시간>**
2시간 이상
**<문제 회고>**
처음에 평범한 DFS, 백트래킹 문제라고 생각하고 접근했지만 계속해서 여러 테스트 케이스에서 시간초과가 났다.
어떻게든 혼자서 풀이하려고 욕심 부리다 보니 PR 시간이 많이 늦어졌다ㅠㅠ
최적화를 어느 부분에서 할 수 있을 지 계속 고민했고, 최소 거리(맨해튼 거리)를 이용하는 부분까지는 생각했으나 (K - 맨해튼 거리)가 짝수가 돼야 하는 부분을 발견하기 어려웠다. 
다음의 [힌트](https://school.programmers.co.kr/questions/45928)를 사용해 프루닝할 수 있는 부분을 좀 더 추가해줬고 겨우 통과될 수 있었다. 찾아보니 해당 문제의 경우, 그리디, 다이나믹 프로그래밍으로도 풀이가 가능하다는데 어떻게 다음의 방법으로도 풀 수 있을지 고민해봐야 할 것 같다.
-- | --
테스트 1 〉 | 통과 (0.29ms, 10.3MB)
테스트 2 〉 | 통과 (0.21ms, 10.1MB)
테스트 3 〉 | 통과 (0.00ms, 10.2MB)
테스트 4 〉 | 통과 (0.03ms, 10.2MB)
테스트 5 〉 | 통과 (0.03ms, 10.3MB)
테스트 6 〉 | 통과 (0.03ms, 10.3MB)
테스트 7 〉 | 통과 (0.03ms, 10.3MB)
테스트 8 〉 | 통과 (0.03ms, 10.2MB)
테스트 9 〉 | 통과 (9.10ms, 15.3MB)
테스트 10 〉 | 통과 (9.33ms, 15.2MB)
테스트 11 〉 | 통과 (8.21ms, 15.2MB)
테스트 12 〉 | 통과 …
> [2024-06-20] sumin #110

- Programmers/무인도 여행/gwangseok.py
<풀이 시간>
15분
<문제 회고>
방문을 기록하면서 2중 for문과 bfs로 해결하였다.
-- | --
테스트 2 〉 | 통과 (0.05ms, 10.5MB)
테스트 3 〉 | 통과 (0.13ms, 10.5MB)
테스트 4 〉 | 통과 (0.30ms, 10.5MB)
테스트 5 〉 | 통과 (2.74ms, 10.5MB)
테스트 6 〉 | 통과 (2.38ms, 10.4MB)
테스트 7 〉 | 통과 (1.37ms, 10.4MB)
테스트 8 〉 | 통과 (3.99ms, 10.4MB)
테스트 9 〉 | 통과 (8.35ms, 10.5MB)
테스트 10 〉 | 통과 (5.45ms, 10.4MB)
테스트 11 〉 | 통과 (5.83ms, 10.4MB)
테스트 12 〉 | 통과 (9.28ms, 10.4MB)
테스트 13 〉 | 통과 (8.61ms, 10.4MB)
테스트 14 〉 | 통과 (20.18ms, 10.4MB)
테스트 15 〉 | 통과 (23.14ms, 10.6MB)
테스트 16 〉 | 통과 (17.24ms, 10.5MB)
테스트 17 〉 | 통과 (0.80ms, 10.6MB)
테스트 18 〉 | 통과 (24.52ms, 10.5MB)
테스트 19 〉 | 통과 (24.86ms, 10.5MB)
테스트 20 〉 | 통과 (1.53ms, 10.3MB)
테스트 21 〉 | 통과 (1.58ms, 10.5MB)
테스트 22 〉 | 통과 (0.12ms, 10.4MB)
테스트 23 〉 | 통과 (11.45ms, 10.6MB)
테스트 24 〉 | …
> [2024-06-25] gwangseok #114

- Programmers/무인도 여행/sungho.py
<문제 풀이 시간>
30분
<문제 풀이 및 회고>
맵 위에 섬이 있다면 해당 섬에서 연결된 지점들의 모든 weight들을 더 한 값을 구하는 문제다.
visited로 어떻게 구현할까 고민하다가 return으로 계속 주는 식으로 바꿔서 문제를 해결하였다. (global 변수로 빼는 게 더 좋아보임)
|-------------|------|-----------|---------------|
| 테스트 1    | 통과 | 0.01ms    | 10.3MB        |
| 테스트 2    | 통과 | 0.05ms    | 10.5MB        |
| 테스트 3    | 통과 | 0.11ms    | 10.5MB        |
| 테스트 4    | 통과 | 0.16ms    | 10.4MB        |
| 테스트 5    | 통과 | 2.10ms    | 10.4MB        |
| 테스트 6    | 통과 | 2.03ms    | 10.5MB        |
| 테스트 7    | 통과 | 1.13ms    | 10.6MB        |
| 테스트 8    | 통과 | 3.16ms    | 10.5MB        |
| 테스트 9    | 통과 | 8.12ms    | 10.4MB        |
| 테스트 10   | 통과 | 5.01ms    | 10.4MB        |
| 테스트 11   | 통과 | 4.67ms    | 10.5MB        |
| 테스트 12   | 통과 | 10.10ms   | 10.5MB …
> [2024-06-25]  sungho #114

- Programmers/무인도 여행/heewon.py
- `dfs`: DFS 방식으로 연결된 섬끼리의 식량의 합 반환
- DFS가 접근하기 쉬워서 코드 작성
- 방문 표시를 집합으로 설정하여 빠르게 진행
`None`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; color: white; overflow: auto; …
> [2024-06-25] heewon #114

- Programmers/무인도 여행/sumin.py
<풀이 시간>
20분
<문제 회고>
많이 풀어본 유형의 기본적인 DFS 문제!
백준과 리트코드 둘다 비슷한 문제가 있었는데 문제 이름이 생각이 안난다..
테스트 케이스 | 처음 DFS 코드
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.4MB)
테스트 2 〉 | 통과 (0.03ms, 10.4MB)
테스트 3 〉 | 통과 (0.06ms, 10.4MB)
테스트 4 〉 | 통과 (0.19ms, 10.4MB)
테스트 5 〉 | 통과 (1.11ms, 10.4MB)
테스트 6 〉 | 통과 (1.81ms, 10.2MB)
테스트 7 〉 | 통과 (1.00ms, 10.4MB)
테스트 8 〉 | 통과 (2.89ms, 10.5MB)
테스트 9 〉 | 통과 (4.53ms, 10.4MB)
테스트 10 〉 | 통과 (4.27ms, 10.5MB)
테스트 11 〉 | 통과 (3.88ms, 10.6MB)
테스트 12 〉 | 통과 (6.43ms, 10.5MB)
테스트 13 〉 | 통과 (12.82ms, 10.4MB)
테스트 14 〉 | 통과 (10.09ms, 10.6MB)
테스트 15 〉 | 통과 (9.28ms, 10.6MB)
테스트 16 〉 | 통과 (11.56ms, 10.8MB)
테스트 17 〉 | 통과 (0.36ms, 10.3MB)
테스트 18 〉 | 통과 (13.22ms, 10.7MB)
테스트 19 〉 | 통과 (12.75ms, 10.7MB)
테스트 20 〉 | 통과 (0.62ms, 10.4MB)
테스트 21 〉 | 통과 (0.90ms, 10.3MB)
테스트 22 〉 | 통과 (0.09ms, 10.5MB)
테스트 23 …
> [2024-06-25] sumin #114

- Programmers/억억단을 외우자/sungho.py
<풀이 시간>
2시간이상. 풀이 보고도 몰랐고 어거지로 맞춤
<문제 풀이 및 회고>
10번 테스트케이스에 대해 시간제한이 잘못된 거 같다. 다른 사람들도 그렇게 말하는 듯. 로직은 같은데 함수 - 함수 - 함수로 풀면 시간이 부족하고 하나의 함수로 바로 풀게 되면 시간제한에 맞게 나왔다...
가장 처음 풀 때 약수 갯수를 구하는 함수를 하나하나 구하는 식으로 했는데 start ~ end가 큰 범위일 수도 있으니 다른 방법으로 구했어야 했다. 다른 분들처럼 처음에 시간복잡도를 생각해서 설계를 잘하는 습관을 가져야겠다.
|-------------|------|-----------|----------------|
| 테스트 1    | 통과 | 0.01ms    | 10.2MB         |
| 테스트 2    | 통과 | 0.01ms    | 10.3MB         |
| 테스트 3    | 통과 | 0.07ms    | 10.2MB         |
| 테스트 4    | 통과 | 0.43ms    | 10.1MB         |
| 테스트 5    | 통과 | 1.00ms    | 10.2MB         |
| 테스트 6    | 통과 | 5.68ms    | 10.2MB         |
| 테스트 7    | 통과 | 10.50ms   | 10.3MB         |
| 테스트 8    | 통과 | 58.07ms   | 11.5MB         |
| 테스트 9    | 통과 | 1499.04ms | 36.2MB …
> [2024-06-26] sungho #123

- Programmers/억억단을 외우자/gwangseok.cpp
- Programmers/억억단을 외우자/gwangseok.py
<풀이 시간>
1시간 정도
<문제 회고>
문제 이해한 뒤, start가 여러 개 있기 때문에 DP를 사용하고 에라토스테네스의 체와 유사하게 등장 횟수를 세주었다.
운이 좋게 바로 통과 되었다.
하지만 주석을 달고 다시 실행하니 시간 초과가 났다.
복잡도를 계산해도 충분히 실행 가능한데, 마지막 case의 통과 시간이 빡센 것 같다.
그래서 같은 코드를 CPP로 제출하니 통과되었다.
- Python
--|--
테스트 3 〉 | 통과 (0.07ms, 10.2MB)
테스트 4 〉 | 통과 (0.37ms, 10.2MB)
테스트 5 〉 | 통과 (0.82ms, 10.1MB)
테스트 6 〉 | 통과 (4.73ms, 10.4MB)
테스트 7 〉 | 통과 (9.82ms, 10.3MB)
테스트 8 〉 | 통과 (56.54ms, 10.8MB)
테스트 9 〉 | 통과 (1716.56ms, 28.4MB)
테스트 10 〉 | 통과 (9900.21ms, 91.4MB)
- CPP
--|--
테스트 1 〉 | 통과 (0.01ms, 4.21MB)
테스트 2 〉 | 통과 (0.01ms, 4.06MB)
테스트 3 〉 | 통과 (0.02ms, 4.13MB)
테스트 4 〉 | 통과 (0.02ms, 3.68MB)
테스트 5 〉 | 통과 (0.06ms, 3.69MB)
테스트 6 〉 | 통과 (0.16ms, 4.13MB)
테스트 7 〉 | 통과 (0.50ms, 4.13MB)
테스트 …
> [2024-06-27] gwangseok #123

- Programmers/뒤에 있는 큰 수 찾기/gwangseok.py
<풀이 시간>
30분
<문제 회고>
문제를 보자마자 백준의 [오큰수](https://www.acmicpc.net/problem/17298)가 생각이 났다.
스택으로 푼 기억이 있어서 스택으로 해결하였다.
세그먼트 트리로도 풀릴 것 같아서 한번 시도 해봤는데 잘 안 된다.
-- | --
테스트 1 〉 | 통과 (0.01ms, 10MB)
테스트 4 〉 | 통과 (0.05ms, 10.3MB)
테스트 5 〉 | 통과 (0.32ms, 10.2MB)
테스트 6 〉 | 통과 (3.97ms, 11.2MB)
테스트 7 〉 | 통과 (5.82ms, 11.4MB)
테스트 8 〉 | 통과 (24.49ms, 17MB)
테스트 9 〉 | 통과 (15.42ms, 17.2MB)
테스트 10 〉 | 통과 (47.69ms, 19.5MB)
테스트 11 〉 | 통과 (35.85ms, 19.7MB)
테스트 12 〉 | 통과 (96.07ms, 25.3MB)
테스트 13 〉 | 통과 (67.77ms, 25.2MB)
테스트 14 〉 | 통과 (147.90ms, 43.4MB)
테스트 15 〉 | 통과 (331.32ms, 75.5MB)
테스트 16 〉 | 통과 (380.88ms, 75.4MB)
테스트 17 〉 | 통과 (299.21ms, 75.4MB)
테스트 18 〉 | 통과 (355.40ms, 75.3MB)
테스트 19 〉 | 통과 (350.37ms, 75.4MB)
테스트 20 〉 | 통과 (409.08ms, …
> [2024-07-02] gwangseok #130

- Programmers/뒤에 있는 큰 수 찾기/yerin.py
<풀이 시간>
10분
<문제 회고>
이전에 풀어봤던 문제라 빠르게 답을 떠올릴 수 있었다. 아쉬운 점은 문제 유형을 떠올리기보다는 문제 자체를 회상해 코드를 짠 점이다. 풀이법을 익힌 것이 아니라 하나의 문제에 대한 답안지를 보고 푼 기분이었다. 다른 문제를 만났을 때 이 풀이를 떠올릴 수 있을까에 대한 물음을 던지면 의문이 남는다. 다른 문제를 만났을 때도 해당 풀이를 떠올릴 수 있도록, 해당 문제를 풀어낸 경험이 일회성이 되지 않도록 문제를 분석하고 머리에 넣어놔야겠다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.1MB)
테스트 3 〉 | 통과 (0.01ms, 10.1MB)
테스트 4 〉 | 통과 (0.03ms, 10.2MB)
테스트 5 〉 | 통과 (0.31ms, 10.3MB)
테스트 6 〉 | 통과 (6.12ms, 11.1MB)
테스트 7 〉 | 통과 (3.24ms, 11.4MB)
테스트 8 〉 | 통과 (22.12ms, 17.1MB)
테스트 9 〉 | 통과 (19.94ms, 17.1MB)
테스트 10 〉 | 통과 (28.78ms, 19.5MB)
테스트 11 〉 | 통과 (38.02ms, 19.5MB)
테스트 12 〉 | 통과 (57.25ms, 25.5MB)
테스트 13 〉 | 통과 (57.28ms, 25.4MB)
테스트 14 〉 | 통과 (152.62ms, 43.3MB)
테스트 15 〉 | 통과 (291.35ms, 75.2MB)
테스트 16 〉 | 통과 (289.92ms, 75.4MB)
테스트 17 〉 | 통과 …
> [2024-07-02] yerin #130

- Programmers/뒤에 있는 큰 수 찾기/sungho.py
< 풀이 시간 >
20분
< 문제 풀이 및 회고 >
고려해야 할 것은 뒤에 수가 뭐가 있는지이다. 
앞에서부터 고려를 하면 뒤에 최악의 경우 가장 뒤까지 수를 고려해야해서 시간복잡도가 O(n^2)이고
뒤에서부터 고려를 하면 자신보다 뒤에 수 중에 큰 수만 고려하면 되므로 O(n)이 된다.
|-------------|------|-----------|---------------|
| 테스트 1    | 통과 | 0.01ms    | 10MB          |
| 테스트 2    | 통과 | 0.01ms    | 10.2MB        |
| 테스트 3    | 통과 | 0.01ms    | 10.1MB        |
| 테스트 4    | 통과 | 0.05ms    | 10.1MB        |
| 테스트 5    | 통과 | 0.45ms    | 10.2MB        |
| 테스트 6    | 통과 | 4.44ms    | 11.3MB        |
| 테스트 7    | 통과 | 4.96ms    | 11.3MB        |
| 테스트 8    | 통과 | 21.29ms   | 16.5MB        |
| 테스트 9    | 통과 | 20.89ms   | 16.6MB        |
| 테스트 10   | 통과 | 44.08ms   | 19.6MB        |
| 테스트 11   | 통과 | 42.14ms   | 19.6MB        |
| 테스트 12   | 통과 | 83.77ms   | 25.3MB        | …
> [2024-07-02] sungho #130

- Programmers/숫자 타자 대회/heewon.py
- `get_weight`: 두 숫자 버튼 간의 거리에 해당하는 가중치 값
- `square_dist`: 두 좌표 간의 제곱 거리 값
- 1st method - fail
- 아닐 것 같지만 떠오르는 방법이 없어서 그리디로 접근
- 최소 가중치를 가지는 번호로 이동
- 동일한 가중치 면 저장하고 나중에 계산
- 반례를 찾음 '7240'
- 느낀 점
- 일단 구현할 생각보다는 반례를 생각해 보고 구현하자(구현 시간 >> 반례 찾는 시간)
- 2nd method - 힌트 참고(`n이 10만이지만, 타이핑하기 전의 엄지의 위치는 0 1 ~ 9 8 까지 100개가 되지 않습니다`)
- 각각의 step마다 가능한 손가락들의 조합을 저장한다.
- 겹치는 조합들은 최솟값으로 저장
- 손가락이 동일한 숫자를 안 누르게 조심
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: …
> [2024-07-04] heewon #136

- Programmers/숫자 변환하기/sungho.py
풀이시간
20분
문제 풀이 및 회고
x에서 y로 수를 만들 때 모든 경우의 수를 들르면서 수를 만들어야 하는데 정수 부문에서는 곱하는 거 보다 나눌 때 경우의 수가 더 적을 거 같아서 y에서 3이나 2로 나눌 수 있는 경우에만 다음 경우의 수까지 고려하는 식으로 문제를 풀었습니다
| 테스트 번호 | 상태  | 시간      | 메모리  |
|-------------|-------|-----------|---------|
| 테스트 1    | 통과  | 0.01ms    | 10.3MB  |
| 테스트 2    | 통과  | 0.01ms    | 10.2MB  |
| 테스트 3    | 통과  | 0.01ms    | 10.3MB  |
| 테스트 4    | 통과  | 0.01ms    | 10.3MB  |
| 테스트 5    | 통과  | 16.80ms   | 11.8MB  |
| 테스트 6    | 통과  | 0.00ms    | 10.2MB  |
| 테스트 7    | 통과  | 9.50ms    | 10.9MB  |
| 테스트 8    | 통과  | 0.01ms    | 10.1MB  |
| 테스트 9    | 통과  | 37.12ms   | 14.7MB  |
| 테스트 10   | 통과  | 42.94ms   | 15.7MB  |
| 테스트 11   | 통과  | 12.41ms   | 11.5MB  |
| 테스트 12   | 통과  | 0.01ms    | 10.1MB  |
| 테스트 13   | 통과  | 0.01ms    | 10.2MB  |
| 테스트 14   | 통과  | 0.60ms …
> [2024-07-09] sungho # 141

- Programmers/숫자 변환하기/gwangseok.py
<풀이 시간>
10분
<문제 회고>
직전에 DP와 관련해서 문제를 풀었다.
그래서 다른 분들의 풀이를 참고해 최대한 효율적으로 DP를 하려고 했다.
하다보니 BFS랑 유사한 것 같기도 하다.
-- | --
테스트 2 〉 | 통과 (0.00ms, 10.2MB)
테스트 3 〉 | 통과 (0.01ms, 10.4MB)
테스트 4 〉 | 통과 (0.01ms, 10.4MB)
테스트 5 〉 | 통과 (110.91ms, 20.9MB)
테스트 6 〉 | 통과 (0.00ms, 10.3MB)
테스트 7 〉 | 통과 (121.48ms, 21.6MB)
테스트 8 〉 | 통과 (0.01ms, 10.4MB)
테스트 9 〉 | 통과 (548.65ms, 100MB)
테스트 10 〉 | 통과 (603.98ms, 68.6MB)
테스트 11 〉 | 통과 (140.27ms, 34.6MB)
테스트 12 〉 | 통과 (0.01ms, 10.4MB)
테스트 13 〉 | 통과 (0.00ms, 10.2MB)
테스트 14 〉 | 통과 (5.80ms, 11MB)
테스트 15 〉 | 통과 (0.18ms, 10.4MB)
테스트 16 〉 | 통과 (1.03ms, 10.3MB)
> [2024-07-09] gwangseok #141

- Programmers/숫자 변환하기/heewon.py
- 1st method - dp
- y를 만드는 최적의 방법은 이전의 값으로 구할 수 있으므로 DP로 접근
- 갱신이 안 된 dp 값은 연산할 필요 없음
- 최솟값으로 갱신
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; color: white; overflow: auto; …
> [2024-07-09] heewon #141

- Programmers/숫자 타자 대회/sumin.py
**<풀이 시간>**
2시간 이상
**<문제 회고>**
2시간 넘게 다익스트라, BFS 등을 이용해서 풀이를 시도하다가 결국 [접근 방법](https://velog.io/@pindum/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%88%AB%EC%9E%90-%ED%83%80%EC%9E%90-%EB%8C%80%ED%9A%8C-Python)을 참고했다.
왼손이 이동하는 경우와 오른손이 이동하는 경우 각각에 대해 메모이제이션을 통해 최솟값을 도출한다.
풀이를 보고 나면 그다지 어렵지 않았는데, 계속 머릿속에서 문제가 정리가 안됐음.(16 ~ 20번 테스트 케이스에 대해서 통과가 안돼서 포기했던 문제)
이후에, 다른 사람의 풀이에서 prev를 저장하는 접근 방법은 봐도 이해가 안됨;;
-- | --
테스트 1 〉 | 통과 (0.13ms, 10.5MB)
테스트 2 〉 | 통과 (0.07ms, 10.4MB)
테스트 3 〉 | 통과 (0.07ms, 10.3MB)
테스트 4 〉 | 통과 (0.09ms, 10.5MB)
테스트 5 〉 | 통과 (0.12ms, 10.4MB)
테스트 6 〉 | 통과 (0.10ms, 10.4MB)
테스트 7 〉 | 통과 (0.18ms, 10.5MB)
테스트 8 〉 | 통과 (0.18ms, 10.3MB)
테스트 9 〉 | 통과 (0.17ms, 10.4MB)
테스트 10 〉 | 통과 (0.15ms, 10.3MB)
테스트 11 〉 | 통과 (0.62ms, 10.6MB)
테스트 12 〉 | 통과 (0.65ms, …
> [2024-07-04] sumin #136 

- Programmers/숫자 변환하기/sumin.py
**<풀이 시간>**
15분
**<문제 회고>**
각 숫자를 노드라고 생각한다면 시작점에서 도착점까지 가는 최단 거리를 구하는 문제로 BFS로 풀이가 가능하다.
실제로 각 숫자를 일직선에 있다고 생각하면 백준에 거의 유사한 문제인 [숨바꼭질](https://www.acmicpc.net/problem/1697)이 있다.
다이나믹 프로그래밍으로도 풀이가 가능하지만, 메모리나 실행시간 측면에서 BFS 풀이가 더 빠르다.
-- | --
테스트 4 〉 | 통과 (0.01ms, 10.1MB)
테스트 5 〉 | 통과 (52.64ms, 19.9MB)
테스트 6 〉 | 통과 (0.00ms, 10.1MB)
테스트 7 〉 | 통과 (62.62ms, 20MB)
테스트 8 〉 | 통과 (0.01ms, 10.2MB)
테스트 9 〉 | 통과 (306.74ms, 53.4MB)
테스트 10 〉 | 통과 (293.45ms, 53.3MB)
테스트 11 〉 | 통과 (102.67ms, 31.6MB)
테스트 12 〉 | 통과 (0.01ms, 10.2MB)
테스트 13 〉 | 통과 (0.01ms, 10.3MB)
테스트 14 〉 | 통과 (3.14ms, 10.4MB)
테스트 15 〉 | 통과 (0.14ms, 10.1MB)
테스트 16 〉 | 통과 (0.91ms, 10.2MB)
> [2024-07-09] sumin #141 

- Programmers/등대/heewon.py
- `dfs`: DFS 방식으로 자기 자신의 on, off 한 상태의 켜지는 등대 정보
- 1st method - 그리디1 fail
- 가장 연결 많이 된 노드 순으로 킨다.
- 구현 -> test fail -> 반례 찾음
- 2nd method - 그리디2 fail
- 모든 노드를 확인해야 한다
- 리프 노드와 연결된 노드를 먼저 킨다
- 제거하고 동일한 작업을 계속 한다.
- 커스텀 test 케이스는 성공하지만 fail
- 모든 간선이 다 연결 되야 한다는 사실 알게 됨
- 3rd method - DFS 힌트 참고
- [힌트](https://www.ai-bio.info/programmers/133500)를 참고
- stack으로 구현 시도 -> fail
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, …
> [2024-07-11] heewon #143

- Programmers/숫자 변환하기/yerin.py
예시를 제대로 안보고 그리디 문제로 오해했었다. 다시 예제를 확인하고 문제를 제대로 파악하고자 했다.
최소 연산 횟수를 반환해야 하기 때문에 bfs 알고리즘을 적용했다. 시간 초과가 있었지만 지금까지 풀어온 bfs 문제와 처리 방식이 동일했다.
9, 10번 시간 초과가 있었었는데 조건절을 어떻게 작성하는가에 따라 작동시간에 차이가 있었다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.00ms, 10.3MB)
테스트 5 〉 | 통과 (87.71ms, 16.6MB)
테스트 6 〉 | 통과 (0.00ms, 10.2MB)
테스트 7 〉 | 통과 (76.56ms, 16.6MB)
테스트 8 〉 | 통과 (0.01ms, 10.4MB)
테스트 9 〉 | 통과 (401.26ms, 61.2MB)
테스트 10 〉 | 통과 (398.42ms, 61.1MB)
테스트 11 〉 | 통과 (164.86ms, 35.5MB)
테스트 12 〉 | 통과 (0.01ms, 10.2MB)
테스트 13 〉 | 통과 (0.01ms, 10.2MB)
테스트 14 〉 | 통과 (3.21ms, 10.5MB)
테스트 15 〉 | 통과 (0.23ms, 10.2MB)
테스트 16 〉 | 통과 (1.16ms, 10.3MB)
> [2024-07-09] yerin #141

- Programmers/등대/gwangseok.py
<풀이 시간>
3시간 이상
- 힌트 참고: leaf node를 키면 이득이 없다. 
<문제회고>
1. 제일 처음 greedy하게 이웃 node와 연결된 것이 많은 node를 키려고 했다.
이때, 예 #2를 처리하려면 여러 가지 조건을 확인해야 했다. 
보다 간편한 방법이 있을 것이라고 생각했다.
2. DP를 사용해서 처리를 해야겠다고 생각했다. 
하지만 해결법이 떠오르지 않았다.
힌트를 참고했다. 
3. Leaf node를 키면 아무런 이득이 없다는 것을 알게 되었다.
Leaf node의 index를 1로 두고 부모는 index 2로 둔다. 
공통 부모는 index가 더 작은 값을 저장했다.
그래서 짝수번째 해당하는 index node를 켰다.
하지만 예외 경우가 있었다.
4. 계속 생각하다가 공통 부모는 각 경우마다 짝수인지 확인하면 해결이 됐다.
이를 구현하려면, 부모, 자식 node를 저장하는 정보를 따로 저장하거나 leaf node의 이웃 node를 키고 두 node를 삭제시키면 된다.
부모, 자식 node를 저장하려면 복잡해서 삭제 시키는 방향으로 진행하였다.
-- | --
테스트 1 〉 | 통과 (204.34ms, 59.6MB)
테스트 2 〉 | 통과 (224.67ms, 59.4MB)
테스트 3 〉 | 통과 (242.52ms, 59.2MB)
테스트 4 〉 | 통과 (207.40ms, 59.3MB)
테스트 5 〉 | 통과 (231.61ms, 57.5MB)
테스트 6 〉 | 통과 (215.08ms, 58.4MB)
테스트 7 〉 | 통과 (204.61ms, 58.7MB) …
> [2024-07-11] gwangseok #143

- Programmers/시소 짝꿍/gwangseok.py
<풀이 시간>
20분
<문제 회고>
weight가 중복될 수 있으니 각 weight마다 몇 개가 있는지 구한다.
각 weight 개수가 n일 때 같은 weight끼리 $_nC_2$ 개의 짝꿍이 된다.
이후, $\times$ 2, 3, 4의 경우의 수도 생각해서 각 경우의 수에 맞게 답을 구하였다.
하드 코딩 없이 하는 방법이 생각이 안 났다.
-- | --
테스트 3 〉 | 통과 (0.02ms, 10.2MB)
테스트 4 〉 | 통과 (2.36ms, 10.7MB)
테스트 5 〉 | 통과 (3.19ms, 11MB)
테스트 6 〉 | 통과 (4.34ms, 11.5MB)
테스트 7 〉 | 통과 (4.96ms, 11.5MB)
테스트 8 〉 | 통과 (6.20ms, 12.2MB)
테스트 9 〉 | 통과 (8.17ms, 12.9MB)
테스트 10 〉 | 통과 (10.44ms, 13.6MB)
테스트 11 〉 | 통과 (10.16ms, 13.7MB)
테스트 12 〉 | 통과 (9.06ms, 13.9MB)
테스트 13 〉 | 통과 (8.99ms, 13.9MB)
테스트 14 〉 | 통과 (9.98ms, 14.2MB)
테스트 15 〉 | 통과 (12.11ms, 13.9MB)
테스트 16 〉 | 통과 (0.01ms, 10.2MB)
테스트 17 〉 | 통과 (0.01ms, 10.2MB)
> [2024-07-16] gwangseok #154 

- Programmers/시소 짝꿍/heewon.py
- 하나의 weight가 여러 개 있을 수 있으므로, 각각의 weight 별로 개수를 구한 후 쌍을 구성합니다. 이때, Counter를 이용하여 각 weight의 개수를 쉽게 파악할 수 있습니다.
- ratio를 이용한다.
- 하나의 weight에 대하여 1/2, 2/3, 3/4, 1, 4/3, 3/2, 2 총 6개의 비율이 가능하지만 쌍이라는 점을 고려하면 3개로 나눌 수 있고 나머지 쌍이 나머지 3개의 경우를 찾게 할 수 있습니다.
- 동일한 weight가 쌍인 경우(=ratio가 1인 경우)는 조합을 이용하여 nC2: n개 중에 2개를 순서에 상관없이 뽑는 경우의 수를 계산합니다.
- 쌍이 다른 weight인 경우는 w1의 경우의 수와 w2(w1의 쌍)의 경우의 수를 곱하여 더해줍니다.
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; …
> [2024-07-16] heewon #154

- Programmers/시소 짝꿍/yerin.py
예제에서 동일한 무게가 여럿있는 경우를 보여주었기 때문에 이를 어떻게 처리할 지를 고민했다. 그런데 같은 무게를 가진 사람이 3명 이상일 때를 간과해서 테스트케이스에서 틀리게 되었다. 이렇듯 문제를 풀다보면 코드의 반례를 찾느라 시간이 소요되는 경우가 잦은데, 반례 찾는 연습을 많이 해봐야 할 것 같다.
다른 사람들의 코드를 보니 수학적으로 풀이한 경우가 있었다. 확실히 반복문을 자주 도는 내 코드와 비교했을 때 반절이상 빠른 걸 확인할 수 있었다. 문제를 풀 땐 안 떠오르다가 다른 사람의 풀이를 보며 뒤늦게 깨닫곤 한다. 문제를 보고 더 효율적인 코드를 위해 고민하는 시간을 가지면 좋을 듯하다.
테스트 | 결과
-- | --
테스트 3 〉 | 통과 (0.02ms, 10.3MB)
테스트 4 〉 | 통과 (2.95ms, 10.8MB)
테스트 5 〉 | 통과 (4.32ms, 11MB)
테스트 6 〉 | 통과 (6.11ms, 11.3MB)
테스트 7 〉 | 통과 (6.48ms, 11.7MB)
테스트 8 〉 | 통과 (11.82ms, 12.2MB)
테스트 9 〉 | 통과 (10.90ms, 12.9MB)
테스트 10 〉 | 통과 (14.62ms, 13.5MB)
테스트 11 〉 | 통과 (19.21ms, 13.6MB)
테스트 12 〉 | 통과 (27.89ms, 14.2MB)
테스트 13 〉 | 통과 (14.18ms, 13.8MB)
테스트 14 〉 | 통과 (13.09ms, 13.8MB)
테스트 15 〉 | 통과 …
> [2024-07-16] yerin #154

- Programmers/부대복귀/sungho.py
풀이 시간
30분
문제 풀이 및 회고
| 테스트 | 결과      | 시간    | 메모리   |
|--------|-----------|---------|----------|
| 테스트 1 | 통과      | 0.02ms  | 10.4MB   |
| 테스트 2 | 통과      | 0.02ms  | 10.4MB   |
| 테스트 3 | 통과      | 0.01ms  | 10.2MB   |
| 테스트 4 | 통과      | 0.01ms  | 10.3MB   |
| 테스트 5 | 통과      | 0.04ms  | 10.4MB   |
| 테스트 6 | 통과      | 18.50ms | 16.7MB   |
| 테스트 7 | 통과      | 19.83ms | 17.4MB   |
| 테스트 8 | 통과      | 27.55ms | 22.3MB   |
| 테스트 9 | 통과      | 7.96ms  | 14MB     |
| 테스트 10 | 통과     | 8.98ms  | 14.6MB   |
| 테스트 11 | 통과     | 712.10ms| 120MB    |
| 테스트 12 | 통과     | 691.80ms| 120MB    |
| 테스트 13 | 통과     | 615.49ms| 120MB    |
| 테스트 14 | 통과     | 632.84ms| 120MB    |
| 테스트 15 | 통과     | 631.28ms| 120MB    |
| 테스트 16 | 통과     | 191.27ms| 52.8MB   |
> [2024-07-18] sungho #160

- Programmers/부대복귀/gwangseok.py
<풀이 시간>
1시간
<문제 회고>
처음에 BFS로 모든 node들 끼리의 최소 distance를 구하였다.
시간 초과가 나서 고민을 하였다.
destination이 1개이기 때문에 모든 node들 끼리 구하지 않고, 
destination을 기준으로 BFS를 돌면서 거리를 구하였다.
--|--
테스트 3 〉 | 통과 (0.02ms, 10.3MB)
테스트 4 〉 | 통과 (0.01ms, 10.4MB)
테스트 5 〉 | 통과 (0.01ms, 10.2MB)
테스트 6 〉 | 통과 (27.66ms, 21.2MB)
테스트 7 〉 | 통과 (30.03ms, 22.3MB)
테스트 8 〉 | 통과 (44.23ms, 28MB)
테스트 9 〉 | 통과 (14.72ms, 16.9MB)
테스트 10 〉 | 통과 (15.83ms, 16.3MB)
테스트 11 〉 | 통과 (746.51ms, 174MB)
테스트 12 〉 | 통과 (808.11ms, 174MB)
테스트 13 〉 | 통과 (829.43ms, 174MB)
테스트 14 〉 | 통과 (733.76ms, 174MB)
테스트 15 〉 | 통과 (756.86ms, 174MB)
테스트 16 〉 | 통과 (188.14ms, 56.3MB)
> [2024-07-18] gwangseok #160

- Programmers/부대복귀/heewon.py
- 매번 sources의 시작점에서 거리를 구하지 않고, 도착점에서 모든 지점까지의 거리를 BFS로 구합니다.
- BFS로 구현하며, Node와 distance를 큐에 삽입합니다.
`defaultdict`, `deque`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; …
> [2024-07-18] heewon #160

- Programmers/택배 배달과 수거하기/gwangseok.py
<풀이 시간>
30분
<문제 회고>
문제를 보고 greedy로 끝에서 부터 cap만큼 delivery하고 pickup해서 돌아오면 되겠다고 생각했다.
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.2MB)
테스트 2 〉 | 통과 (0.01ms, 10.4MB)
테스트 3 〉 | 통과 (0.03ms, 10.1MB)
테스트 4 〉 | 통과 (0.05ms, 10.1MB)
테스트 5 〉 | 통과 (0.09ms, 10.2MB)
테스트 6 〉 | 통과 (0.09ms, 10.3MB)
테스트 7 〉 | 통과 (1.22ms, 10.1MB)
테스트 8 〉 | 통과 (2.69ms, 10.2MB)
테스트 9 〉 | 통과 (11.89ms, 10.3MB)
테스트 10 〉 | 통과 (9.09ms, 10.4MB)
테스트 11 〉 | 통과 (6.11ms, 10.3MB)
테스트 12 〉 | 통과 (3.88ms, 10.4MB)
테스트 13 〉 | 통과 (3.28ms, 10.3MB)
테스트 14 〉 | 통과 (3.31ms, 10.3MB)
테스트 15 〉 | 통과 (129.27ms, 11.5MB)
테스트 16 〉 | 통과 (3019.93ms, 11.6MB)
테스트 17 〉 | 통과 (302.67ms, 11.6MB)
테스트 18 〉 | 통과 (130.49ms, 11.6MB)
테스트 19 〉 | 통과 (99.18ms, 11.6MB)
테스트 20 〉 | 통과 (136.66ms, 11.8MB)
> [2024-07-23] gwangseok #166

- Programmers/시소 짝꿍/sumin.py
**<풀이 시간>**
45분
**<문제 회고>**
테스트 케이스가 적어 [100, 100, 100, 100] -> 6과 같은 테스트 케이스들을 생각하며 문제를 접근했다.
가능한 거리 조합이 7개밖에 되지 않아, 딕셔너리를 활용해서 문제를 풀이했다.
-- | --
테스트 2 〉 | 통과 (0.02ms, 10.2MB)
테스트 3 〉 | 통과 (0.02ms, 10.2MB)
테스트 4 〉 | 통과 (10.59ms, 10.6MB)
테스트 5 〉 | 통과 (20.51ms, 10.7MB)
테스트 6 〉 | 통과 (33.06ms, 11.2MB)
테스트 7 〉 | 통과 (48.05ms, 11.3MB)
테스트 8 〉 | 통과 (53.16ms, 11.9MB)
테스트 9 〉 | 통과 (103.07ms, 12.7MB)
테스트 10 〉 | 통과 (103.48ms, 13.5MB)
테스트 11 〉 | 통과 (104.73ms, 13.4MB)
테스트 12 〉 | 통과 (68.04ms, 14MB)
테스트 13 〉 | 통과 (84.89ms, 14MB)
테스트 14 〉 | 통과 (80.05ms, 14MB)
테스트 15 〉 | 통과 (79.92ms, 14MB)
테스트 16 〉 | 통과 (0.01ms, 10.2MB)
테스트 17 〉 | 통과 (0.01ms, 9.98MB)
> [2024-07-16] sumin #154

- Programmers/택배 배달과 수거하기/sungho.py
< 풀이시간 >
30분
< 문제 풀이 및 회고 > 
가장 뒤에부터 이동/이동시키되 한번 이동할 때 cap최대만큼 옮겨서 최대한 적게 움직이도록 코드를 구성하였음
| 테스트 번호 | 통과 여부 | 시간 (ms) | 메모리 (MB) |
|-------------|------------|-----------|-------------|
| 테스트 1    | 통과       | 0.02      | 10.3        |
| 테스트 2    | 통과       | 0.00      | 10.3        |
| 테스트 3    | 통과       | 0.03      | 10.2        |
| 테스트 4    | 통과       | 0.02      | 10.3        |
| 테스트 5    | 통과       | 0.05      | 10.3        |
| 테스트 6    | 통과       | 0.03      | 10.1        |
| 테스트 7    | 통과       | 0.76      | 10.4        |
| 테스트 8    | 통과       | 2.08      | 10.4        |
| 테스트 9    | 통과       | 9.12      | 10.3        |
| 테스트 10   | 통과       | 7.24      | 10.4        |
| 테스트 11   | 통과       | 3.33      | 10.3        |
| 테스트 12   | 통과       | 2.86      | 10.1        |
| 테스트 13   | …
> [2024-07-23] sungho #166

- Programmers/택배 배달과 수거하기/yerin.py
저번에 레벨3 문제보다 구현이 복잡하게 느껴졌다. 문제를 보자마자 그리디가 떠올랐다. 뒤에서부터 배달과 픽업을 처리하는 식의 풀이를 생각했다. 한 집의 배달 또는 픽업량이 cap보다 많은 경우, 여러 번 방문하는 처리하는 게 고민이었으나 반복문으로 더 옮겨야 할 박스가 없을 때까지 해당 집에 방문하도록 하였다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.3MB)
테스트 2 〉 | 통과 (0.00ms, 10.1MB)
테스트 4 〉 | 통과 (0.01ms, 10.3MB)
테스트 5 〉 | 통과 (0.01ms, 10.1MB)
테스트 6 〉 | 통과 (0.01ms, 10.2MB)
테스트 7 〉 | 통과 (0.19ms, 10.2MB)
테스트 8 〉 | 통과 (0.42ms, 10.2MB)
테스트 9 〉 | 통과 (1.81ms, 10.3MB)
테스트 10 〉 | 통과 (1.61ms, 10.2MB)
테스트 11 〉 | 통과 (0.76ms, 10.2MB)
테스트 12 〉 | 통과 (0.93ms, 10.2MB)
테스트 13 〉 | 통과 (0.60ms, 10.2MB)
테스트 14 〉 | 통과 (0.64ms, 10.3MB)
테스트 15 〉 | 통과 (14.73ms, 11.6MB)
테스트 16 〉 | 통과 (376.53ms, 11.6MB)
테스트 17 〉 | 통과 (43.94ms, 11.5MB)
테스트 18 〉 | 통과 (21.59ms, 11.7MB)
테스트 19 〉 | 통과 (22.18ms, 11.6MB)
테스트 20 〉 | 통과 …
> [2024-07-27] yerin #166

- Programmers/이모티콘 할인행사/heewon.py
- input의 크기가 작아서 완전 탐색을 해도 된다.
- 가능한 모든 경우에 대해서 최적의 해를 구한다.
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; color: white; overflow: auto; display: block; border: none; …
> [2024-07-30] heewon #175

- Programmers/이모티콘 할인행사/sumin.py
**<풀이 시간>**
1시간
**<문제 회고>**
어렵진 않은데 은근히 조건이 많은 문제였다. 수 제한이 굉장히 작기 때문에 특별한 알고리즘이 필요없이 모든 경우의수에 대해 탐색해서 문제를 풀이했다. 모든 경우의 수를 구하기 위한 중복순열 구현이 귀찮아서 시간복잡도가 예상 가능한 product를 사용했다. 카카오가 이 정도로만 나와준다면 얼마나 좋을까 싶다.
-- | --
테스트 1 〉 | 통과 (0.03ms, 10.3MB)
테스트 2 〉 | 통과 (0.08ms, 10.2MB)
테스트 3 〉 | 통과 (0.36ms, 10.2MB)
테스트 4 〉 | 통과 (1.92ms, 10.4MB)
테스트 5 〉 | 통과 (3.21ms, 10MB)
테스트 6 〉 | 통과 (1.54ms, 10.3MB)
테스트 7 〉 | 통과 (15.16ms, 10.2MB)
테스트 8 〉 | 통과 (7.48ms, 9.99MB)
테스트 9 〉 | 통과 (73.02ms, 10.1MB)
테스트 10 〉 | 통과 (32.52ms, 10.1MB)
테스트 11 〉 | 통과 (379.58ms, 10.2MB)
테스트 12 〉 | 통과 (165.57ms, 10.3MB)
테스트 13 〉 | 통과 (1641.48ms, 10.2MB)
테스트 14 〉 | 통과 (1557.11ms, 10.2MB)
테스트 15 〉 | 통과 (79.40ms, 10.4MB)
테스트 16 〉 | 통과 (127.55ms, 10.1MB)
테스트 17 〉 | 통과 (0.68ms, 10.2MB)
테스트 18 〉 | 통과 (22.40ms, 10.1MB)
테스트 19 …
> [2024-07-30] sumin #175

- Programmers/이모티콘 할인행사/yerin.py
제한사항을 보니 입력값의 최대 크기들이 모두 크지 않았다. 완전탐색으로도 풀 수 있을 것이라 판단했다. 가능한 모든 할인율을 사용자별로 확인을 하는 식으로 구상했다. 저번엔 itertools를 썼기에 이번에는 안써보고 풀어봤다.
테스트 |결과
-- | --
테스트 1 〉 | 통과 (0.05ms, 10.4MB)
테스트 2 〉 | 통과 (0.12ms, 10.2MB)
테스트 3 〉 | 통과 (0.51ms, 10.4MB)
테스트 4 〉 | 통과 (2.60ms, 10.4MB)
테스트 5 〉 | 통과 (4.96ms, 10.2MB)
테스트 6 〉 | 통과 (2.35ms, 10.3MB)
테스트 7 〉 | 통과 (22.06ms, 10.3MB)
테스트 8 〉 | 통과 (11.39ms, 10.3MB)
테스트 9 〉 | 통과 (106.70ms, 10.3MB)
테스트 10 〉 | 통과 (48.03ms, 10.5MB)
테스트 11 〉 | 통과 (487.58ms, 10.6MB)
테스트 12 〉 | 통과 (244.23ms, 12.2MB)
테스트 13 〉 | 통과 (2208.03ms, 12.3MB)
테스트 14 〉 | 통과 (2022.40ms, 12.2MB)
테스트 15 〉 | 통과 (104.96ms, 10.3MB)
테스트 16 〉 | 통과 (100.74ms, 10.4MB)
테스트 17 〉 | 통과 (0.49ms, 10.2MB)
테스트 18 〉 | 통과 (29.80ms, 10.4MB)
테스트 19 〉 | 통과 (0.07ms, 10.3MB)
테스트 20 〉 | 통과 (0.07ms, 10.2MB)
> [2024-07-30] yerin #175

- Programmers/고고학 최고의 발견/sumin.py
**<풀이 시간>**
2시간 이상
**<문제 회고>**
저번에 풀었던 2차원 동전 뒤집기와 굉장히 유사한 문제라고 생각했다.
완전 탐색을 하게 되면 당연히 최악의 경우 64개의 시계에 대해 4가지 방향 조합을 구해야 하기 때문에 O(4 ** 64)로 시간초과가 날 수 밖에 없다.
첫 번째 행에 대한 조합만 구해놓고, 그 아래 행부터는 회전이 바로 위 행의 시계 상태에 의존하기 때문에 첫 번째 행의 조합 최악의 경우, O(4 ** 8)와 이후 아래의 행들에 대한 처리 O(n**2)을 수행하면 된다.
-- | --
테스트 1 〉 | 통과 (0.16ms, 10.4MB)
테스트 2 〉 | 통과 (0.15ms, 10.2MB)
테스트 3 〉 | 통과 (7.31ms, 10.2MB)
테스트 4 〉 | 통과 (1515.89ms, 10.2MB)
테스트 5 〉 | 통과 (1403.33ms, 10.1MB)
테스트 6 〉 | 통과 (7428.01ms, 10.1MB)
테스트 7 〉 | 통과 (7534.22ms, 10.3MB)
테스트 8 〉 | 통과 (7397.28ms, 10.1MB)
테스트 9 〉 | 통과 (7271.22ms, 10.3MB)
테스트 10 〉 | 통과 (8201.47ms, 10.3MB)
> [2024-08-01] sumin #183

- Programmers/택배 배달과 수거하기/heewon.py
- 가장 멀리 있는 집부터 차례대로 배달과 수거를 진행합니다.
- 거리를 상자의 개수만큼 리스트에 저장하여 처리합니다.
- index가 0일 때 0을 추가하는 이유는 추후에 max계산 때문에
- ex) [0, 3, 0, 4, 0] -> [0, 2, 2, 2, 4, 4, 4, 4]
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; …
> [2024-07-27] heewon #166

- Programmers/이모티콘 할인행사/sungho.py
< 풀이시간 >
30분
< 문제 회고 및 풀이 > 
모든 경우의 수에서 가장 큰 결과 값 얻기
백트래킹으로 해결.
< 테스트 결과 >
| 테스트 번호 | 결과   | 실행 시간 (ms) | 메모리 사용량 (MB) |
|-------------|--------|----------------|--------------------|
| 테스트 1    | 통과   | 0.09           | 10.3               |
| 테스트 2    | 통과   | 0.15           | 10.4               |
| 테스트 3    | 통과   | 0.73           | 10.3               |
| 테스트 4    | 통과   | 2.51           | 10.3               |
| 테스트 5    | 통과   | 4.86           | 10.3               |
| 테스트 6    | 통과   | 3.39           | 10.4               |
| 테스트 7    | 통과   | 23.09          | 10.4               |
| 테스트 8    | 통과   | 16.07          | 10.4               |
| 테스트 9    | 통과   | 110.98         | 10.4               |
| 테스트 10   | 통과   | 70.90          | 10.5               |
| 테스트 11   | 통과   | 502.34 …
> [2024-07-30] sungho #175

- Programmers/고고학 최고의 발견/yerin.py
처음엔 완전탐색, 두 번짼 그리디를 생각했다가 시간초과가 해결이 되지 않아 힌트를 찾아보았다. 첫 번째 행의 모든 경우를 설정하는, 간략화된 탐색방법이었다. 효율적인 탐색 방법을 고안해내는 걸 연습할 필요가 있어보였다.
테스트|결과
-- | --
테스트 1 〉 | 통과 (0.20ms, 10.3MB)
테스트 2 〉 | 통과 (0.12ms, 10.2MB)
테스트 3 〉 | 통과 (5.69ms, 10.4MB)
테스트 4 〉 | 통과 (948.81ms, 10.3MB)
테스트 5 〉 | 통과 (960.56ms, 10.2MB)
테스트 6 〉 | 통과 (5386.66ms, 10.2MB)
테스트 7 〉 | 통과 (5121.04ms, 10.3MB)
테스트 8 〉 | 통과 (5342.01ms, 10.4MB)
테스트 9 〉 | 통과 (5364.31ms, 10.3MB)
테스트 10 〉 | 통과 (5131.92ms, 10.3MB)
> [2024-08-01] yerin #183

- Programmers/고고학 최고의 발견/gwangseok.py
<풀이 시간>
2시간
<문제 회고>
문제를 처음 보고 완전 탐색, greedy 등을 생각했지만 잘 되지 않았다.
이전 문제와 비슷하게 어떤 특징을 찾아야 하나 30분 고민 했는데 찾지 못했다.
힌트를 보고 첫 번째 행 돌리는 방법이 고정되면 나머지는 결정 된다는 것을 파악했다.
고민한 시간 부족했던 것 같다...
--|--
테스트 1 〉 | 통과 (0.06ms, 10.4MB)
테스트 2 〉 | 통과 (0.10ms, 10.2MB)
테스트 3 〉 | 통과 (4.01ms, 10.2MB)
테스트 4 〉 | 통과 (1248.54ms, 12.5MB)
테스트 5 〉 | 통과 (1216.57ms, 12.5MB)
테스트 6 〉 | 통과 (3966.19ms, 20.8MB)
테스트 7 〉 | 통과 (4956.27ms, 20.8MB)
테스트 8 〉 | 통과 (5195.11ms, 20.8MB)
테스트 9 〉 | 통과 (4527.10ms, 20.8MB)
테스트 10 〉 | 통과 (6622.48ms, 20.9MB)
> [2024-08-01] gwangseok #183

- Programmers/2차원 동전 뒤집기/sungho.py
< 풀이시간 >
2시간
< 문제 풀이 및 회고 >
beginning에서 target 행렬로 바꾸는데 최소 뒤집기(행, 열 단위)로 만들 수 있으면 최소 뒤집기 수, 만들 수 없으면 -1 반환.
뚜렷한 해결방법이 보이지 않아 backtracking으로 문제를 풀었는데 시간초과가 발생했다. (행, 열 바꾸기 / 바꾸지 않기 로) 다른 방법으로 모든 경우의 수를 세보았는데 이 방법은 성공을 했고 꽤나 적은 시간에 통과를 하였다. 왜 되는지 아직도 잘 이해가 가지 않는다...
| ----------- | ---- | -------- | ------------- |
| 테스트 1    | 통과 | 0.32ms   | 10.3MB        |
| 테스트 2    | 통과 | 0.17ms   | 10.3MB        |
| 테스트 3    | 통과 | 0.22ms   | 10.4MB        |
| 테스트 4    | 통과 | 0.21ms   | 10.3MB        |
| 테스트 5    | 통과 | 0.27ms   | 10.3MB        |
| 테스트 6    | 통과 | 0.28ms   | 10.4MB        |
| 테스트 7    | 통과 | 0.35ms   | 10.3MB        |
| 테스트 8    | 통과 | 0.16ms   | 10.2MB        |
| 테스트 9    | 통과 | 0.14ms   | 10.4MB        |
| 테스트 10   | 통과 | 0.18ms   | 10.3MB        | …
> [2024-07-25] sungho #167

- Programmers/고고학 최고의 발견/sungho.py
1.5시간
모든 경우의 수를 생각해야하는데 어떻게 구현할지 계속 고민하다가 첫줄 혹은 마지막 줄을 제외하고는 계속 내리거나 올리는 식으로 변환하면 돼서 위에서부터 아래로 내려오면서 모든 원소들을 0으로 바꿔주는 식으로 코드를 진행했다. 또한 마지막 단계에서 0만 확인되면 모든 원소가 0이 되므로 해당 횟수를 비교하는 식으로 결과를 냈다.
|-------------|------|-----------|---------------|
| 테스트 1    | 통과 | 0.14ms    | 10.1MB        |
| 테스트 2    | 통과 | 0.14ms    | 10.3MB        |
| 테스트 3    | 통과 | 12.01ms   | 10.3MB        |
| 테스트 4    | 통과 | 1262.60ms | 12.3MB        |
| 테스트 5    | 통과 | 1484.95ms | 12.2MB        |
| 테스트 6    | 통과 | 6444.86ms | 18.6MB        |
| 테스트 7    | 통과 | 6977.44ms | 18.6MB        |
| 테스트 8    | 통과 | 6352.52ms | 18.6MB        |
| 테스트 9    | 통과 | 7108.19ms | 18.5MB        |
| 테스트 10   | 통과 | 6295.58ms | 18.5MB        |
> [2024-08-01] sungho #183

- Programmers/2차원 동전 뒤집기/gwangseok.py
<풀이 시간>
1시간 30분
<문제 회고>
문제를 보고 백준의 '체스판 다시 칠하기'가 떠올랐다.
Board의 크기가 완전탐색이 가능해서 백준 문제와 유사하게 완전탐색으로 해결하려고 했다.
완전탐색으로 하다가 해당 문제는 row와 col을 한번에 뒤집는 것이기 때문에 특별한 특징을 발견했다.
이런 특징을 찾고 반영하려고 고민을 많이 했다.
-- | --
테스트 1 〉 | 통과 (0.09ms, 10.4MB)
테스트 2 〉 | 통과 (0.06ms, 10.3MB)
테스트 3 〉 | 통과 (0.04ms, 10.4MB)
테스트 4 〉 | 통과 (0.04ms, 10.2MB)
테스트 5 〉 | 통과 (0.04ms, 10.3MB)
테스트 6 〉 | 통과 (0.03ms, 10.3MB)
테스트 7 〉 | 통과 (0.03ms, 10.3MB)
테스트 8 〉 | 통과 (0.03ms, 10.4MB)
테스트 9 〉 | 통과 (0.03ms, 10.3MB)
테스트 10 〉 | 통과 (0.03ms, 10.3MB)
테스트 11 〉 | 통과 (0.09ms, 10.4MB)
테스트 12 〉 | 통과 (0.06ms, 10.3MB)
테스트 13 〉 | 통과 (0.06ms, 10.3MB)
테스트 14 〉 | 통과 (0.06ms, 10.2MB)
테스트 15 〉 | 통과 (0.01ms, 10.3MB)
테스트 16 〉 | 통과 (0.01ms, 10.3MB)
테스트 17 〉 | 통과 (0.01ms, 10.3MB)
테스트 18 〉 | 통과 (0.03ms, 10.2MB)
테스트 19 〉 | 통과 (0.02ms, 10.4MB)
테스트 …
> [2024-07-25] gwangseok #167

- Programmers/마법의 엘리베이터/gwangseok.py
<풀이 시간>
40분
<문제 회고>
'각 자리수마다 5이하이면 아래로 이동 6이상이면 위로 이동 후 10 아래로 이동'
이라는 규칙을 발견했다.
하지만 통과하지 못하였다.
분기문에서 예외가 일어날 것 같아 고민했다.
5, 55, 555, 5555를 생각해보면서 반례를 발견하였다.
-- | --
테스트 2 〉 | 통과 (0.00ms, 10.4MB)
테스트 3 〉 | 통과 (0.00ms, 10.2MB)
테스트 5 〉 | 통과 (0.01ms, 10.2MB)
테스트 6 〉 | 통과 (0.00ms, 10.2MB)
테스트 7 〉 | 통과 (0.01ms, 10.2MB)
테스트 8 〉 | 통과 (0.01ms, 10.2MB)
테스트 9 〉 | 통과 (0.01ms, 10.4MB)
테스트 10 〉 | 통과 (0.01ms, 10.2MB)
테스트 11 〉 | 통과 (0.00ms, 10.1MB)
테스트 12 〉 | 통과 (0.01ms, 10.4MB)
테스트 13 〉 | 통과 (0.00ms, 10.2MB)
> [2024-08-06] gwangseok #189

- Programmers/마법의 엘리베이터/heewon.py
- 처음에는 순간 DP 문제로 오해했지만, 음수와 10의 c승과 같은 특수한 경우가 있어서 자릿수를 고려해야 한다는 것을 깨달았다.
- 코드를 작성하고 테스트해 보니, 예상과 다른 결과가 나와서 당황스러웠고, 이전에 해결했던 문제의 테스트 케이스 때문에 내가 놓친 부분이 있다는 것을 발견했다. 하지만 아쉽게도 직접 그 부분을 찾아내지 못했다. ex) 95, 45
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; …
> [2024-08-06] heewon #189

- Programmers/마법의 엘리베이터/sungho.py
< 풀이 시간 >
20분
< 회고 및 풀이 시간 >
bfs로 풀어도 될 거 같은데 규칙적인 방법이 보여서 그냥 풀었다.
|-------------|------|-----------|---------------|
| 테스트 1    | 통과 | 0.01ms    | 10.1MB        |
| 테스트 2    | 통과 | 0.00ms    | 10.2MB        |
| 테스트 3    | 통과 | 0.00ms    | 10.3MB        |
| 테스트 4    | 통과 | 0.01ms    | 10.3MB        |
| 테스트 5    | 통과 | 0.00ms    | 10.2MB        |
| 테스트 6    | 통과 | 0.00ms    | 10.2MB        |
| 테스트 7    | 통과 | 0.00ms    | 10.2MB        |
| 테스트 8    | 통과 | 0.00ms    | 10.2MB        |
| 테스트 9    | 통과 | 0.01ms    | 10.2MB        |
| 테스트 10   | 통과 | 0.00ms    | 10.4MB        |
| 테스트 11   | 통과 | 0.00ms    | 10.1MB        |
| 테스트 12   | 통과 | 0.01ms    | 10.2MB        |
| 테스트 13   | 통과 | 0.00ms    | 10.1MB        |
> [2024-08-06] sungho #189

- .github/ISSUE_TEMPLATE/daily-coding-problem.yml
- Programmers/카운트 다운/heewon.py
- DP로 접근 [다트 횟수, 싱글, 불 횟수]
- 0점 부터 target-1 점 까지 각각의 점수에서 다음 다트 점수 갱신
- 싱글, 불: 다트 횟수 최대 값으로 갱신, 다트 횟수가 같으면 싱글, 불 횟수 갱신
- 더블, 트리플: 다트 횟수 최대 값으로 갱신
- 1점 부터 247점 까지 50점과 60점의 차이로 인한 60 주기를 안 가짐 (코드 추가)
- 시간: 2 hour 이하
- 힌트: `None`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; …
> [2024-08-08] heewon #191

- LeetCode/3016/sungho.py
< 풀이 시간 > 
20분
< 문제 회고 및 풀이 >
다른 문제들은 조금 어려운 게 있었는데 해당 문제는 이해하면 바로 그대로 풀리는 문제였다. (다른 문제들은 이전에 푼 문제들과 달리 시간 복잡도가 더 빡빡했던 거 같음)
> [2024-08-13] Sungho #200

- Programmers/카운트 다운/yerin.py
<풀이 시간>
2시간 이상
<문제 회고>
dp로 문제를 풀어 통과는 됐는데 질문하기에서 특정 숫자들의 경우 답이 다르게 나온다는 이야기를 보았다. 191의 경우 코드에서 [4, 2]가 나오는데 직접 세어봤을 때 해당 경우에 맞는 점수 조합을 찾지 못했다. 디버깅을 하여 [40, 50, 50, 51]의 조합을 알아냈다.
bfs로도 풀어 봤는데 시간이 확실히 더 오래 걸렸다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.03ms, 10.4MB)
테스트 2 〉 | 통과 (1417.36ms, 21.6MB)
테스트 3 〉 | 통과 (1009.66ms, 18.4MB)
테스트 4 〉 | 통과 (987.84ms, 18.6MB)
테스트 5 〉 | 통과 (1390.75ms, 19.9MB)
테스트 6 〉 | 통과 (1585.62ms, 19.4MB)
테스트 7 〉 | 통과 (1315.67ms, 19.4MB)
테스트 8 〉 | 통과 (68.72ms, 10.6MB)
테스트 9 〉 | 통과 (1359.31ms, 20.2MB)
테스트 10 〉 | 통과 (233.72ms, 11.4MB)
테스트 11 〉 | 통과 (254.60ms, 11.9MB)
테스트 12 〉 | 통과 (1381.19ms, 20.9MB)
테스트 13 〉 | 통과 (381.78ms, 13MB)
테스트 14 〉 | 통과 (1530.11ms, 21.3MB)
테스트 15 〉 | 통과 (1116.28ms, 18.5MB)
테스트 16 〉 | 통과 (224.96ms, 11.8MB)
테스트 17 〉 | 통과 (149.08ms, 11MB)
테스트 18 〉 | 통과 …
> [2024-08-08] yerin #191

- LeetCode/2/gwangseok.py
<풀이 시간>
20분
<문제 회고>
오랜만에 linked list를 사용해봤다.
> [2024-08-20] gwangseok #206

- LeetCode/2/heewon.py
- 차례대로 노드끼리 합친다. 10 보다 크면 다음 노드에서 추가한다.
- 다양한 타입의 변수를 사용해서 신기
> [2024-08-20] heewon #206

- LeetCode/2/yerin.py
반환값이 정해져 있다보니 다소 불편했다. 그래도 덕분에 오랜만에 linked list도 써보고 공부할 수 있는 시간이었다.
> [2024-08-20] yerin #206

- 카운트 다운/sumin.py
**<풀이 시간>**
50분
**<문제 회고>**
문제를 보면서 반복되는 동일한 하위 문제이기 때문에 DP인걸 빠르게 알았지만, 점화식을 짤 때 약간 헤맸다.
고민 끝에 점화식을 먼저 작성하고 코드를 작성해서 통과했다.
-- | --
테스트 2 〉 | 통과 (1168.38ms, 18.6MB)
테스트 3 〉 | 통과 (832.52ms, 15.8MB)
테스트 4 〉 | 통과 (877.21ms, 16.1MB)
테스트 5 〉 | 통과 (977.40ms, 17.2MB)
테스트 6 〉 | 통과 (948.71ms, 16.6MB)
테스트 7 〉 | 통과 (954.45ms, 16.6MB)
테스트 8 〉 | 통과 (60.51ms, 10.3MB)
테스트 9 〉 | 통과 (996.78ms, 17.2MB)
테스트 10 〉 | 통과 (146.57ms, 10.4MB)
테스트 11 〉 | 통과 (187.04ms, 10.9MB)
테스트 12 〉 | 통과 (1096.70ms, 17.7MB)
테스트 13 〉 | 통과 (276.02ms, 11.8MB)
테스트 14 〉 | 통과 (1183.22ms, 18.2MB)
테스트 15 〉 | 통과 (817.92ms, 15.9MB)
테스트 16 〉 | 통과 (174.95ms, 10.9MB)
테스트 17 〉 | 통과 (114.25ms, 10.7MB)
테스트 18 〉 | 통과 (1138.85ms, 17.7MB)
테스트 19 〉 | 통과 (478.34ms, 13.4MB)
테스트 20 〉 | 통과 (1402.60ms, …
> [2024-08-08] sumin #191

- LeetCode/3016/sumin.py
> [2024-08-13] sumin #200

- LeetCode/2/sumin.py
**<풀이 시간>**
35분
**<문제 회고>**
문제의 위에 주석처리된 ListNode 클래스를 사용해서 풀이해야 해서 번거로웠던 문제...
> [2024-08-20] sumin #206

- Programmers/카운트 다운/sungho.py
< 풀이 시간 > 
30분
< 문제 회고 및 풀이 >
계산해보니까 50점과 60점, 20점 중에 점수가 정해진 sort에 따라 전처리하면 돼서 그렇게 문제 풀었다. 
| 테스트 번호 | 결과  | 실행 시간 | 메모리 사용량 |
|-------------|-------|-----------|---------------|
| 테스트 1    | 통과  | 0.01ms    | 10.3MB        |
| 테스트 2    | 통과  | 184.22ms  | 29.2MB        |
| 테스트 3    | 통과  | 126.08ms  | 21.1MB        |
| 테스트 4    | 통과  | 127.17ms  | 21.2MB        |
| 테스트 5    | 통과  | 161.31ms  | 22.7MB        |
| 테스트 6    | 통과  | 142.07ms  | 22.1MB        |
| 테스트 7    | 통과  | 143.01ms  | 22.3MB        |
| 테스트 8    | 통과  | 9.07ms    | 10.6MB        |
| 테스트 9    | 통과  | 150.18ms  | 22.8MB        |
| 테스트 10   | 통과  | 26.13ms   | 12.1MB        |
| 테스트 11   | 통과  | 29.81ms   | 12.3MB        |
| 테스트 12   | 통과  | 169.41ms  | 23.6MB        |
| 테스트 13   | 통과  | 44.40ms   | 14.3MB        |
| 테스트 14 …
> [2024-08-08] sungho #191

- LeetCode/2/sungho.py
Linked List!
Runtime : 46ms Beats 49.05%
Memory: 11.75MB Beats 32.63%
> [2024-08-20] sungho #206 

- LeetCode/3/gwangseok.py
<풀이 시간>
30분
<문제 회고>
투 포인터를 활용해 문제를 해결하였다.
> [2024-08-22] gwangseok #208

- LeetCode/3/sumin.py
**<풀이 시간>**
20분
어렵지 않은 투포인터 문제
> [2024-08-22] sumin #208

- LeetCode/3/heewon.py
- defaultdict, str 를 이용한 슬라이딩 윈도우 초기 작성
- hashmap을 이용한 최적화 코드 추가
> [2024-08-21] heewon #208

- LeetCode/2/yerin.py
- LeetCode/5/yerin.py
초반에 palindromic 개념을 잘못 이해하고 문제를 풀어서 혼란이 있었다.
- 직접 서브스트링을 뒤집어 palindromic을 확인 ->  O(n**3)
: 마땅히 떠오르는 방법이 없었다. 역시나 속도나 메모리 측면에서 굉장히 비효율적인 결과가 나왔다.
- 센터를 기준으로 palindromic substring 탐색 -> O(n**2)
: 다른 코드들을 참고해 힌트를 얻었다.
> [2024-08-27] yerin #214

- LeetCode/5/heewon.py
1. 각 문자가 위치한 인덱스를 저장하기 위해 딕셔너리를 사용했습니다.
2. 딕셔너리에서 문자별로 가능한 두 개의 조합을 추출하고, 두 인덱스의 차이가 큰 순서대로 확인했습니다.
3. Palindrome인 서브 스트링을 발견하면 기존 문자열과 비교하고 해당 문자 확인을 종료하고 다음 문자를 확인하는 방식으로 구현하여 시간 복잡도를 줄였습니다.
- Palindrome을 판별하는 방법을 while문으로 구현 했다가 time limit가 발생해서 고민하다가 뒤집어서 확인했습니다.
- 딕셔너리 사용으로 memory 효율 나쁨
> [2024-08-27] heewon #214

- LeetCode/5/sumin.py
이 코드를 23년에도 풀었다고 나오는데 전혀 기억이 안나고 그 때는 투포인터로 훨씬 효율적으로 풀었네용;;
이게 투포인터 풀이 결과인데 메모리, 런타임 다 훨씬 효율적으로 동작해용.. 어떻게 더 멍청해질수가..ㅠㅠ
> [2024-08-27] sumin #214

- LeetCode/5/gwangseok.py
<풀이 시간>
40분
<문제 회고>
문제를 보고 O(N^2)으로 풀어도 될 것 같다는 느낌이 들었다. 
가장 naive하게 2중 for문으로 문자열 길이를 조절하려고 했는데, 
해당 문자열이 palindromic인지 검사하려니 또 O(N)이 걸려 총 O(N^3) 만큼 걸린다.
고민하다가 문자열을 for문을 돌면서 해당 index의 문자열을 center로 생각하고 좌우로 1씩 증가시키면서
검사를 하면 O(N^2)이 걸리게 되는 것을 깨달았다.
> [2024-08-27] gwangseok #214 

- LeetCode/6/gwangseok.py
<풀이 시간>
20분
<문제 회고>
numRows마다 zigzag 패턴이 존재한다.
해당 패턴을 파악한 후, 문제에서 주어진 문자열 대로 저장한다.
> [2024-08-29] gwangseok #224

- LeetCode/7/sumin.py
> [2024-09-03] sumin #228

- LeetCode/6/heewon.py
- 주기(`2 * (numRows - 1)`)를 이용하여 row에 추가를 하자
- row의 크기 보다 큰 경우는 주기에서 idx를 빼주자
- 예시) numRows  = 4 -> 주기 = 2 * 4 - 2 = 6개
- 15min 이하
> [2024-08-29] heewon #224

- LeetCode/7/sungho.py
Runtime 10ms Beats 91.22%
Memory 11.52MB Beats 70.91%
> [2024-09-03] sungho #228

- LeetCode/7/gwangseok.py
<풀이 시간>
10분
<문제 회고>
문제 의도를 명확히 모르겠다.
> [2024-09-03] gwangseok #228

- LeetCode/7/heewon.py
> [2024-09-03] heewon #228

- LeetCode/7/yerin.py
<풀이 시간>
10분
<문제 회고>
조건만 신경쓰면 됐던 문제. 떠오른 풀이가 int <-> str 변환이 잦아 다른 방법도 찾아보니, 수학을 활용한 방식이 있었다.
> [2024-09-03] yerin #228

- LeetCode/11/yerin.py
<풀이 시간>
20분
<문제 회고>
문제를 읽고 투포인터 문제인가 싶었지만 시간복잡도가 O(n**2)이 아닌 풀이가 떠오르지 않았다. 정렬로 어찌 풀긴했지만 O(nlogn)이라 빠르다고 할 수 없는 속도가 나왔다. 다른 투포인터 문제들도 풀어보면 좋을 것 같다.
> [2024-09-10] yerin #239

- LeetCode/11/gwangseok.py
<풀이 시간>
2시간 이상
<문제 회고>
문제를 처음 보고 감이 안 잡혔다.
유사한 문제를 스택으로 해결한 경험이 있어 도전했지만, 잘 되지 않았다.
힌트를 봐서 투포인터로 푸는 거라는 걸 알게 되었다.
투포인터는 greedy한 알고리즘에서만 사용할 수 있는데,
일반적인 투포인터로 [1, 1, 1, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1,] 과 같은 경우를 해결할 방법이 안 떠올랐다.
Discussion을 참고해 문제를 이해하고 풀었다.
저장해놨다가 다시 풀어봐야 겠다.
> [2024-09-10]  gwangseok #239

- LeetCode/452/gwangseok.py
<풀이 시간>
40분
<문제 회고>
어떻게 해결해야 할 지 감이 잘 안 잡혔다.
Constraints를 보고 points만 보고 방법을 생각해 내야겠다고 판단했다.
스택과 관련된 문제인 것 같아 해당 방법으로 생각해봤는데, greedy하게 스택에 넣고 빼야 했다.
그러다 굳이 스택을 사용하지 않고 바로 greedy하게 하면 될 것 같아서 그렇게 풀었다.
> [2024-09-05] gwangseok #238

- LeetCode/8/sungho_0905.py
그림 그려서 푸니까 쉽게 풀었습니다. 5분? 10분?
예전에 프로그래머스에 최소 강의실 수랑 문제가 비슷한 거 같아요
Runtime 1042 Beats 45.41%
Memory 60.33 Beats 90.91%\
> [2024-09-05] sungho #238

- LeetCode/11/heewon.py
- 투 포인터
- 서로 양 끝에서 시작하는 경우는 처음이라 힌트를 참고하여 풀었다.
- 조건을 생각하고 구현하지 못 한 점이 아쉽다
> [2024-09-10] heewon #239

- LeetCode/452/heewon.py
- 시간:  5분
- 유사한 문제: [단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884), [요격 시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
- 동일한 알고리즘 + 입출력 방식 수정
> [2024-09-05] heewon #238

- LeetCode/6/sumin.py
**<풀이 시간>**
15분
문제의 테스트 케이스에 주어진대로 구현하면 위아래로 계속 지그재그 반복되기 때문에 back이라는 변수를 둬서 위아래 방향을 판단
> [2024-08-29] sumin #224

- LeetCode/452/sumin.py
풀이 시간: 20분
백준의 회의실 배정과 유사한 전형적인 그리디 알고리즘 문제
> [2024-09-05] sumin #238

- LeetCode/122/gwangseok.py
<풀이 시간>
5분
<문제 풀이>
간단한 그리디 문제로, 현재보다 큰 값이 나오면 팔고 현재보다 낮으면 현재 가격을 업데이트하면 된다.
> [2024-09-19] gwangseok #241

- LeetCode/452/yerin.py
<풀이 시간>
30분
<문제 회고>
단순히 생각나는대로 풀었다. 빠른 코드들과 속도 차이는 꽤 큰 편이어서 속도 측면에서 아쉬움이 있다.
> [2024-09-05] yerin #238

- LeetCode/128/yerin.py
<풀이 시간>
30분
<문제 회고>
문제를 읽자마자 정렬하면 금방 풀겠다고 생각했다. 그런데 O(n)의 시간복잡도를 가져야 한다고 적혀있어 정렬은 쓰면 안되겠구나 생각했다. 모든 숫자들을 한 번씩만 확인하는 로직을 생각해내려고 고민하는데 시간을 대부분 썼다. 그런데 막상 정렬로도 구현을 해보았는데 통과과 됐다🤪
> [2024-09-12] yerin #240

- LeetCode/74/sumin.py
**<풀이 시간>**
10분
이진 탐색으로 풀이했는데 완탐으로 해도 될 것 같다
> [2024-09-26] sumin #243

- LeetCode/909/sumin.py
**<풀이 시간>**
45분
수 제한이 작아 BFS로 풀이하는 건 빠르게 파악했으나, 각 숫자를 row, col 형태로 변환하는걸 찾는데 시간이 가장 오래 걸렸다.
구현 문제를 오랜만에 풀었더니 감이 많이 떨어진 것 같다
> [2024-09-24] sumin #242

- LeetCode/128/heewon.py
- O(n) 풀려고 했지만 내 머리가 거부했다...
- 대부분 O(nlogn)으로 풀었다는 토론글을 보고 풀어보니 생각보다 쉬운 문제였다...
> [2024-09-12] heewon #240

- LeetCode/122/heewon.py
- 간단한 그리디 문제였지만 너무 생각이 많아서 어렵게 풀어서 오래 걸렸다.
- 가장 작은 단위로 상승(>0)만 하면 산다
> [2024-09-19] heewon #241

- LeetCode/74/yerin.py
> [2024-09-26] yerin #243

- LeetCode/909/gwangseok.py
<풀이 시간>
40분
<문제 회고>
BFS 문제인건 금방 알았으나, 문제를 이해하고 구현하는 데 시간이 걸렸다.
> [2024-09-24] gwangseok #242

- LeetCode/909/yerin.py
문제를 이해하는 데 오래 걸렸다. n의 크기도 작고 최단거리를 구해야하니 bfs로 풀었다.
> [2024-09-24] yerin #242

- LeetCode/909/sungho.py
Runtime 89ms Beats 91.50%
Memory 16.63MB Beats 71.50%
> [2024-09-24] sungho #242

- LeetCode/74/gwangseok.py
<풀이 시간>
15분
<문제 회고>
배열이 정렬되어 있고, 제한 시간이 log (n * m)이라서 binary search를 활용했다.
직접 구현하려고 했지만, python 모듈을 활용했다.
> [2024-09-26] gwangseok #243

- LeetCode/74/heewon.py
> [2024-09-26] heewon #243

- LeetCode/236/gwangseok.py
<풀이 시간>
1 시간
<문제 회고>
LCA 알고리즘은 알고 있지만 오랜만에 보니 기억이 안 났다.
처음에 혼자 풀어 봤지만, 굉장히 복잡해지고 생각보다 잘 풀리지 않았다.
그래서 LCA 푸는 법을 찾아봤다.
두 노드의 깊이를 같게 만들면 문제가 간단해진다.
N은 tree의 깊이라고 하자.
첫 번째 방법은 탐색 시간이 O(N) 걸리고, 부모를 저장하는 메모리는 O($2^N$)이다.
두 번째 방법은 탐색 시간이 O(log  N)이지만, 부모를 저장하는 메모리는 O($N \times 2^N$)이 필요하다.
N이 $log_2(10^5) \approx 17$ 라서 간단하게 구현할 수 있는  첫 번째 방법을 활용했다.
> [2024-10-01] gwangseok #274

- LeetCode/274/sumin.py
**<풀이 시간>**
40분 정도 고민하다가 재귀로 풀이할 수는 있을거 같은데 방향이 안잡혀서 풀이를 참고했다.
특히 두 번째 테스트케이스를 어떻게 처리해줘야 하는지 감이 안왔는데 생각보다 간단했다.
왼쪽과 오른쪽 서브트리에서 각각 찾은 경우가 아니라 한쪽에서만 찾은 경우, LCA는 그 찾은 노드 자체이기 때문이다.
LCA 알고리즘은 전혀 기억이 안나는걸 보니 처음보는 알고리즘인 것 같아 익숙해질때까지 관련 문제를 좀 더 풀어봐야겠다.
> [2024-10-01] sumin #274

- LeetCode/236/yerin.py
노드 문제는 언제 풀어도 익숙치 않은 느낌이다. 부모 노드를 저장하고 비교, 탐색하는 식으로 풀이를 했다. 도중에 재귀로 풀어도 되겠다는 생각이 들었는데 코드가 생각이 안났다..ㅎ
> [2024-10-01] yerin #274

- LeetCode/236/heewon.py
- 트리 문제라서 다소 긴장한 상태로 접근(not 익숙)
- 1st
- BFS로 노드를 탐색해서 p,q의 조상들을 저장하는 방식
- 부모의 저장을 리스트 [깊이1 조상 노드, 깊이2 조상 노드, ... 부모 노드] 방식으로 저장이 됨
- p와 q의 최소 깊이 부터 차근차근 조상이 같은지 확인한다.
- 맞았지만 거의 커트라인의 풀이
- 2nd
- 동일하게 BFS 방식으로 조상을 저장하지만 딕셔너리 활용
- 확인하는 작업을 집합을 이용하여 구현 - q의 조상들과 비교하여 p의 조상을 확인하며 곹동 조상 찾기
- 시간 복잡도 줄이기 성공
> [2024-10-01] heewon #274

- LeetCode/79/gwangseok.py
<풀이 시간>
20분
<문제 회고>
비슷한 문제(백준 [보글](https://www.acmicpc.net/problem/9202))를 푼 적이 있어 trie 자료구조를 활용해 풀어야 하나 생각했다.
하지만, 찾고자 하는 단어가 하나이기 때문에 단순히 dfs를 활용해 풀었다.
LeetCode에서도 Top 150에 백준 보글과 같은 문제인 [Word Search II](https://leetcode.com/problems/word-search-ii/?envType=study-plan-v2&envId=top-interview-150)가 있는데, 해당 문제는 trie를 활용해 풀어야 할 것 같다.
> [2024-10-03] gwangseok #275

- LeetCode/79/sumin.py
**<풀이 시간>**
45분
백트래킹을 너무 오랜만에 풀어서 생각보다 오래 걸린 문제
백트래킹 문제 연습좀 다시 해야할 것 같다
런타임이 너무 오래걸린다
> [2024-10-03] sumin #275

- LeetCode/80/yerin.py
공간복잡도를 신경쓰면서 푼 첫 문제. 평소 시간복잡도만큼 신경쓰지는 않았던 요소였었으나 이번 문제를 풀어보면서 앞으로 공간복잡도도 고려해서 더 효율적인 코드를 고민해보면 좋을 거 같았음.
> [2024-10-08] yerin #285

- LeetCode/79/yerin.py
처음에는 더 익숙한 bfs로 풀었었는데 파이썬의 얕은 복사 성질 때문에 방문처리가 까다로웠음. 깊은 복사의 반복, 그리고 너비 우선 탐색인 bfs 특성상 하나의 단어만 찾으면 되는 해당 문제에는 비효율적이라고 생각. 실제로도 엄청 느리고 메모리 비효율적이었음. dfs로 바꿔서 문제를 풀이.
> [2024-10-03] yerin #275

- LeetCode/80/sumin.py
**<풀이 시간>**
리트코드의 in-place 로 배열을 수정해서 풀이하는 문제들에 대한 사고가 아직 부족한 것 같다.
다 풀고나서 풀이를 보니 cnt를 쓰지 않고도 풀이할 수 있는 방법이 있어서 좀 더 효율적으로 코드를 짤 수 있도록 고민해봐야할 것 같다.
> [2024-10-08] sumin #285

- LeetCode/79/heewon.py
- BFS (비효율의 끝판왕)
- DFS + backtracking
> [2024-10-03] heewon #275

- CodeTree/나무 타이쿤/heewon.py
- LeetCode/80/heewon.py
- 풀이시간: 15분
- 접근 방식
1. 리스트에서 처음 두 개의 값은 무조건 포함될 수 있음
2. 현재 숫자와 두 개 전의 숫자를 비교
> [2024-10-08] heewon #285 

- CodeTree/나무 타이쿤/heewon.py
- 풀이시간: 1시간
- 접근 방식
1. 조건을 차례대로 구현 함
2. 영양제 적용하는 부분에서 1증가와 대각선 증가를 동시에 했더니 오답 -> 찾는 과정에서 시간 걸림
- 느낀점: 토론이 적다 = 어려운 반례가 없다
> [2024-10-10] heewon #289

- LeetCode/209/sungho_1017.py
실행시간 181ms 89.77%
메모리 22.32MB 29.65%
> [2024-10-17] sungho #297

- LeetCode/209/sumin.py
**<풀이 시간>**
20분
투포인터로 풀이할 수 있는 간단한 문제
> [2024-10-17] sumin #297

- CodeTree/놀이기구 탑승/heewon.py
- LeetCode/209/heewon.py
- 풀이시간: 15분
- 접근 방식
1. 슬라이딩 윈도우 색다르게 target 이상이였다.
2. 코드 차이가 없어도 시간복잡도 2배 차이가 난다.
> [2024-10-17] heewon #297

- LeetCode/209/yerin.py
nums의 길이가 최대 10만이고 서브배열 문제인 걸 보고 투포인터로 풀 수 있겠구나 싶었다. 그런데 다른 코드를 살펴보니 같은 로직으로 풀었던데 시간 차이가 꽤 났다.
> [2024-10-17] yerin #297

- BaekJoon/13334/sumin.py
> [2024-10-22] sumin #304

- CodeTree/놀이기구 탑승/heewon.py
- 풀이시간: 1시간
- 접근 방식
1. 조건을 차례대로 구현 함
2. 배치 순간마다 points 에 좌표 순서대로 [좋아하는 사람 수, 빈 자리 수, 행, 열]를 구하고 최고의 좌표를 구함
3. T1 맞추고 정답
> [2024-10-15] heewon #293

- BaekJoon/13334/yerin.py
<풀이 시간>
1시간 이상
<회고>
풀이를 생각하는데 시간이 걸렸다. 시간을 줄일 수 있을만한 풀이가 떠오르지 않았다. 다른 풀이를 참고하고 heapq를 사용해 풀 수 있다는 것을 알았다.
> [2024-10-22] yerin #304 

- Programmers/수식 복원하기/sungho.py
| 테스트 번호 | 결과 | 실행시간 | 메모리 |
|-----------|------|----------|---------|
| 1 | 통과 | 0.32ms | 10.4MB |
| 2 | 통과 | 0.11ms | 10.5MB |
| 3 | 통과 | 0.15ms | 10.4MB |
| 4 | 통과 | 0.14ms | 10.5MB |
| 5 | 통과 | 0.19ms | 10.4MB |
| 6 | 통과 | 0.12ms | 10.5MB |
| 7 | 통과 | 0.30ms | 10.4MB |
| 8 | 통과 | 0.31ms | 10.4MB |
| 9 | 통과 | 1.46ms | 10.4MB |
| 10 | 통과 | 0.54ms | 10.5MB |
| 11 | 통과 | 0.69ms | 10.4MB |
| 12 | 통과 | 0.52ms | 10.4MB |
| 13 | 통과 | 0.23ms | 10.4MB |
| 14 | 통과 | 0.22ms | 10.5MB |
| 15 | 통과 | 0.35ms | 10.4MB |
| 16 | 통과 | 0.31ms | 10.5MB |
| 17 | 통과 | 0.70ms | 10.5MB |
| 18 | 통과 | 1.09ms | 10.4MB |
| 19 | 통과 | 1.48ms | 10.3MB |
| 20 | 통과 | 0.89ms | 10.4MB |
| 21 | 통과 | 1.56ms | 10.5MB |
| 22 | 통과 | 0.48ms | 10.4MB |
| 23 | 통과 | 0.54ms | 10.5MB |
> [2024-10-29] sungho #311

- Programmers/수식 복원하기/heewon.py
- if를 너무 많이 사용 -> 코드 수정
1. X식들, noX식들 저장
2. 가능한 진법들 구하기
3. 가능한 진법들 확인하기
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; color: rgb(38, 55, 71); …
> [2024-10-29] heewon #311

- CodeTree/놀이기구 탑승/sungho_1014.py
30분
우선 순위를 어떻게 정할지를 고민하다가(heapq, sort 등 고민) 부등호 하나로 해결할 수 있을거 같아서 부등호 하나로 해결하였다.
197ms | 26MB
> [2024-10-15] sungho #293

- BaekJoon/13334/sungho.py
처음에 풀었을 때 시간 부족으로 문제를 틀렸었는데
1차적으로 가능한 요소들로 줄이고
가능한 요소들 내에서 정렬 후 세어나가는 식으로 하니 문제가 풀렸다.
이 문제 이후 차근차근 되는 요소들 한에서 한쪽으로 정렬하여 문제를 푸는 방식을 익히게 되었다. (아직도 heap은 어색하긴 함)
> [2024-10-22] sungho #304

- LeetCode/15/sungho.py
Runtime 1248ms Beats 33.48%
Memory 15.57MB Beats 23.43%
이전에 프로그래머스에서 비슷한 문제 풀었던 거 같은 ㅋㅋ
> [2024-10-24] sungho #309

- LeetCode/15/yerin.py
<풀이 시간>
1시간 이상
<문제 회고>
시간초과와의 싸움이었다. 처음에 조합으로 문제를 푸는 게 생각이 났다. 그런데 최악 O(n**3)의 시간복잡도까지 갖게 되면서 아니나다를까 시간초과..리트코드에서 자주 본 투포인터로 풀어야 하나 싶어서 투포인터로 풀었다. 중복을 줄이고자 left와 right를 세 개의 수를 합한 값이 0이 아니더라도 while문을 돌며 중복 처리를 해줬는데 시간이 더 오래걸렸다 ..ㅎㅎ
> [2024-10-24] yerin #309

- Programmers/수식 복원하기/yerin.py
<문제 회고>
예외 케이스를 생각 못해서 시간이 많이 걸렸다. 답이 있는 식들을 순환하면서 특정 진수에 해당하는 경우, 반환하고 바로 멈추게 했다. 알고보니 모든 식을 만족하는 진수가 여러 개일수도 있다는 걸 뒤늦게 알았다.
그리고 특정 진수로 변환하는 함수를 직접 구현했는데 int 모듈로 손쉽게 구현할 수 있다는 걸 알게 되었다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.18ms, 10.3MB)
테스트 2 〉 | 통과 (0.17ms, 10.5MB)
테스트 3 〉 | 통과 (0.32ms, 10.6MB)
테스트 4 〉 | 통과 (0.17ms, 10.5MB)
테스트 5 〉 | 통과 (0.41ms, 10.4MB)
테스트 6 〉 | 통과 (0.15ms, 10.5MB)
테스트 7 〉 | 통과 (0.54ms, 10.6MB)
테스트 8 〉 | 통과 (0.29ms, 10.4MB)
테스트 9 〉 | 통과 (0.85ms, 10.4MB)
테스트 10 〉 | 통과 (0.73ms, 10.5MB)
테스트 11 〉 | 통과 (0.86ms, 10.5MB)
테스트 12 〉 | 통과 (1.06ms, 10.6MB)
테스트 13 〉 | 통과 (0.23ms, 10.4MB)
테스트 14 〉 | 통과 (0.23ms, 10.4MB)
테스트 15 〉 | 통과 (0.69ms, 10.5MB)
테스트 16 〉 | 통과 (0.15ms, 10.5MB)
테스트 17 〉 | 통과 (0.32ms, 10.5MB)
테스트 18 〉 | 통과 (0.50ms, 10.5MB)
테스트 19 〉 | 통과 (1.28ms, 10.4MB)
테스트 20 〉 | 통과 …
> [2024-10-29] yerin #311

- Programmers/등산코스 정하기/heewon.py
1. 각각의 gate와 각각의 summit의 최적 시간 구해서 답 구하기 -> **시간 초과**
2. 각각의 summit에서의 모든 gate 까지의 거리 구해서 답 구하기 -> **시간 초과**
3. 모든 gate에서 모든 summit 까지의 시간을 한번에 구하기 -> **성공**
- 풀었던 문제지만 틀렸다... 확실한 복습이 필요할 듯
`defaultdict`, `heapq`
- 시간: 1 hour 이상
- 힌트: `YES`
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; …
> [2024-11-05] heewon #324

- LeetCode/17/sumin.py
> [2024-11-07] sumin #329

- LeetCode/17/heewon.py
> [2024-11-07] heewon #329

- Programmers/수식 복원하기/sumin.py
**<풀이 시간>**
1시간 10분
처음에 문제를 잘 못 이해해서 한참 걸렸다. 테스트 케이스 두번째에서 왜 6진법부터 되는지 이해하는데도 시간이 걸렸다;;
그 외에는 수제한이 작아서 그렇게까지 까다롭지는 않았던 문제였는데도 풀이가 꽤 걸렸다.
정확성 | 테스트
-- | --
테스트 1 〉 | 통과 (0.18ms, 10.3MB)
테스트 2 〉 | 통과 (0.11ms, 10.3MB)
테스트 3 〉 | 통과 (0.12ms, 10.4MB)
테스트 4 〉 | 통과 (0.13ms, 10.4MB)
테스트 5 〉 | 통과 (0.15ms, 10.4MB)
테스트 6 〉 | 통과 (0.11ms, 10.4MB)
테스트 7 〉 | 통과 (0.49ms, 10.3MB)
테스트 8 〉 | 통과 (0.47ms, 10.3MB)
테스트 9 〉 | 통과 (0.69ms, 10.4MB)
테스트 10 〉 | 통과 (0.48ms, 10.4MB)
테스트 11 〉 | 통과 (0.40ms, 10.4MB)
테스트 12 〉 | 통과 (0.40ms, 10.4MB)
테스트 13 〉 | 통과 (0.20ms, 10.3MB)
테스트 14 〉 | 통과 (0.11ms, 10.4MB)
테스트 15 〉 | 통과 (0.21ms, 10.3MB)
테스트 16 〉 | 통과 (0.23ms, 10.3MB)
테스트 17 〉 | 통과 (0.31ms, 10.3MB)
테스트 18 〉 | 통과 (0.46ms, 10.3MB)
테스트 19 〉 | 통과 (0.67ms, 10.4MB)
테스트 20 〉 | 통과 (0.42ms, 10.3MB)
테스트 21 〉 | 통과 (0.71ms, 10.2MB) …
> [2024-10-29] sumin #311

- LeetCode/17/yerin.py
<풀이 시간>
20분
<문제 회고>
digits의 길이가 굉장히 작아서 가장 먼저 생각났던 재귀로 문제를 풀었다.
> [2024-11-07] yerin #329

- Programmers/등산코스 정하기/yerin.py
<풀이 시간>
2시간 이상
<문제 회고>
처음 문제를 보고 다익스트라 문제인가 싶었다. 그런데 푸는 과정에서 문제를 잘못 이해했음을 깨닫고 좀 더 직관적으로 다가왔던 bfs로 선회했다. 문제에서 경유할 수 있는 지점에 대한 조건을 자세히 명시해줬기 때문에 어려움 없이 조건을 작성했다. 다른 풀이를 보니 다익스트라를 활용한 분들이 있었는데 참고가 되었다. 그런데 다른 분들에 비해 속도가 느린 편이라 좀 더 고민해봐야 할 거 같당
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.03ms, 10.4MB)
테스트 2 〉 | 통과 (0.02ms, 10.2MB)
테스트 3 〉 | 통과 (0.02ms, 10.2MB)
테스트 5 〉 | 통과 (0.02ms, 10.2MB)
테스트 6 〉 | 통과 (0.06ms, 10.1MB)
테스트 7 〉 | 통과 (0.06ms, 10.2MB)
테스트 8 〉 | 통과 (0.06ms, 10.3MB)
테스트 9 〉 | 통과 (0.11ms, 10.2MB)
테스트 10 〉 | 통과 (0.28ms, 10.1MB)
테스트 11 〉 | 통과 (0.19ms, 10.4MB)
테스트 12 〉 | 통과 (0.28ms, 10.3MB)
테스트 13 〉 | 통과 (13.86ms, 11.6MB)
테스트 14 〉 | 통과 (113.68ms, 20.8MB)
테스트 15 〉 | 통과 (1093.36ms, 80.3MB)
테스트 16 〉 | 통과 (956.70ms, 82.9MB)
테스트 17 〉 | 통과 (953.92ms, 82.9MB)
테스트 18 〉 | 통과 …
> [2024-11-05] yerin #324

- Programmers/등산코스 정하기/sumin.py
**<풀이 시간>**
1시간 30분
계속 다익스트라로 풀이하다가 방향을 못잡아서 
[힌트](https://tech.kakao.com/posts/530)를 참고해서 풀이
까다로웠어서 다시 한번 풀어봐야 할 듯
정확성 | 테스트
-- | --
테스트 1 〉 | 통과 (0.04ms, 10.6MB)
테스트 2 〉 | 통과 (0.02ms, 10.5MB)
테스트 3 〉 | 통과 (0.03ms, 10.5MB)
테스트 4 〉 | 통과 (0.01ms, 10.3MB)
테스트 5 〉 | 통과 (0.02ms, 10.4MB)
테스트 6 〉 | 통과 (0.08ms, 10.4MB)
테스트 7 〉 | 통과 (0.10ms, 10.6MB)
테스트 8 〉 | 통과 (0.10ms, 10.6MB)
테스트 9 〉 | 통과 (0.17ms, 10.4MB)
테스트 10 〉 | 통과 (0.31ms, 10.6MB)
테스트 11 〉 | 통과 (0.25ms, 10.6MB)
테스트 12 〉 | 통과 (0.38ms, 10.6MB)
테스트 13 〉 | 통과 (6.38ms, 11.9MB)
테스트 14 〉 | 통과 (31.72ms, 20.4MB)
테스트 15 〉 | 통과 (277.39ms, 74.8MB)
테스트 16 〉 | 통과 (308.46ms, 77.4MB)
테스트 17 〉 | 통과 (293.51ms, 77.3MB)
테스트 18 〉 | 통과 (17.83ms, 15.8MB)
테스트 19 〉 | 통과 (112.24ms, 34.3MB)
테스트 20 〉 | 통과 (337.52ms, 71.4MB)
테스트 21 〉 | 통과 (378.01ms, 68.3MB)
테스트 22 〉 …
> [2024-11-05] sumin #324

- LeetCode/15/sumin.py
**<풀이 시간>**
40분
이전에 풀어봤던 문제인데도 풀이하는데 시간이 꽤 걸렸다.
> [2024-10-24] sumin #309 

- LeetCode/15/heewon.py
- 풀이시간: 1시간
- 접근 방식
1. 조합을 이용한 풀이 방법 밖에 생각이 안 났음
2. 기존: nC3, 변경: nC2(중복X) + 중복2 + 0 3개
3. 값 확인으로 조건을 시간 복잡도 감소
> [2024-10-24] heewon #309

- LeetCode/212/sumin.py
**풀이 시간: 1시간 30분**
굉장히 까다로웠던 문제였다. 단어가 여러개 주어지기 때문에 단순히 백트래킹 만으로 풀 수 없는데 도저히 어떻게 프루닝을 해줘야 할 지 감이 오지 않아 hint로 트라이를 써야한다는걸 참고했다. Trie 클래스를 구현해서 각 단어들을 미리 트라이에 넣어놓고 프루닝하며 백트래킹해서 통과했다.
아무래도 트라이를 사용하하다보니 메모리 효율성이 좋지 않고, 트라이를 클래스로 구현하여 시간도 다른 코드보다 느리다.
빠른 코드들을 확인해보니 굉장히 간단하게 트라이를 구현한 걸 확인할 수 있었다.
> [2024-10-31] sumin #316

- Programmers/등산코스 정하기/gwangseok.py
<풀이 시간>
1 시간
<문제 회고>
처음엔 prim으로 MST를 만들어서 각 node 마다 출발지까지 intensity를 구하려했다.
그런데 시간복잡도를 구하면 출발, 도착의 각 쌍을 구해야 하기 때문에 $O(N^2)$이 되었다.
그래서 dp아 bfs에서 greedy하게 프루닝을 하여 풀었다.
-- | --
테스트 1 〉 | 통과 (0.03ms, 10.2MB)
테스트 2 〉 | 통과 (0.03ms, 10.3MB)
테스트 3 〉 | 통과 (0.02ms, 10.3MB)
테스트 5 〉 | 통과 (0.02ms, 10.3MB)
테스트 6 〉 | 통과 (0.07ms, 10.2MB)
테스트 7 〉 | 통과 (0.12ms, 10.2MB)
테스트 8 〉 | 통과 (0.08ms, 10.2MB)
테스트 9 〉 | 통과 (0.13ms, 10.2MB)
테스트 10 〉 | 통과 (0.29ms, 10.3MB)
테스트 11 〉 | 통과 (0.24ms, 10.4MB)
테스트 12 〉 | 통과 (0.57ms, 10.2MB)
테스트 13 〉 | 통과 (6.92ms, 11.7MB)
테스트 14 〉 | 통과 (46.30ms, 20.7MB)
테스트 15 〉 | 통과 (584.84ms, 80.5MB)
테스트 16 〉 | 통과 (628.59ms, 83.3MB)
테스트 17 〉 | 통과 (634.04ms, 83.2MB)
테스트 18 〉 | 통과 (26.71ms, 16MB)
테스트 19 〉 | 통과 (134.90ms, 36.1MB)
테스트 20 〉 | 통과 …
> [2024-11-05] gwangseok #324

- LeetCode/212/heewon.py
접근 방식
- 모든 칸에서 가능한 단어의 조합들을 저장한다. - can_word
- 첫 단어가 되는 칸만 탐색 시작 - first_word
- 최대 단어 길이 이상의 탐색은 불가 - max_len
> [2024-10-31] heewon #316

- LeetCode/212/yerin.py
<풀이 시간>
1시간 이상
<문제 회고>
비슷한 문제를 풀었던 기억이 나서 백트래킹으로 접근을 했다. 그런데 시간초과가 났다. 힌트를 보니 트라이라는 자료구조를 확인할 수 있었고 듣기만 해봤던 트라이를 이번 기회에 적용해 볼 수 있었다.
> [2024-10-31] yerin #316

- BaekJoon/12738/sumin.py
**<풀이 시간>**
25분
이전에 [가장 긴 증가하는 부분 수열 2 ](https://www.acmicpc.net/problem/12015)을 풀었던 경험이 있어서 동일한 방식으로 풀이했는데 통과했다. 원소값에 음수가 올 수 있다는 것 외에 차이가 없어서 문제 자체도 차이가 크게 없는 것 같다
> [2024-11-12] sumin #335 

- BaekJoon/12738/gwangseok.py
<풀이 시간>
15분
<문제 회고>
해당 문제를 이전에 2번 정도 풀었었다.
2번 모두 힌트를 참고해 풀었는데, 이번엔 힌트 참고 없이 해결하였다.
[더 어려운 문제](https://www.acmicpc.net/problem/14003)(플레5)도 해보면 좋을 것 같다.
> [2024-11-12] gwangseok #335

- BaekJoon/12738/yerin.py
LIS 알고리즘을 알게 되었다. 시간 초과되는 코드만 생각나서 힌트를 찾다 알게된 것인데, 접근 방식을 보고 아차 싶었다. 크게 어렵지 않은 접근 방식인데 떠오르지 않았다는 게 아쉬웠고, 새로운 접근 방식을 머릿속에 넣을 수 있는 좋은 기회였다고 생각한다.
> [2024-11-12] yerin #335

- BaekJoon/12738/heewon.py
- LIS 알고리즘 공부: DP, 이진 탐색
관련 문제: [DP 풀이 가능](https://leetcode.com/problems/longest-increasing-subsequence/description/)
> [2024-11-12] heewon #335

- BaekJoon/14003/sumin.py
**<풀이 시간>**
1시간 40분
문제를 잘 못 읽어서 output을 계속 수열만 반환해서 틀렸다;;
오랜만에 문제를 [블로그](https://suminii.tistory.com/entry/BOJ-%EA%B0%80%EC%9E%A5-%EA%B8%B4-%EC%A6%9D%EA%B0%80%ED%95%98%EB%8A%94-%EB%B6%80%EB%B6%84-%EC%88%98%EC%97%B4-5-Python)에 정리했다.
> [2024-11-19] sumin #341

- BaekJoon/14500/gwangseok.py
<풀이 시간>
2시간
<문제 회고>
DFS를 사용하면서 최대한 중복을 없애려고 시간을 많이 보냈다.
최대한 중복을 없애려면 broute-force 방법밖에 생각이 안나서 중복을 허용하더라고 DFS로 문제를 풀었다.
'ㅏ' 블럭을 처리하는 방법이 생각 나지 않아 다른 분들 풀이를 참고했다.
> [2024-11-21] gwangseok #344

- BaekJoon/14500/yerin.py
일일이 퍼즐을 구해볼까 하다가 가능한 퍼즐 모양들을 맞춰보니 모두 문제에서 제시된 퍼즐 모양에 국한되는 것을 알았다. 그래서 백트래킹으로 문제를 풀었다. 'ㅗ' 모양은 중간에 끊긴 형태여서 따로 분기처리를 해주었다.
예전에 문제를 풀 때 각기 다른 퍼즐 모양들을 어떻게 처리를 해야할 지 생각해내지 못해서 풀지 못했었는데, 확실히 아이디어를 떠올리는 게 중요한 거 같다는 생각이 들었다,,
> [2024-11-21] yerin #344

- BaekJoon/14003/heewon.py
- 각각의 LIS의 index 값을 저장하여 문제를 풀었지만 반례 존재
- 힌트 get
- 이전의 index만 저장 -> 반례 존재
- 코드 참고
> [2024-11-19] heewon #341

- BaekJoon/14500/heewon.py
- BFS 접근
- DFS는 불가라고 생각함(백트래킹 생각 못 함)
- T 고려 못 함 -> T 경우만 하드 코딩 추가
- 시간 초과
- 브루트포스 + 모듈화를 곁들인
- 우, 하로 탐색을 하는 것을 고려하여 배치 가능한 경우만 고려
- O: 1, I: 2, T: 4, Z: 4 L: 8
- DFS + backtracking
- T를 고려하여 2칸 채우고 처리
- 최대 점수가 불가 하면 return 
- **PyPy3**는 반복적인 계산 작업에서 성능이 우수 (브루트포스 시간 단축 좋음)
- DFS 코드의 경우는 메모리 사용을 고려하여 **Python3**가 좋음
> [2024-11-21] heewon #344

- LeetCode/207/gwangseok.py
<풀이 시간>
30분
<문제 회고>
위상정렬 알고리즘을 알고 있어서 쉽게 풀었다.
어떻게 구현했는지 까먹어서 조금 오래 걸렸다.
> [2024-11-26] gwangseok #349

- BaekJoon/14003/yerin.py
<풀이 시간>
1시간
<문제 회고>
처음에 이차원 dp도 생각해봤지만 수 제한이 너무 컸다. 최대한 O(NlogN)에 맞추고자 이전 코드에 추가적으로 구현하는 방식으로 풀어나갔다.
> [2024-11-19] yerin #341

- LeetCode/198/sumin.py
**<풀이 시간>**
10분
DP 기본 문제라 빠르게 풀이할 수 있었다. 처음에 dp배열로 풀까하다가 생각해보니 이전 두 집값만 가지고 가도 될 것 같아서 변수 두개로 공간복잡도를 줄여봤다.
> [2024-11-27] sumin #355

- LeetCode/207/heewon.py
- Topics 참고 - DFS 알고리즘
- 사이클 유무 찾기
- 시간 초과(중복 방문 처리 필요)
- 추가 checked 리스트 추가 - Topological Sorting 알고리즘
- **Topological Sorting 알고리즘** : 정리 필요
> [2024-11-26] heewon #349

- LeetCode/198/gwangseok.py
<풀이 시간>
10분
<문제 회고>
DP문제로 빠르게 풀었다.
> [2024-11-27] gwangseok #355

- LeetCode/198/yerin.py
<풀이 시간>
30분 내
<문제 회고>
문제 생긴 게 dp 유형과 닮아 있었다. 처음에 식을 생각해내는 걸 고민했는데 손으로 정리하니 금방 규칙을 찾을 수 있었다.
> [2024-11-27] yerin #355

- LeetCode/207/yerin.py
<풀이 시간>
30분 내외
<문제 회고>
선행 과목을 확인하기 위해 dfs로 문제를 풀이했는데, 다른 풀이에 비해 시간이 굉장히 뒤였다.
> [2024-11-26] yerin #349

- BaekJoon/1520/sumin.py
**<풀이 시간>**
40분
단순 DFS로 풀면 중복으로 같은 경로를 탐색할 수 있기 때문에 최악의 경우 O(4**(m*n))이 될 거라고 생각했다.
이전에 DP + DFS를 이용한 비슷한 문제를 풀어봐서 dp로 풀이했다. 
재귀 깊이를 늘려주지 않으면 재귀 깊이 에러가 나서 
BFS로도 풀이해보려고 했지만 큐에 들어오는 순서가 꼬여 heap을 사용해야했다. 이 부분은 짜다가 패스..
> [2024-12-03] sumin #360

- BaekJoon/1520/yerin.py
<문제 회고>
문제를 이해하는 데 오래걸렸다. 처음에 잘못 이해하고 문제를 풀었다가 엥 싶어서 다시 읽어보고 잘못됐음을 깨달았다. dfs만으로는 안풀려서 헤맸는데 dp를 사용한 풀이가 많아서 참고해서 풀게되었다. 그리고 처음엔 pypy를 썼는데 계속 초과됐다고 나와서 파이썬으로 바꾸니 성공했다.
> [2024-12-03] yerin #360

- BaekJoon/1520/gwangseok.py
<풀이 시간>
30분 + $\alpha$
<문제 회고>
이전에 한번 푼 적이 있어서 생각보다 빨리 풀 수 있었다.
recursionlimit 없이 하려고 stack으로 시도 했지만 실패했다.
> [2024-12-03] gwangseok #360

- BaekJoon/1520/heewon.py
- BFS 접근
- 기본 BFS는 시간 초과
- 중복된 계산 발생 -> heap + DP 사용
- heap: 높이가 낮은 순서로 확인
- DP: 해당 칸까지의 모든 경우의 수 저장
> [2024-12-03] heewon #360

- LeetCode/210/sumin.py
**풀이 시간: 10분**
저번 문제와 거의 유사한 문제라 위상정렬로 간단하게 풀이할 수 있었다. 사실상 날먹 문제...
> [2024-12-04] sumin #365

- BaekJoon/10986/heewon.py
- 두 지점 간의 나머지가 같을 때, 해당 부분합이 m의 배수 (힌트 참고)
sum(i, j)%m = 0 ⇔ prefix_sum[j]%m = prefix_sum[i-1]%m
- 각 누적합의 나머지를 저장하는 딕셔너리
ex) {0: 2,  4:2} 나머지가 0인 값 2개, 나머지가 4인 값 2개
- 조합을 이용하여 경우의 수 구하기
> [2024-12-10] heewon #369

- BaekJoon/10986/yerin.py
<문제 회고>
시간 내에 해결할 수 있는 풀이가 생각나지 않아 힌트를 구해 문제를 풀었다.
> [2024-12-10] yerin #369

- LeetCode/73/sumin.py
> [2025-01-23] sumin #384

- LeetCode/73/gwangseok.py
<풀이 시간>
10분
<문제 회고>
직관적으로 풀렸던 문제이다.
> [2025-01-23] gwangseok #384

- LeetCode/300/yerin.py
예전에 증가하는 부분 수열 풀었던 게 생각나서 생각나는대로 문제를 풀었다.
> [2025-01-09] yerin #375

- LeetCode/73/yerin.py
<문제 회고>
Follow up을 고려해서 풀어보려 했는데 떠오르지 않았다. 숫자 제한이 크지 않아 O(n*m)으로도 풀 수 있을 것 같아 생각난대로 풀었다.
> [2025-01-23] yerin #384

- BaekJoon/10986/sumin.py
**<풀이 시간>**
40분
오랜만에 알고리즘을 푸니까 머리가 안돌아가는 거 같아요.
간단하게 누적합과 조합을 이용해서 풀 수 있는 문제였던 것 같습니다!
> [2024-12-10] sumin #369 

- BaekJoon/24041/yerin.py
문제가 어려워 보이지는 않는데 시간 초과가 날까 싶어 고민하는데 시간이 오래 걸렸다. 세균 수가 많은 것부터 버리는 게 좋으니 힙을 사용하는 것은 떠올랐는데 이분탐색이 떠오르지 않아 애먹었다. 저번 문제도 이분탐색 사용하는 문제였는데 매번 기억이 안나는 거 보니 더 연습이 필요한 것 같다.
> [2025-01-21] yerin #376

- Programmers/퍼즐 게임 챌린지/yerin.py
<풀이 시간>
약 30분
<문제 회고>
최소 숙련도를 찾아나가야 하니 이진탐색을 사용했다. 최근 이진탐색 문제였어서 그런지 금방 떠올랐다.
> [2025-01-30] yerin #389

- LeetCode/300/heewon.py
풀었던 문제라서 뭐지? 했다.
광석님 PR 보고 힌트 다 받고 풀었다.
LIS가 기억이 안 났다... 다시 머리에 저장했다.
> [2025-01-09] heewon #375

- BaekJoon/24041/sumin.py
**풀이 시간**: 45분
이분탐색를 아무생각없이 1e9로 했다가 계속 틀리고, 질문 게시판을 본 후에야 2e9로 해줘야 함을 알았다;;
> [2025-01-21] sumin #376

- LeetCode/73/heewon.py
> [2025-01-23] heewon #384

- Programmers/퍼즐 게임 챌린지/gwangseok.py
<풀이 시간>
30분
<문제 회고>
문제 이해하는데 시간이 좀 걸렸다.
이전에 풀었던 성싶당 문제와 유사해 빠르게 풀었다.
Texst|Comlexity
-- | --
테스트 1 〉 | 통과 (0.03ms, 10.3MB)
테스트 2 〉 | 통과 (0.03ms, 10MB)
테스트 3 〉 | 통과 (0.04ms, 10.2MB)
테스트 4 〉 | 통과 (0.12ms, 10.1MB)
테스트 5 〉 | 통과 (0.12ms, 10.2MB)
테스트 6 〉 | 통과 (0.12ms, 10.1MB)
테스트 7 〉 | 통과 (0.21ms, 10.1MB)
테스트 8 〉 | 통과 (6.12ms, 10.2MB)
테스트 9 〉 | 통과 (6.26ms, 10.4MB)
테스트 10 〉 | 통과 (6.27ms, 10.2MB)
테스트 11 〉 | 통과 (10.93ms, 10.2MB)
테스트 12 〉 | 통과 (6.40ms, 10.1MB)
테스트 13 〉 | 통과 (6.15ms, 10.2MB)
테스트 14 〉 | 통과 (5.77ms, 10.3MB)
테스트 15 〉 | 통과 (1994.20ms, 34.9MB)
테스트 16 〉 | 통과 (1855.08ms, 34.8MB)
테스트 17 〉 | 통과 (1899.85ms, 34.8MB)
테스트 18 〉 | 통과 (2064.23ms, 34.5MB)
테스트 19 〉 | 통과 (1801.57ms, 34.1MB)
테스트 20 〉 | 통과 (1917.64ms, 34.7MB)
테스트 21 〉 | 통과 (1918.13ms, 34.8MB)
> [2025-01-30] gwangseok #389

- Programmers/퍼즐 게임 챌린지/heewon.py
약 30분 
level의 최솟값이 0으로 해서 14 테스트 케이스 틀렸네요
<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-variant-emoji: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; color: white; overflow: …
> [2025-01-30] heewon #389
