ksumini/Algorithm-Study2.0

Programmers/도넛과 막대 그래프/dori.py
- 약 2시간 풀이 후 실패로 답지 참조
- 초기 접근
- DFS로 접근하되, 방문마다 visited 배열의 값을 갱신하여 특정 조건에서 종료
- 이후 시작, 8자, 도넛, 막대 각각의 조건을 찾으려했음
- 시작의 경우 본인 노드는 딱 한번 방문, 연결된 나머지 노드들은 전부 방문
- 막대의 경우 본인 노드만 방문
- 8자와 도넛의 규칙을 찾지 못했음
- 하나를 찾으면 다른 하나가 틀리는 현상 발생 ...
- 애초에 입력의 길이가 100만으로 매우 길어 완전탐색으로 풀이가 어렵다는 것을 인지하지 못함
- 힌트
- 방문을 할 필요가 없음, 나가고 들어온 간선의 수만 파악하는 것이 핵심
- 시작 노드에서 모든 그래프들이 생성되기 때문임
- 즉 시작 노드에서 나가는 간선의 수가 총 그래프의 개수
- 이 때문에 모든 방문을 할 필요가 없는 것
- 문제를 대충 읽어 이 부분을 놓친 것이 풀이 실패의 큰 원인 중 하나 인것 같음
- 또한 도넛형 그래프의 경우 복잡하므로, 8자형과 막대기형을 찾고 시작 노드의 간선 수에서 빼버림
- #3
=> [2024-03-14] dohyun #3

Programmers/도넛과 막대 그래프/heewon.py
- `node_in`: Node로 들어오는 노드들
- `node_out`: Node에서 나가는 방향의 노드들
- `shape_cnt`: 모든 모양의 개수
- `nodes`: 모든 노드의 집합
- `node_in`, `node_out`, `nodes` 구하기
- 모든 노드를 탐색하여 모양 개수 찾기
- 각각의 모양의 규칙
- 생성한 정점
- `node_in`이 없고 `node_out`이 2개 이상, 
- 막대 모양
- 노드의 입출의 합이 1이다 -> wrong -> why? 막대 모양의 중간과 생성한 정점이 연결되면 2개로 카운트 됨
- `node_out`이 0 -> 항상 1개 존재하는 막대의 끝 부분 카운트
- 8자 모양
- `node_in >=2 and node_out >= 2` -> 8자 모양의 중심으로 카운트
- 도넛 모양
- 조건이 다른 모양과 겹침 -> 전체 모양 - 막대 모양 - 8자 모양
`defaultdict`
- 노드의 개수와 간선의 개수로 모양을 정하기 가능
- 지수님의 코드 참고
- 문제의 조건을 사용
- 크기가 n인 도넛 모양 그래프는 n개의 정점과 n개의 간선이 있습니다.
- 노드의 수와 간선의 수가 같으면 도넛
- 크기가 n인 막대 모양 그래프는 n개의 정점과 n-1개의 간선이 있습니다.
- BFS 방식이라 나머지 경우
- 크기가 n인 8자 모양 그래프는 2n+1개의 정점과 2n+2개의 간선이 있습니다.
- 노드의 수 + 1 = 간선의 수
`defaultdict`, `deque`
#3
=> [2024-03-14] heewon #3

Programmers/주사위 고르기/dori.py
- 약 2시간 풀이 후 힌트 참조
- 승리할 확률이 가장 높은 주사위 조합은 유일함 -> 완전탐색으로 풀이
- Product + Combination 을 활용해 가능한 쌍을 구할 수 있음
- 경우의수 그대로 구현 후 완전탐색 시 시간초과 발생, 중복되는 계산을 해결해야 함
- 리스트B를 정렬 + 이분탐색을 활용해서 승리 경우의수를 O(logN) 으로 구함
- 정렬하고 나면 특정 cutoff 이후의 값들은 모두 패배가 되기 때문
- #8
=> [2024-03-19] dohyun #8

Programmers/석유 시추/dori.py
- 약 1시간 소요
- BFS/DFS로 하나의 연결된 지점마다 석유의 총 내장량을 찾고 이를 Return
- 중복을 최소화하지않으면 시간초과 발생
- 즉 모든 row, col 을 순회하는 이중 반복문 -> 시간초과
- 집합을 활용하여 한번 탐색할 때 해당 좌표가 뻗어있는 석유의 y 좌표를 반환하여 중복 최소화
- 최종적으로 oil_by_col 딕셔너리에 각 컬럼별 시추량을 저장
- 예제2 예시) {1:12, 2:12, 3:15, 4:14, 5:14, 6:16}
정확성 테스트
- 테스트 1 〉 | 통과 (0.06ms, 10.3MB)
- 테스트 2 〉 | 통과 (0.33ms, 10.2MB)
- 테스트 3 〉 | 통과 (0.07ms, 10.2MB)
- 테스트 4 〉 | 통과 (0.12ms, 10.2MB)
- 테스트 5 〉 | 통과 (0.09ms, 10.2MB)
- 테스트 6 〉 | 통과 (0.78ms, 10.2MB)
- 테스트 7 〉 | 통과 (1.05ms, 10.2MB)
- 테스트 8 〉 | 통과 (0.48ms, 10.4MB)
- 테스트 9 〉 | 통과 (5.26ms, 10.5MB) 
효율성 테스트
- 테스트 1 〉 | 통과 (60.89ms, 16.5MB)
- 테스트 2 〉 | 통과 (166.29ms, 22.5MB)
- 테스트 3 〉 | 통과 (301.17ms, 22.5MB)
- 테스트 4 〉 | 통과 (59.06ms, 16.4MB)
- 테스트 5 〉 | 통과 (675.79ms, 36.4MB)
- 테스트 6 〉 | 통과 (112.01ms, 16.6MB)
- #9
=> [2024-03-21] dohyun #9

Programmers/석유 시추/heewon.py
- `row_oil`: row의 값당 석유의 총양을 저장한 딕셔너리 ex) 1번 예시 : {3: 7, 4: 7, 5: 7, 6: 9, 0: 8, 1: 8, 2: 8, 7: 2}
- `visited`: 석유가 있는 곳은 True, 석유가 없는 곳은 False
- `x_set`: 각 석유 덩어리당 포함된 row(x)의 값들을 set으로 저장
- `oil_size`: DFS, BFS를 통하여 얻은 석유 덩어리의 석유양
- DFS, BFS로 각각의 석유 덩어리당 총 석유양과 포함된 row 값들을 저장한다.
- 각각의 덩어리 탐색이 끝나면 `x_set`에 포함된 row 값들의 석유양 `row_oil`에 추가
- DFS 방법은 recursion limit 설정 필요
- BFS 방법은 효율성 1문제 FAIL
DFS: `defaultdict, sys`
BFS: `defaultdict, deque`
- 시간: 2 hour
- 힌트: `None`
#9
=> [2024-03-21] heewon#9

Programmers/아날로그 시계/jisu_fail.py, Programmers/아날로그 시계/jisu_ref.py
`jisu_fail.py`
- 각 초/분/시침의 위치(각도)를 기반으로 초침이 분/시침을 역전했는지 여부로 카운트
- 3시간 풀이 후 FAIL, 모든 예외 처리 불가
`jisu_ref.py`
- 솔루션 참고
- [ref1](https://school.programmers.co.kr/questions/71323)
- [ref2](https://school.programmers.co.kr/questions/64706)
- 초/분/시침 위치 기반 접근이 아닌, 한 바퀴(12시간, 43200초)에 각 침이 몇 번 돌아가는지에 대한 수리적 접근
- 초/분/시침이 정확히 겹쳐 중복 알람이 울리는 것에 대한 예외 + 시작 시점에 알람이 울리는 것에 대한 예외 추가
- #24
=> [2024-03-28] jisu #24

Programmers/요격 시스템/jisu.py
``` text
1 <= targets <= 500,000
0 <= s < e <= 100,000,000
```
- 완전탐색 불가, 로직이 필요
1. 폭발 범위 끝 기준으로 오름차순 정렬
2. 가장 끝에서 폭발(e가 가장 큰)하는 s를 기준, 범위가 겹치는 폭발(기준 s보다 큰 e)을 계속 pop() -> 동시 요격 가능
2-1. 이 때 범위가 겹치는 폭발에서 s가 더 크면 기준 s를 업데이트 (동시 요격 가능한 추가 폭발)
2-2. 더 이상 기준 s보다 큰 e를 가진 폭발이 없으면 새로 쏴야 함 -> 해당 폭발을 기준으로 다시 1로 돌아감
테스트 1 〉 | 통과 (0.01ms, 10.5MB)
-- | --
테스트 2 〉 | 통과 (0.02ms, 10.5MB)
테스트 3 〉 | 통과 (0.08ms, 10.5MB)
테스트 4 〉 | 통과 (0.47ms, 10.7MB)
테스트 5 〉 | 통과 (9.03ms, 11.9MB)
테스트 6 〉 | 통과 (89.63ms, 26.4MB)
테스트 7 〉 | 통과 (638.18ms, 91.4MB)
테스트 8 〉 | 통과 (682.07ms, 91.4MB)
테스트 9 〉 | 통과 (645.25ms, 77.7MB)
테스트 10 〉 | 통과 (215.45ms, 73.3MB)
테스트 11 〉 | 통과 (0.00ms, 10.6MB)
- #34
=> [2024-04-04] jisu #34

Programmers/연속된 부분 수열의 합/jisu.py
- 투포인터 접근
- 매번 sum을 구하면 연산량이 너무 큼 -> weighted_sum으로 합계 관리
- 초기 left 0 / right 0 으로 세팅 (k가 sequence[0]인 엣지케이스)
- weighted_sum < k 인 경우 right를 늘려 수를 하나 합산
- weighted_sum > k 인 경우 left를 늘려 왼쪽 수를 하나 제거
<details>
테스트 1 〉 | 통과 (0.01ms, 10.5MB)
-- | --
테스트 2 〉 | 통과 (0.01ms, 10.6MB)
테스트 3 〉 | 통과 (0.05ms, 10.6MB)
테스트 4 〉 | 통과 (0.28ms, 10.6MB)
테스트 5 〉 | 통과 (4.52ms, 10.8MB)
테스트 6 〉 | 통과 (8.83ms, 11.1MB)
테스트 7 〉 | 통과 (19.36ms, 12MB)
테스트 8 〉 | 통과 (32.50ms, 13.7MB)
테스트 9 〉 | 통과 (110.50ms, 17MB)
테스트 10 〉 | 통과 (205.00ms, 27MB)
테스트 11 〉 | 통과 (283.78ms, 43.7MB)
테스트 12 〉 | 통과 (330.17ms, 43.4MB)
테스트 13 〉 | 통과 (325.95ms, 43.4MB)
테스트 14 〉 | 통과 (302.74ms, 43.5MB)
테스트 15 〉 | 통과 (335.79ms, 43.6MB)
테스트 16 〉 | 통과 (183.49ms, 51.9MB)
테스트 17 〉 | 통과 (456.46ms, 51.9MB)
테스트 18 …
=> [2024-04-17] jisu #47

Programmers/수레 움직이기/dori.py
- 약 2시간 풀이 후 실패로 힌트 참조 - 약 3시간 더 풀이 후 실패
- 두 원이 겹쳐질 때에 대한 예외처리
- 이동 전과 이동 후의 R, B 순서 바뀌었을 때
- 두 원을 같은 곳에 이동시킬 때
- 빨강, 파랑 두 원의 움직임을 병렬적으로 구현할 지, 하나를 먼저 이동시켜놓고 발자취를 기록해놓을지 선택
- BFS로 구현하면 후자를 선택해야하는데 너무 복잡함
- 입력 개수가 매우 작으니 가능한 모든 경우를 탐색, 백트래킹을 활용
- 종료 조건 : 둘 다 정답에 도달 했을 때 탐색 종료
- 일부 테케에서 통과 못해 힌트 참조 -> 풀이 로직은 거의 똑같은 것 같은데 dx, dy 순서에 따라서 답이 달라짐?!
- 방문 순서에 따라서 답이 달라진다는 뜻 왜..?
- 그냥 몇 개 안되니 direction 순열로 다 때려박고 가장 최소값을 정답인 것으로 해결
- 하려 했으나 테케 7번, 9번에서 실패
- 반복문에서 빨강 대신 파랑을 먼저 돌리면 테케 7번만 실패..?
- 뭔가 굉장히 잘못 설계한 것 같은데 도저히 디버깅 불가해서 그냥 이렇게 제출하고 여러분들의 풀이를 공부하겠습니당 .. ㅜㅠ
-----
```
테스트 1 〉	통과 (0.23ms, 10.3MB)
테스트 2 〉	통과 (0.77ms, 10.4MB)
테스트 3 〉	통과 (0.40ms, 10.3MB)
테스트 4 〉	통과 (0.19ms, 10.5MB)
테스트 5 〉	통과 (0.17ms, 10.3MB)
테스트 6 〉	통과 (1.34ms, 10.4MB)
테스트 7 〉	실패 (2.32ms, 10.2MB) <<<<<
테스트 8 〉	통과 (1.78ms, 10.2MB) …
```
=> [2024-04-09] dohyun #35

Programmers/혼자서 하는 틱택토/gwangseok.py
<풀이 시간>
1시간
<문제 회고>
문제를 보고 같은 row, column은 2번 방문하면 시간이 걸릴 것 같아 2중 for문으로 필요한 정보를 얻었다. 
그러다 보니 예외 처리를 해야 할 부분이 생겨서 오래 걸렸다.
다른 분들 코드를 여러번 방문하는 게 보기 깔끔하고 시간이 덜 걸린다.
[파이썬은 function call 비용이 비싸다는 것](https://brorica.tistory.com/139)을 알게 되었다.
- Global dict table에 많은 함수들의 정보가 있어 원하는 identitifer(함수)를 찾으려면 시간이 소모된다. O(log N)
- 파이썬 코드를 실행하기 위해선 내부적으로 많은 모듈들이 실행된다.
- 호출 횟수가 엄청 크지 않는 이상 성능 저하가 크지 않다. 
- 하지만, 코테에서 특정 기능을 빠르고 반복적으로 수행해야 할 경우 repeat 대신 iterable을 지향하자.
- 추가로 함수 호출이 느린 또 다른 이유 -> Monkey Patch: 런타임에 attribute를 동적으로 결정하것
- 즉, C나 JAVA처럼 컴파일 과정에서 매개변수를 실체화하는 것이 아니라 런타임에 추상적인 매개변수를 실체화하기 때문에 함수 호출 비용 증가.
- 내장 함수는 C로 되어 있기 때문에 더 빠르다.
all이나 any 함수를 사용할 때, generator를 활용하면 memory/time에서 더 효율적이다.
- all([a for a in b])보단 all(a for a in b)를 사용하자.
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.4MB) …
=> [2024-06-04] gwangseok #78

Programmers/표현 가능한 이진트리/gwangseok.py
<풀이시간>
30분
<문제 회고>
포화 이진 트리와 완전 이진 트리 차이점을 몰라서 검색을 해봤다.
포화 이진 트리에 대해 파악한 후, 루트 노드를 기준으로 search를 해야 겠다라고 생각했다.
1. 수를 이진수로 만든다.
2. 이진수를 포화 이진 트리로 표현하기 위한 트리의 depth를 계산한다 -> d = int($log_2$(binary_length)) + 1 // 1e15의 depth는 6
3. 포화 이진 트리로 표현되어야 하는 이진수의 length를 계산한다. -> $2^d$ - 1  // 1e15의 length는 63
4. 이진수 앞에 '0'을 추가해 포화 이진 트리로 표현되는, 더미가 추가된 이진수를 구한다.
4.1. 예를 들어, 13이면 binary length는 4이고 depth d는 3이 된다. 
4.2. 더미를 포함한 13의 binary length는 $2^d$ - 1인 7이된다. 즉, '0001101'이 되어야 한다.
5. 더미가 추가된 이진수를 tree의 루트(가운데)를 기준으로 분할정복을 활용해 가능한지 불가능하지 검사한다.
5.1. 예를 들어, 13의 경우 root는 3번째 index인 1이 된다.
5.2. 1을 기준으로 왼쪽, 오른쪽으로 나눈다. '000', '1', '101'
5.3. '000'에서 다시 root를 구한다. 1번째 index인 0이다. 
5.4. root가 0이므로 자식 노드가 없어야 한다. -> 좌,우가 모두 0인지 확인한다. 1이 하나라도 있으면 False 반환
5.5. 모두 0이므로 '000'에 대해선 True이다.
5.6. '101'에서 root를 …
=> [2024-06-06] gwangseok #84

Programmers/호텔 대실/yerin.py
<풀이 시간>
30분
<문제 회고>
입실 시간이 퇴실 시간 보다 항상 빠르다는 조건과 자정을 넘어가지 않는다는 조건이 있어 시간 비교만 하면 되겠다고 생각했다. 예약 시간들을 분 단위로 맞추어 계산 용이하도록 했다. 딕셔너리에 방 번호를 키로, 현 이용객의 퇴실 시간 + 10분을 값으로 하여 다음 이용시간을 확인할 수 있도록 했다.
로직은 크게 아래와 같이 정리할 수 있다.
- 다음 이용 가능 시간보다 체크인 시간이 빠른 경우, 새로운 방 부여
- 체크인 이전에 퇴실한 방이 있으면 해당 방 부여
datetime으로도 풀어보려고 했으나 time함수 사용여부에 따라 결과가 달라졌다. time()을 쓰면 실패로 뜨는데 이유를 아직 못찾았다.
<time() 사용 --> 실패>
```
for check_in, check_out in book_time:
check_in = datetime.strptime(check_in, "%H:%M").time()
check_out = datetime.strptime(check_out, "%H:%M")
next_available_time = (check_out + timedelta(minutes=10)).time() 
```
<time() 미사용 --> 성공>
```
for check_in, check_out in book_time:
check_in = datetime.strptime(check_in, "%H:%M")
check_out = datetime.strptime(check_out, "%H:%M")
next_available_time = check_out + …
```
=> [2024-06-18] yerin #97

Programmers/무인도 여행/yerin.py
<풀이 시간>
30분
<문제 회고>
예전에 프로그래머스에서 풀었던 [시추 문제](https://school.programmers.co.kr/learn/courses/30/lessons/250136)와 유사해서 금방 풀이법을 생각했다. 근데 변수명을 오타내서 의도치않은 결과가 나와 시간 소모가 있었다. bfs로 문제를 풀 때 같은 실수를 반복하는데 주의해야겠다.
이전 문제들에서 성호님께서 그룹 넘버를 만들어 그룹 별로 데이터를 정리하셨던 것이 평소 문제 풀이를 떠올릴 때 도움이 될 것 같아 기억해두고 있었는데, 시추 문제와 이번 문제 모두 활용해 보았다. 그 외에도 bfs에서 이전에 중복 탐색으로 시간 초과가 났던 경험이 떠올라 해당 부분을 주의해서 코드를 짰다.
여러모로 지금까지 이 스터디에서 풀어왔던 문제들에서 배운 것들을 활용해 볼 수 있었던 문제였다.
테스트 케이스 | 결과
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.4MB)
테스트 2 〉 | 통과 (0.04ms, 10.4MB)
테스트 3 〉 | 통과 (0.08ms, 10.3MB)
테스트 4 〉 | 통과 (0.87ms, 10.5MB)
테스트 5 〉 | 통과 (1.53ms, 10.4MB)
테스트 6 〉 | 통과 (4.41ms, 10.3MB)
테스트 7 〉 | 통과 (1.37ms, 10.3MB)
테스트 8 〉 | 통과 (7.95ms, 10.6MB)
테스트 9 〉 | 통과 (8.04ms, 10.6MB)
테스트 10 〉 | 통과 (5.86ms, 10.7MB)
테스트 11 〉 | 통과 (5.70ms, 10.7MB)
테스트 12 〉 | 통과 …
=> [2024-06-25] yerin #114

Programmers/억억단을 외우자/yerin.py
<풀이 시간>
2시간 이상
<문제 회고>
e의 최대값이 5,000,000이었어서 시간 효율성을 많이 생각하고자 했다. 규칙을 찾는 과정에서, 빈도수가 약수의 개수와 일치함을 알았다. 그런데 머릿속에는 효율이 좋지 못한 코드만 떠올라 인터넷을 참고했다.
약수의 개수를 구한 후에는, start별로 결과값을 찾아줘야 했다. 여기서 한 번 계산했던 결과를 또다시 계산하는 건 비효율적이니 한 번에 계산한 후, 인덱스로 값을 찾는 식으로 구현했다.
store_max_divisors 함수가 그러한 역할을 수행한다. 사실 처음에는 해당 코드를 solution함수 내부에 적었다가 시간 초과가 나서 모듈로 분리를 했는데 시간 초과가 해결이 됐다. 로직도 같은데 결과가 차이가 나는 것이 아직도 의문이다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.1MB)
테스트 3 〉 | 통과 (0.06ms, 10.3MB)
테스트 4 〉 | 통과 (0.37ms, 10.1MB)
테스트 5 〉 | 통과 (0.82ms, 10.2MB)
테스트 6 〉 | 통과 (4.65ms, 10.3MB)
테스트 7 〉 | 통과 (9.83ms, 10.4MB)
테스트 8 〉 | 통과 (54.11ms, 11MB)
테스트 9 〉 | 통과 (1365.28ms, 28.5MB)
테스트 10 〉 | 통과 (8384.99ms, 91.5MB)
=> [2024-06-27] yerin #123

Programmers/숫자 타자 대회/sungho.py
풀이 시간
1시간
문제 회고 및 풀이
손가락 움직임을 가장 적게 가져가면서9가중치0 숫자들을 다 칠 때 가중치를 구하는 문제이다
처음에 문제를 bfs로 풀었는데 시간초과가 떴다 조건을 최대한 걸어서 되도록 했었는데도 시간초과가 떠서
가장 작은 가중치에 초점을 잡고 heap을 이용해서 다시 문제를 통과하였고 가중치를 매번 구하는 것이 아닌 정한 값을 사용하도록 가중치 테이블을 만들어 시간을 한번 더 줄였다
테스트 시간
| 테스트 번호 | 결과   | 시간      | 메모리    |
|-------------|--------|----------|----------|
| 테스트 1    | 통과   | 0.16ms   | 10.4MB   |
| 테스트 2    | 통과   | 0.16ms   | 10.4MB   |
| 테스트 3    | 통과   | 0.19ms   | 10.5MB   |
| 테스트 4    | 통과   | 0.27ms   | 10.3MB   |
| 테스트 5    | 통과   | 0.18ms   | 10.3MB   |
| 테스트 6    | 통과   | 0.20ms   | 10.4MB   |
| 테스트 7    | 통과   | 0.32ms   | 10.4MB   |
| 테스트 8    | 통과   | 0.20ms   | 10.4MB   |
| 테스트 9    | 통과   | 0.38ms   | 10.4MB   |
| 테스트 10   | 통과   | 0.19ms   | 10.2MB   |
| 테스트 11   | 통과   | 0.53ms   | 10.3MB   |
| 테스트 12   | 통과 …
=> [2024-07-04] sungho #136

Programmers/숫자 타자 대회/gwangseok.py
<풀이 시간>
1 시간 30분
<문제 회고>
문제를 보고 greedy로 해결하려고 했다.
하지만 예 #2는 greedy로 해결이 불가능하다.
완전탐색은 2^1000000이라 시간초과가 난다.
DP로 해결해야 겠다고 생각했다.
고민을 많이 한 것 같다.
손가락이 위치할 수 있는 좌표: 10 * 10 = 100 
한번 옮길 때 발생하는 경우의 수: 2 * 100 = 200
복잡도: O(200 * N) = O(N)
Case | Compexity
-- | --
테스트 1 〉 | 통과 (0.07ms, 10.4MB)
테스트 2 〉 | 통과 (0.10ms, 10.5MB)
테스트 3 〉 | 통과 (0.09ms, 10.5MB)
테스트 4 〉 | 통과 (0.16ms, 10.5MB)
테스트 5 〉 | 통과 (0.18ms, 10.5MB)
테스트 6 〉 | 통과 (0.25ms, 10.5MB)
테스트 7 〉 | 통과 (0.22ms, 10.5MB)
테스트 8 〉 | 통과 (0.40ms, 10.5MB)
테스트 9 〉 | 통과 (0.23ms, 10.4MB)
테스트 10 〉 | 통과 (0.23ms, 10.6MB)
테스트 11 〉 | 통과 (0.97ms, 10.5MB)
테스트 12 〉 | 통과 (0.89ms, 10.5MB)
테스트 13 〉 | 통과 (1.60ms, 10.4MB)
테스트 14 〉 | 통과 (1.44ms, 10.4MB)
테스트 15 〉 | 통과 (1.24ms, 10.5MB)
테스트 16 〉 | 통과 (1596.04ms, 63.3MB)
테스트 17 〉 | 통과 (2448.59ms, 94.8MB)
테스트 18 〉 | 통과 …
=> [2024-07-04] gwangseok #136

Programmers/숫자 타자 대회/yerin.py
처음에는 시간 초과로 머리를 싸맸다. deque를 활용해서 숫자별 거리값들을 이차원 리스트에 저장을 했었다. 리스트가 커질수록 계산량이 많아지기 때문에 시간 초과가 난 것이라 생각하여(명확한 근거x. 좀 더 공부가 필요) 숫자별 거리값을 모두 저장하는 게 아니라 마지막 숫자를 제외하고 나머지는 갱신 후 삭제가 되도록 만들고자 했다. 그리고 숫자 좌표로 이동 후 (왼손, 오른손) 좌표가 같으나 거리값은 다른 경우 최솟값으로 저장하게 하고 싶은데 리스트에서는 방법이 떠오르지 않아 딕셔너리로 변경했다. (당시 데이터 구조를 '왼손, 오른손, 누적거리'로 구상했었다)
이후에는 반례를 찾느라 시간을 다썼다. 이전 코드(가장 먼저 커밋한 코드가 통과 못한 코드)를 보면, 숫자 좌표와 왼손이나 오른손 좌표가 같은 위치에 있는 경우를 따로 조건식을 두어 거리값을 갱신했었다. 그런 경우, 가중치가 1이니 당연히 최소 거리겠지 싶어 그렇게 작성을 했던 것인데 이전 거리값에 따라 1만 더하는 경우여도 최소가 아닐 수 있다는 걸 뒤늦게 생각해냈다.
사실 거리값을 구하는 함수에서 가중치 1인 경우도 반환해주기 때문에 조건식을 뺄 필요도 없었던 건데 케이스를 나누다 오히려 내가 함정을 만들어 버린 꼴이 되었다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.45ms, 10.3MB)
테스트 2 〉 | 통과 (0.47ms, 10.4MB)
테스트 3 〉 | 통과 (0.48ms, 10.4MB)
테스트 4 〉 | 통과 (0.48ms, 10.3MB)
테스트 5 〉 | 통과 (0.49ms, 10.3MB)
테스트 6 〉 | 통과 …
=> [2024-07-04] yerin #136

Programmers/등대/yerin.py
등대의 개수(n)의 범위가 10만 이하여서 완전 탐색으로 풀어봐야겠다는 생각을 했다. 그런데 코드 구현 방법을 떠올리지 못했다. [힌트를](https://www.ai-bio.info/programmers/133500) 찾아보니 on, off 값을 저장해서 비교하는 방식을 취하고 있었다.
힌트에서는 재귀를 활용했는데 깊이 제한을 건들이지 않고 stack으로 풀어보고자 했다. 수민님이 저번에 스택으로 dfs를 구현하셨던 걸 참고하기도 했다. 그 과정에서 아직 스택을 어떤 식으로 활용할 수 있을지 고민하고 공부할 필요가 있다고 느꼈다.
전반적으로 dp와 스택을 더 공부해보면 좋을 것 같다는 생각이 드는 시간이었다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (372.81ms, 50.2MB)
테스트 2 〉 | 통과 (425.14ms, 50.4MB)
테스트 3 〉 | 통과 (346.36ms, 49.9MB)
테스트 4 〉 | 통과 (373.25ms, 50.1MB)
테스트 5 〉 | 통과 (358.49ms, 50MB)
테스트 6 〉 | 통과 (288.78ms, 51MB)
테스트 7 〉 | 통과 (328.66ms, 51.2MB)
테스트 8 〉 | 통과 (286.42ms, 50.2MB)
테스트 9 〉 | 통과 (241.50ms, 51.1MB)
테스트 10 〉 | 통과 (312.96ms, 49.9MB)
테스트 11 〉 | 통과 (109.22ms, 29.8MB)
테스트 12 〉 | 통과 (59.58ms, 21.3MB)
테스트 13 〉 | 통과 (29.47ms, 13.7MB)
테스트 14 〉 | 통과 (0.01ms, …
=> [2024-07-11] yerin #143

Programmers/등대/sumin.py
<풀이 시간>
2시간 이상
<문제 회고>
처음에 그리디로 접근해서 풀이했다.
각 리프노드의 부모 노드를 모두 켜주는 식으로 진행하면 된다고 생각했고, 반례를 찾지 못했다.
결국에 [아이디어](https://school.programmers.co.kr/questions/74238)를 참고해서 DP로 접근해야 한다는 것을 확인했다.
동적 프로그래밍(DP) 접근법은 각 노드의 상태를 정의하고, 모든 가능한 선택을 고려하여 최적의 해를 계산할 수 있다. 
특히, DFS + DP를 사용하면 **각 노드가 켜져 있는 경우**와 **꺼져 있는 경우**를 모두 고려할 수 있기 때문에, 단순히 현재 단계에서 최적의 선택을 하는 그리디와 달리, 전체 트리 구조를 고려해 최적의 해를 보장할 수 있다.
반례 계속 못찾다가, n=8, lighthouse=[[1, 2], [2, 5], [1, 4], [4, 6], [1, 3], [3, 7], [7, 8]]
이 반례를 찾을 수 있었다. [여기](https://school.programmers.co.kr/questions/39676)에 누군가 아주 친절하게 그림까지 그려주셨는데, 내가 처음에 짠 그리디로 풀이하면 해당 결과를 3으로 반환하기 때문에 틀린 코드가 된다는 것을 확인할 수 있다.
+ 트리 순회의 경우 DFS를 재귀 방식과 스택 방식 모두 구현해서 제출해봤는데 재귀 방식이 약간 더 빠른 걸 확인할 수 있었다. (하지만, 여전히 재귀 깊이를 늘려주지 않으면 시간초과 난다.)
테스트 케이스 | 재귀(런타임, 메모리) | 스택(런타임, 메모리) 
-- | -- | -- 
테스트 1 …
=> [2024-07-11] sumin #143

Programmers/등대/sungho.py
풀이 시간
3시간 이상
문제 풀이 및 회고
최소 등대만을 이용해서 모든 항구가 서로 이동할 수 있게 만드는 문제이다. dfs로 쉽게 풀릴 줄 알았는데 안 풀려서 당황했었고 greedy로 어떠한 조건에 맞게 풀려했는데 실패했다.
그래서 dp와 dfs를 활용해서 문제를 풀어보았지만 set을 써서 remove를 써도 list를 써도 계속 시간 초과가 나고 제대로 짠 거 같은데 안 돼서 결국 힌트를 보게 되었는데 sys.recursionlimit만 적어주니 풀리게 되었다
다른 사람들 풀이에서 recursionlimit이 없이도 풀리는데 없이 푸는 걸 더 연습해보아야겠다 다시 봐야할 문제로 일단 체크했고 한달내로 다시 풀어봐야겠다
|-------------|------|------------|---------------|
| 테스트 1    | 통과 | 244.94ms   | 67.9MB        |
| 테스트 2    | 통과 | 219.92ms   | 68.3MB        |
| 테스트 3    | 통과 | 258.45ms   | 67.7MB        |
| 테스트 4    | 통과 | 199.91ms   | 67.9MB        |
| 테스트 5    | 통과 | 221.98ms   | 66.1MB        |
| 테스트 6    | 통과 | 227.69ms   | 66.9MB        |
| 테스트 7    | 통과 | 214.49ms   | 67.4MB        |
| 테스트 8    | 통과 | 197.70ms   | …
=> [2024-07-11] sungho #143

Programmers/부대복귀/sumin.py
**<풀이 시간>**
30분
**<문제 회고>**
가중치가 모두 1이기 때문에 다익스트라까지 갈 필요없이 BFS로 풀이하면 된다.
BFS도 sources의 각 원소마다 destination까지의 거리를 구하지 않고, 역으로 destination에서 각 지역까지의 거리를 BFS로 구하면 시간내에 통과할 수 있다. 오랜만에 Level 3이지만 어렵지 않은 문제였던 것 같다 🤔 
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.1MB)
테스트 4 〉 | 통과 (0.01ms, 10.1MB)
테스트 5 〉 | 통과 (0.02ms, 10.2MB)
테스트 6 〉 | 통과 (18.24ms, 16MB)
테스트 7 〉 | 통과 (30.35ms, 16.8MB)
테스트 8 〉 | 통과 (25.53ms, 22.1MB)
테스트 9 〉 | 통과 (7.75ms, 13.7MB)
테스트 10 〉 | 통과 (17.78ms, 14.5MB)
테스트 11 〉 | 통과 (742.77ms, 114MB)
테스트 12 〉 | 통과 (755.25ms, 114MB)
테스트 13 〉 | 통과 (705.11ms, 114MB)
테스트 14 〉 | 통과 (746.35ms, 114MB)
테스트 15 〉 | 통과 (702.93ms, 114MB)
테스트 16 〉 | 통과 (113.79ms, 43.1MB)
=> [2024-07-18] sumin #160

Programmers/부대복귀/yerin.py
최단 거리를 구하기 위해 sources 요소마다 bfs를 도는 것은 비효율적이라고 생각했다. 그래서 모든 거리값을 한 번에 계산하도록 하고자 했다.
처음에는 문제를 풀다가 sources의 숫자를 지역번호가 아니라 거리라고 착각해버렸다. 다시 문제를 제대로 읽고 목적지에서 갈 수 있는 모든 지역을 탐색하는 식으로 풀이를 변경했다.
테스트 | 결과
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.4MB)
테스트 3 〉 | 통과 (0.01ms, 10.3MB)
테스트 5 〉 | 통과 (0.01ms, 10.2MB)
테스트 6 〉 | 통과 (13.49ms, 16.2MB)
테스트 7 〉 | 통과 (14.99ms, 16.9MB)
테스트 8 〉 | 통과 (20.79ms, 21.9MB)
테스트 9 〉 | 통과 (6.90ms, 13.9MB)
테스트 10 〉 | 통과 (7.64ms, 14.4MB)
테스트 11 〉 | 통과 (485.94ms, 109MB)
테스트 12 〉 | 통과 (475.57ms, 109MB)
테스트 13 〉 | 통과 (510.72ms, 109MB)
테스트 14 〉 | 통과 (518.66ms, 109MB)
테스트 15 〉 | 통과 (489.15ms, 109MB)
테스트 16 〉 | 통과 (93.46ms, 38.6MB)
=> [2024-07-18] yerin #160

Programmers/택배 배달과 수거하기/sumin.py
**<풀이 시간>**
40분
**<문제 회고>**
전에 풀어 본 문제라 그리디로 풀이해야 한다는 점은 빠르게 알 수 있었으나,
계속해서 2번 테스트케이스에서 틀려서 시간이 오래 걸렸다. 
기존 코드에서 배달 지점과 수거 지점의 초기화를 0으로 해뒀었는데, 이렇게 하면 배달과 수거 값 모두 0인 경우 왕복거리를 0이 아닌 2를 반환해 틀리게 된다. 해당 부분을 -1로 초기화 해준 후 해결했다. 제출 후에 다른 사람들 풀이를 보다 보니 역순으로 누적합을 구해 풀이하는 간결한 코드도 있던데 잘 이해가 가지 않는다.
-- | --
테스트 1 〉 | 통과 (0.01ms, 10.3MB)
테스트 2 〉 | 통과 (0.00ms, 10.4MB)
테스트 3 〉 | 통과 (0.02ms, 10.3MB)
테스트 4 〉 | 통과 (0.02ms, 10.3MB)
테스트 5 〉 | 통과 (0.04ms, 10.2MB)
테스트 6 〉 | 통과 (0.03ms, 10.3MB)
테스트 7 〉 | 통과 (0.74ms, 10.3MB)
테스트 8 〉 | 통과 (1.97ms, 10.1MB)
테스트 9 〉 | 통과 (10.19ms, 10.4MB)
테스트 10 〉 | 통과 (5.90ms, 10.4MB)
테스트 11 〉 | 통과 (2.86ms, 10.3MB)
테스트 12 〉 | 통과 (5.10ms, 10.3MB)
테스트 13 〉 | 통과 (2.31ms, 10.3MB)
테스트 14 〉 | 통과 (3.84ms, 10.3MB)
테스트 15 〉 | 통과 (60.09ms, 11.6MB)
테스트 16 〉 | 통과 (1706.91ms, …
=> [2024-07-27] sumin #166 

Programmers/2차원 동전 뒤집기/sumin.py
**<풀이 시간>**
2시간 이상
**<문제 회고>**
처음에는 매번 보드판의 상황을 복제해서 뒤집기를 실행할 경우, 해당 행들을 직접 다 뒤집어주고 target과 같은지 비교했는데 일부 테스트 케이스에서 시간초과가 났다. 실제로 매번 뒤집기를 실행하지 않고, 비트 연산을 사용해 해당 행 또는 열이 뒤집어진지 확인하여 비교하는 식으로 풀이를 변경했다. 또, 뒤집은 후 하나의 칸이라도 target과 다르면 바로 false를 반환하는 방식으로 변경하니 시간초과 없이 통과됐다. 
백준에도 [동전 뒤집기](https://www.acmicpc.net/problem/1285)라는 비슷한 유형의 문제가 있는데 그거보다 더 까다로웠던 것 같다.
-- | --
테스트 1 〉 | 통과 (1429.64ms, 10.1MB)
테스트 2 〉 | 통과 (5.23ms, 10.4MB)
테스트 3 〉 | 통과 (70.99ms, 10.2MB)
테스트 4 〉 | 통과 (74.33ms, 10.2MB)
테스트 5 〉 | 통과 (236.78ms, 10.2MB)
테스트 6 〉 | 통과 (31.01ms, 10.2MB)
테스트 7 〉 | 통과 (50.16ms, 10.2MB)
테스트 8 〉 | 통과 (7.83ms, 10.2MB)
테스트 9 〉 | 통과 (4.07ms, 10.2MB)
테스트 10 〉 | 통과 (10.55ms, 10.2MB)
테스트 11 〉 | 통과 (1286.10ms, 10.2MB)
테스트 12 〉 | 통과 (1027.80ms, 10.1MB)
테스트 13 〉 | 통과 (1015.38ms, 10.1MB) …
=> [2024-07-25] sumin #167 

LeetCode/210/heewon.py
- 위상 정렬 접근
- 여러 조건과 변수를 추가하여 성공
- 기존의 위상 정렬 코드만 사용해도 충분
시간: 1hr 이하
[수정 전]
[수정 후]
=> [2024-12-04] heewon #365

LeetCode/210/yerin.py
<풀이 시간>
20분
<문제 회고>
이전에 알게된 위상정렬을 활용하여 문제를 풀었다. 사이클이 있는지를 확인하는 과정에서 처음에 리스트에 in을 썼더니 시간이 느리게 나와, set을 따로 만들어주었다. 이전에 풀었던 문제와 큰 차이가 있지 않아서 생각보다 금방 문제가 풀렸다.
=> [2024-12-04] yerin #365

BaekJoon/10986/gwangseok.py
<풀이 시간>
1시간
<문제 회고>
고민 끝에 생각이 나지 않아 문제 유형을 힌트로 보았다.
누적합 문제인 것을 파악안 후 쉽게 풀었다.
<풀이1>
- 0 ~ i 까지의 합을 cum_num list에 저장한다.
- k index에서 M으로 나눠 떨어지는 후보를 고르려면 누적합이 k index와 동일한 index까지 값을 빼주면 된다. 
- 중복을 고려해 누적합 값이 같은 index 2개를 조합한 수를 구한다.
- 누적합이 0인 것은 자기 자신을 포함해서 수를 세준다.
<풀이2>
- 누적합을 따로 list에 저장하지 않고 이전 까지의 누적합해서 같은 값을 가지는 index의 수를 dictionary 형태로 저장한다.
- k index에서 M으로 나눠 떨어지는 후보를 고르려면 누적합이 k index와 동일한 index까지 값을 빼주면 된다. 
- 중복을 고려해 누적합 값이 같은 index 2개를 조합한 수를 구한다.
- 누적합이 0인 것은 자기 자신을 포함해서 수를 세준다.
=> [2024-12-10] gwangseok #369
